1단계 - 질문 삭제하기 기능 리팩토링
next-step/java-bowling pull request #254
Opened 2020-09-03 15:06 UTC by pcspapa

안녕하세요. 박찬석입니다.

1단계 - 질문 삭제하기 기능 리팩토링 리뷰 요청드립니다.

리팩토링을 어디까지 완성을 해서 보내야 하는지 항상 고민입니다.
우선 초안을 작성했습니다. 
추가 혹은 부족한 부분이 있으면 알려주세요.

고맙습니다.

2020-09-04 10:51 UTC, wheejuni requested changes
전반적으로 리팩토링 잘 진행해 주셨는데요,
하나만 더 해보고 넘어가면 좋을 것 같습니다. 
이부분 코멘트로 남겨드렸으니 확인 부탁드릴게요! 감사합니다.

2020-09-04 10:51 UTC, wheejuni commented on src/main/java/qna/domain/Question.java
> +      deleteHistories.add(answer.delete(loginUser));
이 부분은 `Stream` 이용해서 리팩토링 시도해보시면 어떨까요?

2020-09-04 13:07 UTC, pcspapa commented on src/main/java/qna/domain/Question.java
> +      deleteHistories.add(answer.delete(loginUser));
```suggestion
    answers.forEach(answer -> answer.delete(loginUser));
```
처음에는 Stream 으로 작성을 하려고 했으나

```suggestion
    answers.forEach(
        answer -> {
          try {
            deleteHistories.add(answer.delete(loginUser));
          } catch (CannotDeleteException e) {
            throw new RuntimeException(e);
          }
        });
```
기존 소스에서 CannotDeleteException 을 Checked Exception 으로 만들어 놓아서foreach 로 구현을 하였습니다. 

Checked Exception 보다는 Unchecked Exception 리팩토링 후 Stream 으로 구현도 고민을 했지만 기존 소스를 변경하지 않으려고 했습니다.

좋은 방법이 있으면 알려주세요.

2020-09-05 06:34 UTC, wheejuni commented on src/main/java/qna/domain/Question.java
> +      deleteHistories.add(answer.delete(loginUser));
@pcspapa 어느정도는 오버 엔지니어링 처럼 보이기는 합니다만...
https://www.slipp.net/questions/572 읽어 보시고, 한 번 시도해 보시겠어요?

2020-09-07 12:43 UTC, wheejuni approved these changes
수고 많으셨습니다! 👍 
2단계로 넘어가도 될 것 같습니다.
merge 하겠습니다~

2020-09-07 12:44 UTC, merged