2단계 - 볼링 점수판(그리기)
next-step/java-bowling pull request #255
Opened 2020-09-03 16:11 UTC by antksk

안녕하세요 김승겸 입니다. 
볼링 점수판 그리기 작업하여 PR 드립니다.

볼링에 대한 도메인 지식이 없어서 ^^;; 
코딩하는 것보다.. 볼링 자료 찾고 이해 하는데 
더 많은 시간을 사용한것 같네요 ^^;

최대한 TDD로 작업하려고 노력했고, 
도메인 지식이 부족한것 같아서 ^^ 아래  test coverage 처럼 테스트를 많이 하려고 하였습니다.
![image](https://user-images.githubusercontent.com/1481137/92139502-c6e35800-ee4a-11ea-9e3e-bde122253be5.png)

그리고, 많은 도메인 지식을 클라언트 코드(BowlingGame)에 
노출되지 않도록 패키지 레벨 제한을 하였으며, 작은 단위로 클래스를 유지하고,
작업들을 서로 나눠서 할수 있도록 구성하였습니다.

한 예로, BowlingGame이 진행되면, 
Player가 투구(Rolling)를 하게 되면 프레임(Frames)을 생성해서, 
결과를 역으로 취합하는 형식으로 구성하였습니다.

리뷰 부탁드립니다.

감사합니다. ^^

2020-09-05 07:13 UTC, sah3122 requested changes
요구사항 구현을 잘해주셨네요 😄 
이번에도 깔끔한 코드와 상세한 테스트 코드가 너무 좋았습니다. 
코드를 파악하는데 시간이 많이 걸려 리뷰가 늦어진점 죄송합니다 😢 
구조적인 부분에 대해서 몇가지 코멘트를 달아두었는데 확인 부탁드립니다 !

2020-09-09 01:44 UTC, antksk commented on src/main/java/bowling/domain/Frames.java
> +        zeroBaseCurrentFrameIndex = 0;
의견 감사합니다. ^^ 
그렇게 작성하게 되면 생성되는 Frame을 불변객체로 설계할수 있을것 같아,
처음에 그렇게 생각하고 작업을 진행하였으나, 

두가지 정도 설계에 문제가 발생해서 이렇게 작성하였습니다.
1. 두번째 투구가 발생해서  한번 더 기회가 주어 지는 경우, 두번째 투구가 완료 될때 까진 Frame 객체를 불변으로 만들수 없다.
2. Frame 객체의 필드 갯수가 2개 이상이 될 확률이 높아 진다.

위와 같은 이유로 미리 프레임을 만들어 놓고, 투구상태(RolledResult)를 불변객체로 
설계하는 방법으로 고민하게 되었습니다.

2020-09-09 02:28 UTC, antksk commented on src/main/java/bowling/domain/Rolling.java
> +final class Rolling {
^^ 네 맞습니다.제 코드를 자세히 봐주셔서 감사합니다. ^^

Rolling이 Fraems 클래스의 기능을 대행해주는것이 맞습니다.

아래의 규칙들 때문에 이런식으로 구성하게 되었습니다.

- 규칙 6: 모든 엔티티를 작게 유지한다.
- 규칙 7: 3개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다.

Frames에 모든 기능을 위임하다 보면, 필드가 금방 3개가 될 것 같았습니다.

필드를 2개로 유지 하려다 보면, 클래스들이 작게 나눠지게 되는데, 
작은 클래스가 많아 지다 보면, 다음과 같은 특징이 생기는 것 같습니다.

1. 사실상 같은 기능을 하지만 클래스 별로 의미가 달라지기 때문에 다른 이름을 사용하는 메소드가 만들어 의미 전달을 을 새롭게 함(예를 들어 Rolling 클래스의 isPlayable()메소드)
2. Player가 Frames클래스를 직접 보지 않고 Rolling 클래스를 보기 때문에, Frames 클래스보다 적은 동작 방식을 알게됨
(Player는 Frames의 currentFrameIndex() 등 Frames에 특화된 내용에 직접 접근하지 못함)

위의 내용은 양날의 검과 같이, 장단점이 있지만, 
같은 동작을 하는 메소드를 작게 유지 하면서 메소드 이름으로 의미를 최대한 전달하려 노력하는 것과 같이, 
어떤 정보를 클래스로 표현할때, 작은 단위로 클래스를 만들어서 적절하게 더 작은 단위로 묶어서 
의미를 전달하는 하는 연습을 해보고 싶었습니다.

2020-09-09 02:29 UTC, antksk commented on src/main/java/bowling/domain/Rolling.java
> +    void roll(int fallenPins){
의견 감사합니다. ^^ 좋은 생각인것 같아요 ^^
TwoFallenPins 클래스를 만들어서 의견 주신 내용 적용했습니다.

2020-09-09 02:37 UTC, antksk commented on src/main/java/bowling/domain/core/AbstractTowFallenPins.java
> +    protected static final int MAX_TOW_FALLEN_PINS_SIZE = 2;
Frame 클래스는 가변으로 설계하고, 
거기에 담기는 RolledResult클래스를 불변으로 생각했는데요;

제가 알고 있는 불변 클래스는 다음과 같습니다.
- 완전 불변객체 : 내부 필드가 변하지 원시타입이거나 레퍼런스 타입도 모두 변하지 않는 형태
- 반 불변 객체 : 불변 객체 자체는 변화가 없으나 필드로 갖는 객체가 레퍼런스 타입, 일급콜렉션 으로 내부에서 변경이 되는 경우


RolledResultFactory 내부에서 동작할때는 가변 객체로 TwoFallenPins를 사용하고, 
RolledResult로 등록될때는 완전불변객체(ImmutableTwoFallenPins)로 변경하는 작업을 하기 위해 중간에 추상 클래스를 하나 구성하여 공통적인 부분을 제거(pull up)하였습니다.

2020-09-09 02:55 UTC, antksk commented on src/main/java/bowling/domain/core/IncompleteState.java
> +final class IncompleteState implements RolledResult {
의견 감사합니다. ^^ 좋은 아이디어 인 것 같아요 ^^ 
처음부터 가변 객체나 반 불변객체 혹은 생성자 초기값 전달기법등으로 설계 했다면, 
말씀 해주신 내용으로 작업하는게 좋았을 것 같습니다.

그런데, 제가 설계할때 투구 결과(RolledResult) 상태를 나타내는 클래스 들은 완전불변객체로 
생성되는 순간부터 상태가 결정되어 있기를 원했습니다. 
그래서, 상태가 완료되지 않은 IncompleteState클래스도(이 또한 완전불변객체로 설계함)
중간에 만들어 넣었던것 같습니다.


말씀해주신 내용으로 설계가 되었다면, 아마 Miss 클래스의 상태가 완료여부를 체크해야,
본인의 상태가 Miss인지, Gutter인지 알수 있기 때문에, 불완전한 상태가 상태 객체에 존재해야 된다고 생각했습니다.


이건 개발 방식에 따라 자기 스타일이 있는것 같은데요 ^^ 

저는 이런 상황이 생길때...(상태객체를 를 표현할때), 
처음에 enum을 고려해보고, 처음 부터 고정할수 없으면,
"완전 불변객체"로 모델링해서 완전히 상태가 변경되지 않도록 구성하는 걸 선호 합니다.

이렇게 코드를 작성하면, 상태 변경 유무를 플래그등으로 확인하지 않고 객체로 평가 할수 있기 때문에 
장점이라고 생각합니다. ^^;

물론 지적해 주신것과 같이, 의미가 크지 않은 IncompleteState와 같은 클래스가 생성되는 것은 단점이라고 생각됩니다. ^^

^^ 앞에서 언급했듯이 그래서 이 부부은 자기 스타일이 있고, 성향에 따라 개발 방향이 달라지는 부분인것 같아요.

2020-09-09 02:56 UTC, antksk commented on src/main/java/bowling/domain/core/Pins.java
> +
의견 감사합니다. ^^ 
TwoFallenPins 클래스가 판단하도록 변경했습니다. ^^

2020-09-09 02:57 UTC, antksk commented on src/main/java/bowling/domain/core/AbstractTwoFallenPinsRolledResult.java
> +abstract class AbstractTwoFallenPinsRolledResult implements RolledResult {
ㅠ.ㅠ 짬짬히 작업하다 보니, 
Two를 Tow라고 작성하고 뒤늦게 발견해서 ㅠ.ㅠ 
여기서 부터는 오타 수정 정도로 생각해주시면 될것 같아요 ^^;

2020-09-09 02:58 UTC, antksk commented on src/main/java/bowling/domain/Rolling.java
> +        return null != firstBowlRolledResult && firstBowlRolledResult.isNotCompleteState();
의견 주신 내용으로 코드 개선해서, 관련 코드 제거 했습니다. 
감사합니다. ^^

2020-09-09 02:58 UTC, antksk commented on src/main/java/bowling/domain/Rolling.java
> +        return null == firstBowlRolledResult;
의견 주신 내용으로 코드 개선해서, 관련 코드 제거 했습니다. 
감사합니다. ^^

2020-09-10 02:01 UTC, sah3122 approved these changes
피드백에 대한 상세한 설명 감사합니다 :) 
전체적인 구조가 더 잘 이해 되는것 같아요 😄 
간단한 피드백 한가지 남겨두었습니다. 
다음 미션을 진행해주시면 될것 같은데 구현의 복잡도를 조금 낮춰 보는것도 좋을것 같습니다 !

2020-09-10 02:02 UTC, merged

2020-09-10 02:05 UTC, antksk commented on src/main/java/bowling/domain/core/TwoFallenPins.java
> +    public RolledResult toRolledResult() {
좋은 의견 감사합니다. ^^ 
저도 같은 생각을 해서.. 
불변객체 최적화 작업을 진행할때.. ^^(다음 단계에서)
진행해 보겠습니다.
 
의견 주셔서 감사합니다. ^^

2020-09-10 02:10 UTC, antksk commented on src/main/java/bowling/BowlingGameApplication.java
> +public class BowlingGameApplication {
ㅎㅎㅎ의미 없는 이스터 에그 같은 부분이였는 데...
발견해 주셨군요 ^^ㅎㅎㅎ

BowlingGame.gameLoop에서 player.whileRoll 동작이 끝난후에 
보드판을 출력해서 발생하는 현상인데요;

편의상 UI 부분이라 크게 신경 쓰지 않고 도메인 코드에만 집중하다 보니 
미쳐 수정을 못했습니다. 다음번 작업에서 수정하겠습니다.

다시한번... 상세하게 코드 봐주셔서 감사드립니다. ^^