Step2
next-step/java-bowling pull request #269
Opened 2020-09-12 07:41 UTC by bass84

안녕하세요 이재석 리뷰어님.
바쁘셨을텐데 1단계 리뷰를 몇 시간만에 해주셔서 바로 2단계 PR 요청 드릴 수 있게 되었습니다.

이전 프로젝트인 사다리 게임 하면서 시간될 때 구현을 미리 해 놓아서 오늘 바로 요청드릴 수 있게 되었네요.^^
참고로 이번주 방송에서 포비님께서 view 로직은 신경 쓰지 않아도 된다고 해서 좀 덜 신경쓰긴 했습니다.ㅎㅎ
이번 단계도 잘 부탁드립니다.

감사합니다.

2020-09-12 08:14 UTC, seogi89 requested changes
기능 구현 정말 잘해주셨네요 👍 
미리미리 준비하신 부분도 대단하시네요 😭 

다만 책임이 불필요하게 나눠져 있고, 관계가 너무 복잡하게 얽혀있어서 가독성이 약간 떨어지는 것 같아요.
클래스간의 관계를 그려보고 불필요한 객체가 없는지 점검해보면 좋을 것 같아요.

물론 지금 상태가 나쁘다는것은 아니니 그대로 다음 미션 진행해주셔도 됩니다.
그럴 경우 다시 PR 주세요 :) 

몇가지 관련한 코멘트 남겨 놓았으니 확인 부탁드립니다.

2020-09-12 08:14 UTC, seogi89 commented on src/main/java/bowling/BowlingGame.java
> +	private final ScoringBoard scoringBoard;
ScoringBoard 를 특별히 분리한 이유가 있으실까요 ? 

첫번재 볼링 게임이 프레임과 플레이어를 가질수도 있었을 것 같아요.

2020-09-12 08:14 UTC, seogi89 commented on src/main/java/bowling/BowlingGame.java
> +		return scoringBoard.reflect(pins);
`reflect` 어떤 의미로 사용하고 계신가요 ? 🤔

2020-09-12 08:14 UTC, seogi89 commented on src/main/java/bowling/frame/FinalFrame.java
> +		int currentPitchingCount = pitchingResults.getPitchingCountToDate();
pitchingResults 가 스스로 게임의 종료를 판별 할 수 있지 않을까요?

2020-09-12 08:14 UTC, seogi89 commented on src/main/java/bowling/frame/Frames.java
> +	}
프레임이 종료 될때 다음 프레임을 추가하는 방식으로 구현 한다면 인스턴스 변수를 하나 줄일 수 있을 것 같은데
어떻게 생각하시나요 ?

2020-09-12 08:14 UTC, seogi89 commented on src/main/java/bowling/pin/Pins.java
> +		return this.knockingDownPins == 0;
0도 상수로 분리 할 수 있을 것 같아요.

2020-09-12 08:14 UTC, seogi89 commented on src/main/java/bowling/pitching/PitchingResults.java
> +	}
상수들이 어떤 의미를 가지는지 잘 모르겠어요.

2020-09-12 08:14 UTC, seogi89 commented on src/main/java/bowling/pitching/PitchingState.java
> +public enum PitchingState {
enum 을 통해서 상태를 잘불리해주셨네요.

다만, 클래스 자체가 너무 복잡한 것 같아요
enum -> class 형태로 변경해볼 수 있을까요 ? 🤔

2020-09-12 08:14 UTC, seogi89 commented on src/main/java/bowling/pitching/status/PitchingResult.java
> +public class PitchingResult {
`Pins` 만 가지고, Result 를 만들 수 있을 것 같아요 .

조금 더 고민 해볼 수 있을까요?

2020-09-12 11:27 UTC, merged

2020-09-13 03:22 UTC, bass84 commented on src/main/java/bowling/frame/NormalFrame.java
> +	private final int frameNo;
이건 이번 단계에서는 사용되지 않았는데 요청 드릴 때 이 부분은 제거하지 않고서 올렸었네요.

3단계 구현된 것을 보셔서 아실 거라고 생각되는데요,
이 frameNo를 Score에 넘긴 후 이것을 이용해서 PitchingState의 getNextPitchingCountToReflect()를 호출할 때 사용하는 용도로 쓰게 됩니다.^^
각각의 프레임을 담당하는 Frame 인스턴스에서 자기 자신의 순서를 아는 게 맞다고 생각이 들기도 해서 가지고 있는 게 좋다고 생각도 들구요.

2020-09-13 03:34 UTC, bass84 commented on src/main/java/bowling/BowlingGame.java
> +	private final ScoringBoard scoringBoard;
이 부분은 두가지를 고려하였습니다.

1.  볼링게임은 어떤 구조로 되어있고 이것을 어떻게 구현할까 고민했는데
`볼링게임`은 `점수판`을 가지고 있고,
`점수판`은 `전체프레임`, `선수이름`, `점수` 등을 가지고 있고
`전체프레임`은 각각의 `프레임`을 가지고 있고... 등등으로 구조를 만들었습니다.
그래서 가장 상단인 `볼링게임`의 바로 다음 계층인 `점수판`을 고려해서 만든 게 ScoringBoard였구요.

2. 현재는 한명만 하는 게임이지만, 볼링 게임은 보통 여러명이 함께 하죠.
그것을 고려해서 리팩토링이 있다고 가정하였을 때, 
ScoringBoard이 없다면 현재 구조상으로는 Frames를 리스트로 가지고 있는 방식이 될 것 같습니다.
Frame을 리스트로 가진 것이 Frames인데 이것을 또 다시 리스트로 가지고 있는 건 오히려 가독성 측면에서 좀 더 불편하겠다는 생각이 들었습니다.
위에서 점수판을 ScoringBoard로 구현했다고 말씀드렸는데, 이것은 각 한 사람의 점수판을 의미합니다.
그래서 여러 사람이 게임을 하게 되면 모두가 하나의 ScoringBoard를 가지게 되어 이것을 리스트 또는 일급 컬렉션으로 구현해야겠다고 생각을 했죠.
마침 혹시나 해서 마지막 단계 미션을 보니 여러명이 하는 게임이더라구요.^^

위의 두가지 이유로 ScoringBoard를 따로 분리하게 되었습니다.

2020-09-13 03:36 UTC, bass84 commented on src/main/java/bowling/BowlingGame.java
> +		return scoringBoard.reflect(pins);
선수가 투구한 공으로 쓰러뜨린 핀이 `Pins`이고 이것을 점수판에 반영하겠다는 의미로 reflect로 사용하였습니다.

2020-09-13 03:49 UTC, bass84 commented on src/main/java/bowling/frame/FinalFrame.java
> +		int currentPitchingCount = pitchingResults.getPitchingCountToDate();
먼저는 pitchingResults는 각각의 프레임에서 투구한 결과를 가지고 있는 것이라 한 개의 프레임에 종속이 되는 구조입니다.

NormalFrame 경우에는 다음 프레임으로 넘어갈 수 있냐를 판단하는 pitchingResults.isDonePitchingOfCurrentFrame() 를 통해서 현재 프레임이 종료되었다는 것을 판단할 수 있지만, 
게임이 종료되었다는 판단을 pitchingResults가 하기 위해선 pitchingResults가 가지고 있어야 할 정보가 더 많은 것 같습니다. 예를 들어, 마지막 프레임인지, 투구 횟수가 2회인지 3회인지 등등을 알아야 하는데 이것들을 마지막 프레임만을 위해 pitchingResults가 멤버변수로 가지고 있는 건 좋은 방식은 아니겠다는 생각이 들었구요. 메서드에 파라미터로 굳이 두 개의 정보를 넘겨서 하는 게 좋을지도 좀 고민이 되었던 것 같습니다.

재석 리뷰어님의 의견을 듣고 싶습니다.^^

2020-09-13 03:51 UTC, bass84 commented on src/main/java/bowling/frame/Frames.java
> +	}
그 방식을 고려했었는데 사실 그렇게 하는 것과 제가 구현한 것의 차이를 잘 모르겠더라구요.
그래서 제가 조금 편하게 생각한 방식으로 하였습니다.
전체 프레임을 관리하는 Frames를 이미 생성해두었고 저는 이것이 리스트로 관리하는 게 좀 더 낫겠다는 판단을 했는데요.

말씀하신대로 하면 어떤 이점이 있을까요?

2020-09-13 04:02 UTC, bass84 commented on src/main/java/bowling/pitching/PitchingState.java
> +public enum PitchingState {
사실 이 부분은 제가 제일 많이 고민했던 부분이거든요.ㅎㅎ
진짜 많은 고민 끝에 enum으로 구현했어요.ㅎㅎ
큰 문제가 아니라면 유지해도 괜찮을까요??ㅜㅜ

2020-09-13 04:09 UTC, bass84 commented on src/main/java/bowling/pitching/status/PitchingResult.java
> +public class PitchingResult {
`Pins`로도 말씀하신 것 같이 Result를 만들 수 있다고 생각하는데요,
그게 맞는지는 조금 고민이 됩니다.
Pins는 쓰러뜨려진 핀만 담당하면 되고,
그것에 대한 결과를 Pins가 가지고 있어야 하는지는 좀 의문이 드는데요.

Pins로 Result를 만드는 것이 어떤 면에서 좋은 걸까요...?

2020-09-13 04:15 UTC, bass84 commented on src/main/java/bowling/pitching/PitchingResults.java
> +	}
화면에 보여주기 위한 용도로 쓰는 쓰러진 핀의 개수를 조회하기 위한 메서드이구요,
- 현재까지 투구 결과로 쓰러진 핀이 10개 이하인 경우엔
프레임의 투구 순서와 상관없이 마지막 쓰러진 핀의 숫자를 화면에 보여준다.

- 현재까지 투구 결과로 쓰러진 핀이 10개 이상인 경우엔
마지막 프레임이라는 의미이고, 마지막 프레임에서는 쓰러뜨리는 핀의 개수가 10개를 넘길 수 있기 때문에
이것을 화면에 보여줄 때는 10을 쓰러뜨린 핀의 갯수로 나눈 나머지의 값을 화면에 보여준다.

이런 의미로 보시면 될 것 같습니다.

2020-09-13 09:16 UTC, bass84 commented on src/main/java/bowling/BowlingGame.java
> +	private final ScoringBoard scoringBoard;
이거 다시 생각을 해봤는데 BowlingGame은 현재 ScoringBoard에 전달만 하는 정도로 사용하니 ScroingBoard보단 BowlingGame을 제거하는 게 어떨까란 생각이 드네요.^^

2020-09-13 23:37 UTC, seogi89 commented on src/main/java/bowling/pitching/PitchingState.java
> +public enum PitchingState {
제 의견일 뿐이니까 요한님께서 좋다고 생각하시는데로 유지해주시면 됩니다 :)

2020-09-13 23:38 UTC, seogi89 commented on src/main/java/bowling/pitching/PitchingResults.java
> +	}
설명이 필요한 부분을 코드로서 해석 가능하도록 메소드로 분리하거나 매직넘버를 상수로 분리해주시면 좋을 것 같아요.

2020-09-13 23:42 UTC, seogi89 commented on src/main/java/bowling/frame/Frames.java
> +	}
인스턴스 변수자체가 비싼 자원이라고 생각하고 있어서 말씀드렸습니다.
이번 미션에서는 인스턴스 변수를 3개로 제한하고 있고, 나아가 객체지향 생활체조에서는 2개로 제한하고 있는데,
인스턴스 변수를 사용하지 않고도 문제를 해결 할 수 있다면 최대한 아끼는게 좋지 않을까요?

또한 다음 미션에서 인덱스의 증감이 상당히 많았는데, 가독성도 해치는것 같다는 생각이 드네요 🤔

2020-09-13 23:43 UTC, seogi89 commented on src/main/java/bowling/frame/NormalFrame.java
> +	private final int frameNo;
슬랙으로 말씀 나눴듯이, 미션 요구사항에 집중한다면 불필요한 변수인것 같아요.

2020-09-13 23:44 UTC, seogi89 commented on src/main/java/bowling/BowlingGame.java
> +		return scoringBoard.reflect(pins);
전체적으로 reflect 라는 메소드 네이밍을 많이 사용하셨는데, 좀 더 구체적인 네이밍을 사용하면 좋을 것 같아요.
반영하다 라는 행위가 너무 추상적이고 많은 클래스에서 사용하다보니 코드를 읽는데 어려움이 있네요.

2020-09-13 23:47 UTC, seogi89 commented on src/main/java/bowling/pitching/status/PitchingResult.java
> +public class PitchingResult {
Pins -> PitchingResult 가 변환되는 방식이라면 책임이 명확해지고 결합도도 낮출 수 있는 방법이라고 생각하지만
지금은 PitchingResult 가 Pins 를 가지고 있는 형태인데요, 이는 결합도가 높은 상태라고 생각이 되어서 말씀드렸습니다.

이외에도 상당부분이 has -a  하는 방식으로 구현되어 있어 클래스 뎁스가 깊어지고, 유지보수에 어려움이 생길 것 같네요.

2020-09-13 23:53 UTC, seogi89 commented on src/main/java/bowling/frame/FinalFrame.java
> +		int currentPitchingCount = pitchingResults.getPitchingCountToDate();
result 가 상태를 모두 포현하고 있다면 외부의 도움 없이 추가 투구가 있어야할지 구분 할 수 있다고 생각이 드는데요.
별도의 메소드가 필요할 것 같기는 하지만 내부의 값을 외부로 꺼내서 비교하는 행위는 없앨 수 있을 것 같아요.