3단계 - 볼링 점수판(점수 계산)
next-step/java-bowling pull request #284
Opened 2020-09-15 17:52 UTC by pcspapa

안녕하세요. 
3단계 - 볼링 점수판(점수 계산) 리뷰 요청드립니다.
수고하세요.

2020-09-17 01:24 UTC, wheejuni requested changes
리뷰가 늦어져 대단히 죄송합니다.
전반적으로 정말 깔끔히 구현 잘 해주셨습니다. 👍 💯 

간단한 디자인 패턴 적용 등을 추천드리는 세 개의 코멘트를 달았습니다.
체크해주시고, 반영 혹은 추가 질문 부탁드릴게요. 감사합니다.

2020-09-17 01:24 UTC, wheejuni commented on src/main/java/bowling/domain/Bowling.java
> +        .collect(Collectors.toList());
중간의 `frame.score(score)` 부분이 조금 어려워 보이기는 하지만,
`.peek()` 과 같은 중간 처리 연산자를 응용하신다면, 별도의 for loop과 `List` 객체 할당 없이
처음부터 끝까지 하나의 스트림 체인으로 구현하실 수 있으리라 생각됩니다.
한번 시도해보시겠어요?

2020-09-17 01:24 UTC, wheejuni commented on src/main/java/bowling/domain/state/Final.java
> +    return null;
래핑을 통해 `Score` 라는 좋은 클래스를 추출해 주셨는데, 
해당 타입을 리턴 타입으로 갖는 메소드에서 그냥 `null` 을 리턴하는 것은 조금은 아쉽습니다. 

https://johngrib.github.io/wiki/null-object-pattern/ 참고하셔서 null object pattern을 시도해 보시는 것을 추천드려요. 
(모든 실무 상황에서 적용될만한 패턴은 아니고, 학습차 시도를 권해드리는 부분입니다.)

2020-09-17 01:24 UTC, wheejuni commented on src/main/java/bowling/domain/Score.java
> +  }
static factory method 도입을 검토해주세요.

2020-09-17 12:11 UTC, pcspapa commented on src/main/java/bowling/domain/Score.java
> +  }
해당 사항은 반영하였습니다.

2020-09-17 12:12 UTC, pcspapa commented on src/main/java/bowling/domain/Bowling.java
> +        .collect(Collectors.toList());
쉽게 생각을 했는데 답이 안 없네요.
계속 고민을 한 번 해 보겠습니다.
(저도 하나로 만들고 싶어서 PR 보내기 전에 이렇게 저렇게 해 본 곳이라서..)

2020-09-17 12:13 UTC, pcspapa commented on src/main/java/bowling/domain/state/Final.java
> +    return null;
학습차 시도를 한 번 해보겠습니다.
헌데 보내주신 내용에도 있지만 적용 시 넘 큰 작업이 될 것 같네요..

2020-09-17 12:15 UTC, pcspapa commented
리뷰 내용 3 가지에서 
먼저 하나 반영 후 리뷰 요청 드렸습니다.

이제 작게 작게 계속 PR을 보내야 할 것 같습니다.
(미션을 클리어를 위해)

2020-09-17 12:53 UTC, pcspapa commented on src/main/java/bowling/domain/Bowling.java
> +        .collect(Collectors.toList());
```suggestion
    frames.stream()
        .reduce((Score) null, (s, f) -> {
          Score score = f.score(s);
          if (score != null)
            scores.add(score);
          return score;
        }, (a, b) -> b);
    return scores;
```

이렇게는 구현 할 수 있는데 개인적으로 깔끔하지 않네요.

2020-09-17 12:55 UTC, pcspapa commented
리뷰 내용 3 가지에서
먼저 하나 반영 후 리뷰 요청 드렸습니다.

그리고 peek 에 대한 부분은 답을 찾지 못했습니다.
다른 방법을 제안하기는 했는데 개인적으로 더 좋아졌다고 느껴지지가 않네요.

null 에 대한 부분은 학습차원에서 마음에 여유가 있을 때 할까 합니다.
이제 작게 작게 계속 PR을 보내야 할 것 같습니다.
(미션을 클리어를 위해)

2020-09-19 03:30 UTC, wheejuni approved these changes
많은 고민과 학습 해주신 것 같습니다. 💯 👍 
여기까지 해도 충분할 것 같고요, 이제 과정의 마지막 단계로 넘어가주시면 될 것 같아요.

2020-09-19 03:30 UTC, wheejuni commented on src/test/java/bowling/domain/play/PeekTest.java
> +        .forEach(n -> accs.add(acc[0]));
`.peek()` 과 `.forEach()` 의 목적이 다른데, 이번에 학습하시면서 캐치하신 것 같네요. 
(여기에야 뭐 당연히 연습장 개념으로 작성하신 거겠지만) 저는 하나의 스트림 체인에서 `.peek()` 과 `.forEach()`는 병용되면 안된다는 생각은 갖고 있습니다. 
종단 연산자로서 `.forEach()` 가 하는 기능을 중간 연산자 `.peek()` 이 모두 대체할 수 있다고 보기 때문인데요. 
그래서 최대한 중간 연산자 체이닝으로 모든 수정 작업을 마치고, 종단 연산자로는 `.collect()` 만을 사용하는 구현을 선호하기는 합니다.

2020-09-19 03:30 UTC, merged