3단계 - 볼링 점수판(점수 계산)
next-step/java-bowling pull request #315
Opened 2020-09-20 17:41 UTC by enemfk777

안녕하세요 휘준님 :)

볼링 미션 3단계 리뷰 요청드립니다.

기간을 초과할 것 같은 부담감에 구현할 때 생각을 덜하고 PR을 드리는것 같네요...

코드가 읽기 힘드시다면 미리 죄송합니다 ... ㅜㅜ

4단계는 머지 전에 미리 구현을 시작해 둬야 겠습니다...

오늘도 리뷰 미리 감사드립니다 !!

2020-09-22 00:52 UTC, wheejuni requested changes
리뷰가 많이 늦어져 대단히 죄송합니다. ㅠㅠ
3단계까지 진행하시느라 수고 많으셨습니다. 💯 
코드에 대해 개선 의견을 남겨 드렸습니다.
한 번 검토해 보시고, 추가 질문이 생긴다면 언제든지 남겨주세요!

2020-09-22 00:52 UTC, wheejuni commented on src/main/java/bowling/domain/game/Game.java
> +										.collect(Collectors.toMap(Frame::getFrameSequence, Frame::getScore, (frame1, frame2) -> frame1, LinkedHashMap::new));
`Collectors.toUnmodifiableMap` 이라는 것이 있어서요.
https://www.logicbig.com/how-to/code-snippets/jcode-java-8-streams-collectors-tounmodifiablemap.html

바로 여기서 리턴해줘도 될 것 같네요.

2020-09-22 00:52 UTC, wheejuni commented on src/main/java/bowling/domain/score/OpenScore.java
> +		this.accumulatedCount = list;
`Arrays.asList()` 로 리팩토링 어려울까요?

2020-09-22 00:52 UTC, wheejuni commented on src/main/java/bowling/domain/score/OpenScore.java
> +		DownedPinCount sum = accumulatedCount.stream().reduce(DownedPinCount.NO_PIN_DOWN, DownedPinCount::sum);
스트림 체인을 하다 보면 한 라인 자체가 굉장히 길어지는 모습을 볼 수 있는데요, 
이 때 적절히 개행해주시면 조금 더 가독성있는 코드가 완성될 것 같아요. 

```suggestion
        DownedPinCount sum = accumulatedCount.stream()
                                                                            .reduce()....

2020-09-22 00:52 UTC, wheejuni commented on src/main/java/bowling/domain/score/PlayingScore.java
> +
불필요한 blank line이 하나 들어가 있는 것 같습니다!

2020-09-22 00:52 UTC, wheejuni commented on src/main/java/bowling/domain/score/StrikeScore.java
> +	}
지금 비슷한 생성자 로직이 `Score` 의 구현체들에서 반복되고 있는 것처럼 보여요.
이렇게 하나의 타입을 구현하는 구현체 집단에서 반복적인 로직이 발생하는 경우, 
생성자 자체를 정적 팩토리 클래스에 위임하거나(https://johngrib.github.io/wiki/static-factory-method-pattern/)
각 구현체가 공통으로 사용할 생성자/로직만 담은 추상 클래스를 구현하는 것도 추천합니다.
(https://studymake.tistory.com/423)
각 구현체별 분기처리가 필요한 경우엔 생성자를 따로 만들고, `super()` 를 호출한 후 분기 로직을 작성하면 되니까요.
조금 더 간결한 코드로 가는 길이 될 것 같습니다. 단 남용하면 안되지만요.

2020-09-22 13:26 UTC, enemfk777 commented on src/main/java/bowling/domain/game/Game.java
> +										.collect(Collectors.toMap(Frame::getFrameSequence, Frame::getScore, (frame1, frame2) -> frame1, LinkedHashMap::new));
오... 입력 순서대로 순회하며 출력해주려고 LinkedHashMap을 썼다가 Intstream을 이용해서 value를 얻는 방식으로 바꿨는데 이걸 미처 바꾸지 못해뒀네요 :)

2020-09-22 13:35 UTC, enemfk777 commented on src/main/java/bowling/domain/score/OpenScore.java
> +		this.accumulatedCount = list;
Open 상태는 추가 투구가 없으니 고정된 List를 사용할 수 있겠네요 감사합니다 :)

2020-09-22 14:43 UTC, enemfk777 commented
리뷰해 주신 내용 반영해봤습니다 !!

리뷰해 주신대로 absctract 클래스를 적극 사용하니 Score 구현체 클래스의 길이가 줄어들고 보기 좋아졌네요

리뷰 감사합니다 :)

2020-09-23 01:47 UTC, wheejuni approved these changes
다소 모호한 피드백이 아닐까 걱정했는데,
너무나 훌륭히 잘 반영해 주셨네요 👏👏
좋습니다!!
이제 마지막 스텝으로 넘어가주세요!

2020-09-23 01:47 UTC, merged