Step2 - 볼링 점수판(그리기)
next-step/java-bowling pull request #347
Opened 2020-11-27 11:17 UTC by catsbi

안녕하세요 이번 PR은정말 오래걸린거 같습니다. 
첫째로 규칙을 몰라서 규칙이해하는데 걸린 시간이 상당히 오래걸린 것 같네요. 
둘째로는 미션을 잘못봐서 점수계산까지 같이봐버려서 그것까지 하다보니 더 오래걸렸네요 ㅠㅠ...

아무쪼록 잘부탁드립니다 😀

2020-11-28 13:10 UTC, ohtaeg requested changes
안녕하세요 한솔님! 리뷰가 늦어서 죄송합니다 🙏 
기다려주신 만큼 열심히(?) 리뷰하였습니다!! ㅎㅎ

구현을 잘해주셨어요 👍 
몇 가지의 고민거리를 드렸는데, 고민해보신다음 리팩토링해주시면 좋을 것 같아요!
함께 의논할 것이 있다면 편하게 DM을 주시면 감사하겠습니다 😄 
피드백 반영 후 재요청 주세요 :)

2020-11-28 13:10 UTC, ohtaeg commented on src/test/java/step2/domain/StrategyTest.java
> +}
하나의 테스트에서 다루는 것보다 각 전략을 사용하는 테스트에서 생성해주시면 더 좋을 것 같아요!
StrategyTest 를 제거해주시면 좋을 것 같습니다 :)

2020-11-28 13:10 UTC, ohtaeg commented on src/main/java/step2/domain/NormalFrame.java
> +        private BowlingPoint secondPoint;
개인적으로 현재 구조상 firstPoint와 secondPoint를 선택적으로 주입하여
NormalFrame이 생성될 구조는 아닌 것 같아요! 빌더 패턴으로 구현해주신 이유가 있을까요 :) ?

2020-11-30 01:05 UTC, catsbi commented on src/main/java/step2/Main.java
> +    public static void main(String[] args) {
기능 요구사항에는 볼링 투구수를 입력해서 한다는 말이 없어서 자동주입으로 알고있었는데 아니였나보네요....

2020-11-30 01:19 UTC, catsbi commented on src/main/java/step2/domain/NormalFrame.java
> +        private BowlingPoint secondPoint;
모든 초기값을 한 번에 설정할수도 있게끔하려고 넣어놨습니다. 
예전 포비가 getter, setter를 추가하는건 안되지만 생성자는 추가하는것도 나쁘지 않다고 했는데, 생성자에 모든 필드를 추가하기에는 인수갯수가 2개를 넘기에 빌더패턴에 추가해줬습니다.

2020-11-30 01:20 UTC, catsbi commented on src/test/java/step2/domain/StrategyTest.java
> +}
원래 필요한데서 만들어서 쓰다가, 볼링 1미션에서 qna에 Test용 객체를 만든것을 보고 사용해봤는데, 
이런식의 Test객체 모음클래스가 있는것보다 없는게 어떤 장점이 있을까요??

2020-11-30 01:22 UTC, catsbi commented on src/main/java/step2/domain/Frames.java
> +    private final Frame tail;
이번 미션의 요구사항중 링크드리스트로 구현하라는 말이 있어서 head/tail개념으로 한것이거든요... 
※미션 3에서 요구한거였네요 처음에 미션3을 미션2로 잘못봐서... 무튼! 미션3의 힌트중 링크드리스트로 구현하라는 말이 있어서 그렇게 구현한건데, frames에서 여러 frame을 관리하는게 더 나을까요?

2020-11-30 07:48 UTC, ohtaeg commented on src/main/java/step2/Main.java
> +    public static void main(String[] args) {
해당 미션에 입력하라는 설명이 없네요 😭  이 부분은 따로 말씀드리겠습니다 ㅎㅎ 감사합니다 🙇 
프레임당 투구를 수동으로 입력해주시는 미션은 맞습니다 ㅎㅎ

2020-11-30 07:54 UTC, ohtaeg commented on src/main/java/step2/domain/Frames.java
> +    private final Frame tail;
3단계 힌트를 미리 참고하셨었군요 👍 
해당 힌트는 Frames가 아닌 Frame에 대한 내용이였습니다! 물론 Frames를 LinkedList로 구현해도 되는 부분입니다!
Frames라는 네이밍을 통해 일급컬렉션으로 쉽게 착각이 되었네요 🙏 
꼭 힌트처럼 구현할 필요는 없으니 한솔님께서 현재 구조를 유지하시면서 구현해주도 좋을 것 같아요 😄

2020-11-30 07:58 UTC, ohtaeg commented on src/test/java/step2/domain/StrategyTest.java
> +}
해당 설계가 아닌 각각 분리하여 보관한다면
해당 테스트 클래스를 수행하는데 필요한 정보가 해당 클래스 내에 위치해있기 때문에 쉽게 파악이 가능하다는 장점이 있는 것 같아요.

물론 전략을 여러 곳에서 사용이 된다면 위와 같이 모음 클래스를 두는 것도 괜찮다고 생각합니다.
이 부분에 대해서 한솔님께서 어떤 면이 더 좋을지 고민해보신 다음 트레이드 오프 하시면 될 것 같아요 😄

2020-11-30 08:02 UTC, ohtaeg commented on src/main/java/step2/domain/NormalFrame.java
> +        private BowlingPoint secondPoint;
빌더 패턴을 사용하는 접근과 취지는 좋았던 것 같아요!
다만 말씀해주신 것처럼 모든 초기값을 한 번에 설정할수도 있게끔 빌더 패턴을 적용해주셨는데
현재 NormalFrame은 firstPoint와 secondPoint를 한번에 초기화가 되지 않는 구조로 되어있는 것 같아요!

그렇기에 빌더 클래스 내부에서 firstPoint와 secondPoint를 입력받는 메서드는 사용되지 않는 것 같아요.
말씀해주신 취지에 맞게 빌더 패턴을 사용하도록 리팩토링 해주시거나 빌더 패턴을 걷어내면 좋을 것 같아요 😄

2020-11-30 09:22 UTC, catsbi commented
안녕하세요 태경님. 리뷰가 정말 디테일해서 신나서<?> 수정을하는데 쉽지가 않았네요.
정말 대규모적인 수정을... 될수있는한 최대한 객체내 필드수를 줄이려고 노력을 해봤습니다. 

일급 컬렉션으로 BowlingPoints를 만들어서 볼링 투구정보를 넣어놓도록 했습니다. 
잘 부탁드립니다(__)

2020-11-30 15:34 UTC, ohtaeg requested changes
피드백 반영을 잘해주셨어요 👍  한솔님 말씀대로 설계가 많이 변경되었네요 ㅎㅎ
변경해주신 설계에 대해 피드백 몇 개를 드렸습니다! 이번엔 대규모적으로 수정하지 않게(?) 피드백을 드렸습니다!
피드백 확인 후 재요청 주시면 감사하겠습니다 :)


마지막 미션인 만큼 난이도가 높고 고민해야될 점이 많다고 생각합니다.
고민하시는 만큼 좋은 경험이 되실 것 같아요 👍 
같이 의논할 것이 있다면 언제든지 슬랙으로 DM 주세요!
마지막 미션 화이팅입니다 🔥

2020-11-30 15:34 UTC, ohtaeg commented on src/main/java/step2/domain/BowlingPoint.java
> +public class BowlingPoint {
BowlingPoint가 투구에 대한 점수뿐만 아니라 투구에 대한 symbol까지 관리를 하고 있네요 :)
많은 책임이 부여됨으로써 객체의 규모도 커진것 같아요.
볼링 점수 상태를 관리하는 객체를 만들어 책임을 분리한다면 어떤 장점이 있을까요 ~ ?

2020-11-30 15:34 UTC, ohtaeg commented on src/main/java/step2/domain/BowlingPoints.java
> +                || (maxPitches == FINAL_MAX_PITCHES && size() == 2 && getScore(FIRST, SECOND) < STRIKE_VALUE)) {
세부적인 조건들도 조합이 이루어질 경우, 가독성이 낮아지는 단점이 있는 것 같아요!
메서드를 분리하여 의도를 드러내는 것은 어떨까요?

2020-11-30 15:34 UTC, ohtaeg commented on src/main/java/step2/domain/BowlingPoints.java
> +                && getScore() >= STRIKE_VALUE)) {
해당 피드백과 같은 내용입니다 :)

2020-11-30 15:34 UTC, ohtaeg commented on src/main/java/step2/domain/BowlingPoints.java
> +                : BowlingPoint.of(pitchesCount, current.getPoint());
삼항 연산자도 if - else 구문이라고 생각됩니다!
메서드로 분리해주시면 좋을 것 같아요 :)

2020-11-30 15:34 UTC, ohtaeg commented on src/main/java/step2/domain/BowlingPoints.java
> +public class BowlingPoints {
BowlingPoint와 BowlingPoints 둘다 입력된 투구에 따라 상태를 판단하는 로직이 중복해서 관리되고 있네요 ㅎㅎ
해당 피드백과 같이 고민해보시면 좋을 것 같아요 :)

2020-11-30 15:34 UTC, ohtaeg commented on src/main/java/step2/domain/FinalFrame.java
> +    private final BowlingPoints bowlingPoints;
피드백 반영 👍

2020-11-30 15:34 UTC, ohtaeg commented on src/main/java/step2/domain/Frames.java
> +        if (!frame.isFinished() || (frame.isFinished() && frame instanceof FinalFrame)) {
instanceof를 사용한다는건 LSP 원칙을 위반한다는 뜻으로 해석이 가능합니다.
더 나아가 확장에도 열려있지 않다는 뜻으로 OCP 원칙도 위반된다고 할 수 있습니다.
타입이 추가될때마다 타입 확인을 할 필요가 있는지 고민해보시면 좋을 것 같아요!
instanceof를 사용하지 않도록 리팩토링해주세요 :)

2020-11-30 15:34 UTC, ohtaeg commented on src/main/java/step2/type/PitchesOrderType.java
> +            default:
switch 문도 if - else if 구문과 동일하게 취급됩니다!
switch 문을 제거해주는 방향으로 리팩토링 해주시면 좋을 것 같아요 :)

2020-11-30 15:34 UTC, ohtaeg commented on src/main/java/step2/type/ResultPitchesType.java
> +public enum ResultPitchesType {
점수에 따른 상태(스트라이크, 스페어 등)를 관리하는 책임을 가진 객체인 것 같아요 👍 
다만 해당 객체에서 점수에 대한 상태를 판단해야하는데, 여러 곳에서 상태 판단을 하고있기에
전체적으로 객체의 응집도가 낮은것 같아요. 상태 책임을 최대한 해당 객체에서 관리할 수 있도록 리팩토링 해보실 수 있을까요 :) ?

2020-11-30 15:34 UTC, ohtaeg commented on src/test/java/step2/BowlingPointTest.java
> +import org.junit.jupiter.api.Test;
BowlingPoints, Player, PitchesOrderType, ResultPitchesType 객체의 테스트 코드가 존재하지 않네여 😭 
해당 객체들의 테스트 코드를 작성해주세요!
테스트 코드가 존재하지 않는다는 것은 테스트 중심이 아닌 기능 중심으로 구현이 되었다고 해석될 수 있습니다!

2020-12-01 09:35 UTC, catsbi commented
이번에는 부족했던 테스트케이스 추가와 심볼을 담당하는 심볼객체(BowlingSymbol)추가를 하였습니다. 
계속 테스트케이스 실패하는게 나오는걸 놓치는게 부끄러워 열심히 케이스 추가해서 테스트를 했는데, 또 나올지 모르겠네요 ㅠㅠ

2020-12-01 16:31 UTC, ohtaeg requested changes
피드백 반영을 잘해주셨습니다 👍  점진적으로 반영이 잘되고 있습니다!
하지만 이번에도 고민해볼 거리가 존재하여 Request changes 하였습니다..!!
다음 미션으로 넘어가고 싶지만, 리팩토링하고 진행한다면 좀 더 수월할 것 같습니다 😂 
드린 피드백들을 참고해주시면 감사하겠습니다 🙇 

마지막 미션인만큼 좀 더 화이팅입니다 💪

2020-12-01 16:31 UTC, ohtaeg commented on src/main/java/step2/domain/BowlingGame.java
> +        frame.pitches(pitchesCount);
Frames 객체는 head만 갖고있기 때문에 결국, 피칭할때마다 head부터 순차적으로 검색해야하는 단점이 존재하는 것 같아요. 

Frames가 피칭할때마다 List나 다른 자료구조에 Frame이 추가되는 구조로 바뀐다면 자료구조의 마지막 데이터만
찾을 수 있다면 현재 프레임으로 갖고올 수 있을 것 같아요.
그렇게 되면 피칭할때마다 탐색하는 불필요한 반복 작업이 개선될 것 같은데 어떻게 생각하시나요 :) ?

2020-12-02 02:42 UTC, catsbi commented on src/main/java/step2/domain/BowlingGame.java
> +public class BowlingGame {
본디 GameHistory및 GameHistories를 만들어 결과나 결과 DTO를 만들어 반환하기 위한곳이였다가 리팩토링 후 현재의 책임은 Frames의 생성과 투구 후 풀프레임 현재상황을 반환입니다. 현재는 그래서 Controller에 합쳐도 무방해보이나 n명 그리기나 스코어까지 반환할것을 생각하면 Controller보다는 Game에 있는게 더 맞지 않나 싶습니다

2020-12-02 04:13 UTC, catsbi commented on src/main/java/step2/controller/BowlingController.java
> +        Frames frames = dto.getFrames();
네 현재 dto가 레이어간 이동에 쓰이질 않는것 같아 제외했습니다 😊

2020-12-03 08:35 UTC, catsbi commented
안녕하세요 태경님, 이번 PR에서는 Symbol 인터페이스와 구현객체(STRIKE, SPARE, MISS, GUTTER, NONE)을 이용해 상태패턴을 추가하고, BowlingSymbols 일급 컬렉션을 추가해 책임을 분산해봤습니다. 
ResultPitchesType에서 심볼생성책임을 추가했으며, 상태패턴적용하는 방법을 책임사슬패턴으로 해당 타입에서 Stream을 돌려서 적용해봤는데, 우선 테스트케이스는 통과하고 제가 실행하였을 때는 문제가 없었습니다 ㅠㅠ.. 

Frame뿐아니라 Point나 Symbols등 대부분의 객체들이 Normal과 Final을 혼용해서 쓰다보니 책임을 담당하기 위해 추가되는 로직이 많아지는 것 같아서 인터페이스 분리를 하여 다형성을 추가해야하나 고민이 됩니다 ...

2020-12-03 16:40 UTC, ohtaeg commented on src/main/java/step2/domain/BowlingGame.java
> +public class BowlingGame {
앗 그러시다면 다음 미션을 위해 살려두시면 좋을 것 같아요 👍

2020-12-03 17:23 UTC, ohtaeg approved these changes
피드백 반영을 잘해주셨습니다 👍 
볼링미션 시작 단계에서 생각보다 많은 피드백을 드렸었네요 🙏 
끝까지 지치시지 않고 따라와주셔서 감사합니다.
"인내는 쓰고 열매는 달다." 라는 말처럼 지금은 쓰지만 미션 완료 후에는 달콤한 열매를 수확하실겁니다 ㅎㅎ
몇 개의 피드백을 드렸는데 다음 미션을 진행해주시면서 함께 반영해주세요!
다음 미션도 화이팅입니다 🔥

2020-12-03 17:23 UTC, ohtaeg commented on src/main/java/step2/domain/BowlingPoints.java
> +    private final int maxPitches;
completed필드가 제거가 된다면 해당 필드도 제거해볼 수 있을 것 같네요 :)

2020-12-03 17:23 UTC, ohtaeg commented on src/main/java/step2/state/GutterSymbol.java
> +    private final int point;
point를 정수 타입이 아닌 BowlingPoint나 BowlingPoints로 관리하면 어떤 장점이 있을까요 :) ?

2020-12-03 17:23 UTC, ohtaeg commented on src/main/java/step2/state/StrikeSymbol.java
> +public class StrikeSymbol implements Symbol {
Strike, Spare 등의 객체들은 Symbol을 구현함을 시그니처로 알 수 있기 때문에 각 상태 네이밍에서 Symbol을 제거해도 괜찮을 것 같아요 :)
```suggestion
public class Strike implements Symbol {
```

2020-12-03 17:25 UTC, merged