1단계 - 질문 삭제하기 기능 리팩토링
next-step/java-bowling pull request #352
Opened 2020-12-05 02:01 UTC by siyoon210

잘 부탁드립니다!! :)

2020-12-05 20:02 UTC, misudev requested changes
안녕하세요 시윤님~ 볼링미션을 함께하게 된 정미수입니다 😁
서비스레이어 코드를 도메인 객체로 리팩토링 잘 해주셨네요  👍 💯 
몇 가지 코멘트 남겨놨는데 확인 부탁드려요 ! 
벌써 마지막 미션이네요. 끝까지 화이팅입니다  🔥

2020-12-07 13:41 UTC, siyoon210 commented
반환된 DeleteHisotries에 특정 값이 포함되었는지 확인하고 싶었는데 외부로 노출하는건 iterator 뿐이고, 테스트만을 위해서 getter를 추가하는게 탐탁치 않아 iterator를 list로 변환후에 테스트를 진행했습니다. 이 부분은 어떤거 같나요? 🤔

2020-12-07 16:14 UTC, misudev approved these changes
피드백 반영 정말 잘 해주셨네요 👍😀
질문주신 부분은 코드와 함께 코멘트 드렸습니다 ~
확인 하시고, 다음 스텝 진행 부탁드려요 :)
본격적인 볼링 미션 시작이네요 ! 화이팅 입니다 😁

2020-12-07 16:14 UTC, misudev commented on src/main/java/qna/domain/Answer.java
> +        return new DeleteHistory(this, user, LocalDateTime.now());
피드백 반영 잘해주셨습니다 ! 👍👍

2020-12-07 16:14 UTC, misudev commented on src/test/java/qna/domain/QuestionTest.java
> +        assertThat(collect).contains(new DeleteHistory(question, LocalDateTime.now()));
```suggestion
        assertIterableEquals(deleteHistories, Arrays.asList(new DeleteHistory(question, LocalDateTime.now())));
```
이부분이 질문 주신 부분 같은데요 ! 😀 시윤님이 말씀하신 방법도 충분해 보입니다 👍
아니면 위에 처럼 Assertions에서 제공해주는 assertIterableEquals()을 사용해 
Iterable객체간의 비교로 검증하는 방법도 괜찮을 것 같아요 🙂

https://junit.org/junit5/docs/5.0.1/api/org/junit/jupiter/api/Assertions.html#assertIterableEquals-java.lang.Iterable-java.lang.Iterable-

2020-12-07 16:16 UTC, merged