Step1
next-step/java-bowling pull request #353
Opened 2020-12-05 12:13 UTC by changgunyee

## 인사말
안녕하세요. 첫 볼링 첫 리뷰입니다. 😄 
앞으로 잘 부탁드리겠습니다. 🔥

2020-12-05 16:04 UTC, ohtaeg requested changes
안녕하세요 창권님!
마지막 볼링 미션을 같이 함께할 리뷰어 오태경이라고 합니다. ✋
잘 부탁드립니다 🙇 

도메인 객체로 리팩토링을 잘해주셨습니다 💯
고민거리를 남겨드렸는데, 한번 고민해보시면 좋을 것 같아 Request changes 하였습니다.
고민해보신 후, 반영하여 리뷰 요청 부탁드립니다!

함께 의논할 것이 있다면 편하게 DM 이나 코멘트 달아주세요 :)

2020-12-05 22:54 UTC, ohtaeg approved these changes
피드백 반영을 잘해주셨습니다 👍 
이제 마지막 미션인 볼링 미션을 하러 가보실까요? 🎳
다음 미션도 기대하겠습니다 😄

2020-12-05 22:54 UTC, ohtaeg commented on src/main/java/qna/domain/Answer.java
> +        return new DeleteHistory(contentType, getId(), writer, deleteDate);
피드백 반영 👍

2020-12-05 22:54 UTC, ohtaeg commented on src/main/java/qna/domain/Answer.java
> +    public void setDeleted(boolean deleted) {
다음과 같이 객체의 멤버를 변환하는 메서드는 외부에서 접근하지 못하도록 최소화 하시면 좋을 것 같아요!
```suggestion
    private void setDeleted(boolean deleted) {
```

2020-12-05 22:54 UTC, merged

2020-12-06 14:02 UTC, changgunyee commented on src/main/java/qna/domain/Answer.java
> +    public void setDeleted(boolean deleted) {
.... 눈이 삐었나 봅니다. private인줄 알았네요. 수정하겠습니다.