[Step1] 질문 삭제하기 기능 리팩토링
next-step/java-bowling pull request #374
Opened 2020-12-17 06:12 UTC by baek9652

안녕하세요 용대님! 리뷰이로 배정된 백성협이라고 합니다

잘 부탁 드립니다.

2020-12-17 11:58 UTC, yongdae requested changes
안녕하세요. 성협님 🙇
볼링 미션을 함께 하게된 리뷰어 권용대라고 합니다.

볼링 미션 첫 단계를 잘 진행해주셨네요. 👍 

다음 단계로 넘어가기전에 한번 더 고민해보셨으면 하는
내용이 있어 의견을 남겨 놓았습니다. 

확인 후에 다시 리뷰 요청 부탁드리겠습니다. 😄

궁금한 부분이 어려운점 있으면 슬랙을 통해 DM 주세요. (🔥_🔥)
마지막 미션인만큼  끝까지 화이팅 입니다!

2020-12-17 11:58 UTC, yongdae commented on src/main/java/qna/domain/Question.java
> +        }
유효성 검사 위치를 바꿔보면 어떨까요?

Question의 유효성을 Question에서 검증하는 것처럼
Answer가  유효성을 가지게하면 어떨까요? :)

2020-12-17 11:58 UTC, yongdae commented on src/main/java/qna/domain/Answer.java
> +    public List<DeleteHistory> delete(List<DeleteHistory> deleteHistories) {
인자를 전달받지 않고 결과를 반환 해보는 것은 어떨까요? 🤔

Answer가 삭제가 될 때 List<DeleteHistory> 라는 인자를 필요로 하게 된다면
어색해보이는 것 같아요. 일을 시켜서 결과만 받아보는 것도 좋을 것 같은데
어떻게 생각하시나요?

2020-12-17 11:58 UTC, yongdae commented on src/main/java/qna/domain/Answer.java
> +        return new DeleteHistory(ContentType.ANSWER, getId(), writer, LocalDateTime.now());
DeleteHistory 클래스에 정적 팩토리 메소드를 만들어 활용하면
더 읽기 좋은 코드가 될 것 같아요. 😄

2020-12-17 11:58 UTC, yongdae commented on src/main/java/qna/domain/Question.java
> +        deleteHistories.add(new DeleteHistory(ContentType.QUESTION, getId(), writer, LocalDateTime.now()));
여기도 위하고 동일하게 정적 팩토리 메소드를 써보면 어떨까요?

2020-12-17 11:58 UTC, yongdae commented on src/test/java/qna/domain/AnswerTest.java
>  public class AnswerTest {
Answer의 테스트를 작성해주셨네요. 👍

2020-12-17 11:58 UTC, yongdae commented on src/main/java/qna/service/QnAService.java
>          deleteHistoryService.saveAll(deleteHistories);
깔끔하게 잘 정리해주셨네요. 💯

2020-12-17 13:16 UTC, baek9652 reviewed
`delete(<DeleteHistory> deletehistories)` 관련 하여 의견 남겨두었습니다. 혹시 리뷰어님 저기에 대해서 리뷰어님 생각을 조금 들어볼 수 있을까요?

2020-12-17 13:16 UTC, baek9652 commented on src/main/java/qna/domain/Answer.java
> +    public List<DeleteHistory> delete(List<DeleteHistory> deleteHistories) {
제가 `DeleteHistory` 만 반환하는 `delete()` 메소드 이외에 추가적으로 이 메서드를 추가적으로 제공하고 싶었던 이유는 다른 사람이 `Answer` 클래스를 사용 혹은 수정하는 경우에 편의성(?)을 제공하고 싶어서 였습니다. 지금 전체 로직을 살펴보면 `List<DeleteHistory>` 는 전체 서비스 로직 안에서 언젠가 한 번은 만들어져야 되므로, 만약 기존에 만들어진 리스트가 존재한다면 안에 내용을 채우기 까지 `Answer` 가 맡아서 하면 어떨까 생각을 해봤습니다.

혹시 용대님이 추가적으로 의견 제공해주실 수 있나요?

2020-12-17 14:54 UTC, yongdae commented on src/main/java/qna/domain/Answer.java
> +    public List<DeleteHistory> delete(List<DeleteHistory> deleteHistories) {
질문하신 '외부로 노출하는 public method의 범위'는 요구사항에따라 달라진다고 생각합니다.
다르게 말하자면 문제가 제시하는 조건이나 상황에 맞추어 '외부로 노출하는 public method의 범위'가 정의되어야 한다고 생각해요.

특히 명확한 요구 조건이 없거나 재미로 하는 토이 프로젝트에서라면
상호간의 의존성을 가지지 않게 '외부로 노출하는 public method의 범위'를 설계하려고 하는 편 입니다.

어떤 형태가 되었든 "의존성"이 생긴 코드들은 결국에 남이 이해하기 어려운 코드를 야기시켜 힘들고 재미없게 만들기도 하고
지속적으로 유지 보수 되는 프로젝트에서는 일을 지루하게 만들고 생산력을 저하시킨다고 생각하기 때문입니다. 😄

추가로

"Answer 클래스를 사용 혹은 수정하는 경우에 편의성(?)을 제공하고 싶어서 였습니다. 지금 전체 로직을 살펴보면 List<DeleteHistory> 는 전체 서비스 로직 안에서 언젠가 한 번은 만들어져야 되므로"

이렇게 이야기해주신 것처럼 코드를 작성하는 조건이 있다면 상황에 맞추어서 개발이 이루어지는 맞다고 생각합니다.

"List<DeleteHistory> 는 전체 서비스 로직 안에서 언젠가 한 번은 만들어져야 되므로, 만약 기존에 만들어진 리스트가 존재한다면 안에 내용을 채우기 까지 Answer 가 맡아서 하면 어떨까 생각을 해봤습니다."

이와 고민을 하시고 적용하신 부분도 좋다고 생각합니다. 💯

2020-12-17 15:01 UTC, yongdae requested changes
빠르게 피드백을 잘 반영해주셨네요. 👍👍

추가로 한가지 더 적용해보면 좋을 것 같은 부분이 있어 의견드렸어요!!
질문에도 답변 남겨놓았습니다. 🙇

확인하시고 다시 리뷰 요청 부탁드리겠습니다. 🔥

2020-12-18 02:25 UTC, yongdae approved these changes
마지막 피드백까지 잘 반영해주셨네요!!
수고하셨습니다.

이제 본격적으로 볼링 미션을 진행해보시죠. 🔥🔥
그럼 다음 단계에서 리뷰 요청을 기다리고 있겠습니다. 😄

2020-12-18 02:25 UTC, merged