[step3] 볼링 점수판(점수 계산)
next-step/java-bowling pull request #386
Opened 2020-12-19 16:39 UTC by karian7

[이전 PR](https://github.com/next-step/java-bowling/pull/384) 의 피드백이 반영되어 있습니다. 해당 PR 에 댓글을 확인해주세요 😀 

점수계산 누적이 좀 헷갈려서 시간이 걸렸네요 😅 
그리고 `NormalFrame` 의 인스턴스 변수가 세개인데 꼭 필요한 변수들이라 두개미만으로 내리기 어렵워서 고치지 못했습니다. 😢  

잘 부탁드립니다~

2020-12-20 08:58 UTC, JunilHwang requested changes
안녕하세요 광수님! Step3 잘 구현해주셨네요 👏👏👏
몇 가지 리뷰 남겼으니 확이 후 다시 피드백 요청 부탁드립니다!

2020-12-20 08:58 UTC, JunilHwang commented on src/main/java/bowling/domain/BallThrow.java
> +        }
원시값 포장 객체의 경우 보통 valueOf를 통해서 값을 생성합니다! 그리고 인스턴스를 아무리 많이 생성해봤자 필요한 인스턴스는 최대 10개 라서 이라서 캐싱을 사용하면 더 좋을 것 같아요~

2020-12-20 08:58 UTC, JunilHwang commented on src/main/java/bowling/domain/NormalFrame.java
> +    private Frame nextFrame;
nextFrame 이라는 멤버변수가 꼭 필요할까요?

2020-12-20 08:58 UTC, JunilHwang commented on src/main/java/bowling/domain/NormalFrame.java
>      private final List<BallThrow> ballThrows = new ArrayList<>();
list가 아니여도 되지 않을까요? 어차피 많아봤자 최대 3개라서요~

2020-12-20 08:58 UTC, JunilHwang commented on src/main/java/bowling/view/GameStatus.java
> +                .collect(joining("|"));
```suggestion
        return IntStream.rangeClosed(1, 10)
                .mapToObj(game::getFrame)
                .map(frame -> frame.map(Frame::getScore))
                .map(score -> score.map(Score::toInt).orElse(null))
                .collect(accumulateScore())
                .stream()
                .map(this::toStringScore)
                .map(this::formatString)
                .collect(joining("|"));
```
이렇게 표현할 수 있습니다!

2020-12-20 08:58 UTC, JunilHwang commented on src/test/java/bowling/view/GameStatusTest.java
> +                .isEqualTo("|      |  0   |  0   |  0   |  0   |  0   |  0   |  0   |  0   |  0   |  0   |");
View 형태가 아니라 도메인으로 테스트 하면 어떨까요?

2020-12-20 08:58 UTC, JunilHwang commented on src/main/java/bowling/view/FrameStatusView.java
>      public String toString() {
이렇게 toString 내부에서 처리되는 로직은 view 객체에게 위임하고, toString은 단순하게 현재 도메인이 어떤 값을 가지고 있는지 표현하는 수단이 되어야 하는게 아닐까요?

2020-12-20 09:14 UTC, karian7 commented on src/main/java/bowling/domain/BallThrow.java
> +        }
18c9fe2e37b8ca7ffa4d4300e141967f4b9a3a28 에서 수정했습니다.

2020-12-20 09:21 UTC, karian7 commented on src/main/java/bowling/view/GameStatus.java
> +                .collect(joining("|"));
그렇게 할수도 있지만 (처음엔 그렇게 되어있었지) 의도적으로 분리했어요. 
대신 메소드 추상화 레벨을 높여 맞춰봤습니다.
a59d6e3b14e82cc9594eee02b47ec94126247fb3

2020-12-20 09:28 UTC, karian7 commented on src/test/java/bowling/view/GameStatusTest.java
> +                .isEqualTo("|      |  0   |  0   |  0   |  0   |  0   |  0   |  0   |  0   |  0   |  0   |");
도메인에 대한 테스트는 충분히 이루어 졌다고 봐요 allGutter 같은 테스트는 없지만 각 영역에 대한 단위테스트는 있어요.
다만 이곳의 테스트는 View 영역의 테스트를 도메인을 의존해서 테스트를 구동하고 있어서 통합테스트에 가까운 상태네요.

2020-12-20 09:35 UTC, karian7 commented on src/main/java/bowling/view/FrameStatusView.java
>      public String toString() {
맞아요. 적당한 이름이 당시에 떠오르지 않았어요. 적당한 이름을 찾아 붙여주었습니다. 29225cea370e2ff57113bf71ea28dc9c6ec4e918 에서 확인 가능하세요~

2020-12-20 09:40 UTC, karian7 commented on src/main/java/bowling/domain/NormalFrame.java
>      private final List<BallThrow> ballThrows = new ArrayList<>();
준일님 말씀대로 세개가 최대인건 맞는데요, 여기서 리스트를 사용않기 위한 방법으로 일급컬렉션을 사용하더라도 내부에선 결국 리스트를 써야 할 것으로 생각되어서요. 혹시 좋은 아이디어 있으실가요? 😀

2020-12-20 09:49 UTC, karian7 commented on src/main/java/bowling/domain/NormalFrame.java
> +    private Frame nextFrame;
현 구현에서는 점수 계산을 위해서 다음 프레임의 레퍼런스를 사용하고 있어요. 
다른 방법으로 클라이언트 객체가 Frame 객체에 스코어 계산을 요청하지 않고 프레임 목록을 가진 `GameService` 객체가 계산하는 방법이 있을 수 있겠어요. 다만 이 경우 다음프레임의 다음프레임을 접근하거나 그 프레임의 넘어진 핀수를 가져올 때 내부 접근이 아닌 외부 접근이 많아져서 메소드 참조의 응집도가 떨어질 수 있어요. 혹시 다른 질문 의도가 있으시다면 말씀 부탁드려요~ 😀

2020-12-20 11:07 UTC, JunilHwang commented on src/main/java/bowling/domain/NormalFrame.java
> +    private Frame nextFrame;
현재 프레임이 nextFrame에 대한 정보까지 굳이 알아야 하는건가 싶어서요! nextFrame은 현재 frame에서 만들고, 전체 프레임에 대한 표현은 Frames라는 일급 컬렉션에게 위임하면 어떨까요?

2020-12-20 11:10 UTC, JunilHwang approved these changes
안녕하세요 광수님! Step3는 여기서 마무리하겠습니다.
제가 남기는 코멘트들은 무언가 제안하는 것도 있지만 광수님의 생각이 궁금해서 코멘트 하는 것들도 있어서요 ㅎㅎ 꼭 저의 표현을 강요하는건 아니랍니다!
이제 고지가 코앞입니다. 마지막까지 화이팅!

2020-12-20 11:13 UTC, JunilHwang commented on src/main/java/bowling/domain/NormalFrame.java
>      private final List<BallThrow> ballThrows = new ArrayList<>();
음 제 생각에는 List로 표현하기보단, 각각의 Frame에 적합한 BallThrows 형태로 표현하면 어떨까 싶어서요!
- NormalBallThrows: 두 번의 throw
- FinalBallThrows: 최대 세 번의 Throw

2020-12-20 11:13 UTC, merged

2020-12-21 14:47 UTC, karian7 commented on src/main/java/bowling/domain/NormalFrame.java
> +    private Frame nextFrame;
공감합니다. 그래서 step 4 진행초기에 nextFrame 을 제거해보려 시도하였으나 위 코맨트대로 내부에 강한 의존성이 이미 만들어져 버려서 수정하긴 쉽지 않네요. 그밖에도 이번 구현에서 아쉬운 점을 정리해 봤습니다. 724bc23b61ca4abded283073323ce9077721c7a5
다시한번 볼링구현을 한다면 이부분을 고려해 보도록 하겠습니다 😎

2020-12-21 15:10 UTC, karian7 commented on src/main/java/bowling/domain/NormalFrame.java
>      private final List<BallThrow> ballThrows = new ArrayList<>();
한번의 공 던지는 행위를 BallThrows 로 추상화 했었는데 프레임당 공을 던지는 횟수를 추상화 해 볼수도 있겟네요.
https://github.com/next-step/java-bowling/pull/384 에서 언급했었지만 BallThrow 를 다형성으로 풀어볼지는 고민했었는데요, 
> BallThrow 는 의도적으로 Last 를 구현상속 구조로 바꾸지 않았습니다. 시간을 더 쓴다면 모르겠지만 현재로선 하나의 인터페이스로 만들기가 쉽지 않더군요.

이때는 공을 두번 던지는것과 세번 던지는것을 하나의 인터페이스로 풀기 어렵겠다는 판단이었었어요. 그러나 말씀주신 내용을 고려해보니 프레임에 여러개 존재하는 공위 수를 추상화 해 볼수 있고 NormalBallThrows -> BallThrow 같은 형태로 위임해볼 수 있겠네요. 반면에 `Game#throwBall` 실행시 Controller -> Game -> Frames -> Frame -> BallThrows -> BallThrow -> List or Integer 이렇게 깊어지는 런타임 의존성이 괜찮을까 하는 고민도 살짝 듭니다. FinalBallThrows 는 결국 레퍼런스 변수를 세개이상 가지거나 List를 가져야 하는 부분도 일부 한계점으로 의견드리고 싶습니다.

한편 최대 3개까지 가질 수 있는 상황에서 List 가 아니어도 되지 않나라는 의견에 대해선 3개를 넘을수도 있는 자료구조를 사용하고 있지만 이를 제약하는 로직이 있다는 점에서 괜찮지 않나 하는 생각을 했었는데요, `Frame#getBallThrows` 같이 List 가 외부로 노출되는 인터페이스를 가진 부분이 있고 클라이언트 입장에서는 이 자료구조가 두개일지 세개일지 더이상 있을지 알 수 없기 때문에 이 경우엔 일급 컬렉션으로 대체하는게 좋겠다고 생각도 했습니다.

이 부분 역시도 다음에 재구현 해본다면 시도해 보도록 하겠습니다. 13e32ae33aa7cf8c0186d6467e485cbf1e94c9fd