피드백 반영
next-step/java-bowling pull request #402
Opened 2020-12-21 14:41 UTC by changgunyee

## comment
에고... 급하게 하다보니 몇가지 실수를 했군요.
다시 반영하였습니다.
감사합니다. 🔥

2020-12-22 00:36 UTC, ohtaeg requested changes
4단계까지 구현을 잘해주셨습니다 👍 
마지막으로 몇 개의 피드백을 드렸는데, 확인해주시고 반영해주시면 감사하겠습니다!
아직 여유가 있으니 천천히 고민해보시고 리팩토링해보시면 좋을 것 같아요 :)
화이팅입니다!!

2020-12-22 00:36 UTC, ohtaeg commented on src/main/java/bowling/controller/GameController.java
> +            if (gameOfPlayer.isGameEnd())
if 문의 내부가 한 문장일 경우에도 중괄호로 둘러싸는게 컨벤션이오니
구글 자바 가이드 문서를 참고하시면 좋을 것 같아요 :)
해당 부분 외에 지켜지지 않은 곳들도 적용해주세요!

```
4.1.1 Braces are used where optional
Braces are used with if, else, for, do and while statements, even when the body is empty or contains only a single statement
```
https://google.github.io/styleguide/javaguide.html#s4.1.1-braces-always-used

2020-12-22 00:36 UTC, ohtaeg commented on src/main/java/bowling/controller/GameController.java
> +        Frame frame = null;
두개의 Frame을 하나로 줄여볼 수 있을 것 같아요 :)

추가로 가능하면 Frame을 get하지않고 gameOfPlayer에게 frame 상태를 물어보도록 리팩토링되면
객체간에 서로 대화하듯이 협력을 하는 것 처럼 변경될 수 있을 것 같아요!

2020-12-22 00:36 UTC, ohtaeg commented on src/main/java/bowling/controller/GameController.java
> +                break;
같은 피드백입니다 :)

2020-12-22 00:36 UTC, ohtaeg commented on src/main/java/bowling/domain/frame/FinalFrame.java
> +        return TOTAL_FRAME_COUNT;
피드백 반영 👍

2020-12-22 00:36 UTC, ohtaeg commented on src/test/java/bowling/domain/FinalFrameTest.java
> +class FinalFrameTest {
테스트를 잘 작성해주셨습니다 👍

2020-12-22 00:36 UTC, ohtaeg commented on src/main/java/bowling/domain/GameOfPlayer.java
> +    private final Frame firstFrame;
개인적으로 해당 firstFrame을 인스턴스 필드로 가지고 있지 않으면 좋을 것 같아요!
출력을 위해서 단순 getter만 사용되고 있으며, 출력에서도 단순 비교용으로만 사용되고 있네요 :)
한번 고민해보아요 😄

2020-12-22 00:36 UTC, ohtaeg commented on src/main/java/bowling/controller/GameController.java
> +            .collect(Collectors.toList()));
해당 로직을 Game 내부에서 수행하면 어떤 장점이 있을까요 :) ?

2020-12-22 00:39 UTC, ohtaeg commented on src/main/java/bowling/domain/frame/FinalFrame.java
>      public int getFrameCount() {
Frame의 getFrameCount 추상 메서드는 사용되지 않는 것 같아요 :)
사용되지 않는 메서드는 제거해주시면 좋을 것 같습니다 😄

2020-12-22 12:04 UTC, changgunyee commented
## comment
> 두개의 Frame을 하나로 줄여볼 수 있을 것 같아요 :)
> 
> 추가로 가능하면 Frame을 get하지않고 gameOfPlayer에게 frame 상태를 물어보도록 리팩토링되면
> 객체간에 서로 대화하듯이 협력을 하는 것 처럼 변경될 수 있을 것 같아요!

위에 있는 피드백을 제외한 나머지 피드백은 반영하였습니다. 
위에 있는 피드백은

2020-12-22 12:06 UTC, changgunyee commented
> 4단계까지 구현을 잘해주셨습니다 👍
> 마지막으로 몇 개의 피드백을 드렸는데, 확인해주시고 반영해주시면 감사하겠습니다!
> 아직 여유가 있으니 천천히 고민해보시고 리팩토링해보시면 좋을 것 같아요 :)
> 화이팅입니다!!

볼링의 난이도는 역대급인 것 같습니다.
엄청나게 힘드네요 ㅠㅠ.
그래도 해결하고나면 인생에서 몇 없는 뿌듯함을 느낄 수 있을 것 같네요.
리뷰 잘 부탁드려요. 😄

2020-12-22 15:32 UTC, changgunyee commented
+ 커밋 추가하였습니다.

2020-12-23 00:36 UTC, ohtaeg approved these changes
마지막 볼링 미션까지 모두 완주하신걸 축하드려요 🎉
8주 동안 달려오시느라 고생 많으셨습니다 🥇👏 👏

마지막까지 최선을 다하셔서 마무리 하신걸 진심으로 축하드립니다 🙇
구조가 잘 잡힌 상태에서 구현되었기에 설계 측면에서 리뷰를 크게 드리지 못했네요 😄 
피드백을 빠르게 반영해주시는데 그에 비해 리뷰가 늦은 것 같아 죄송스럽네요 🙏 


제가 드렸던 피드백들은 정답은 아니지만 창권님께 조금이나마 도움이 되었으면 좋겠습니다 :)
정말 고생많으셨습니다!! 😄
감사합니다. 🙇

2020-12-23 00:36 UTC, ohtaeg commented on src/main/java/bowling/controller/GameController.java
>      public void play() {
start 메서드와 play 메서드의 네이밍은 게임을 시작하는 기능으로 유추가 되기에
두 메서드를 하나로 합쳐도 될 것 같아요 ㅎㅎ

2020-12-23 00:36 UTC, ohtaeg commented on src/main/java/bowling/domain/Game.java
> +    public List<Frame> getCurrentFrames() {
Game 객체가 Frame을 의존하게 되었네요..!
Frame 의존이 불가피한지 고민해보시면 좋을 것 같아요 :)

2020-12-23 00:38 UTC, merged