1단계 - 질문 삭제하기 기능 리팩토링
next-step/java-bowling pull request #405
Opened 2020-12-22 15:00 UTC by sehan

안녕하세요. 볼링점수판 1단계 리뷰요청 드립니다.

답변들을 입급객체로 만들고 삭제와 상태체크를 로직을 위임, 질문/답변의 삭제로직을 entity 객체로 위임 했습니다.

리뷰 잘 부탁드립니다 😊

2020-12-22 20:47 UTC, slamdunk7575 commented
미션의 핵심은 현재 `deleteQuestion()` 내에 있는 로직들을 각각의 도메인을 이동시키는 것입니다.
그리고 List<DeleteHistory>를 Wrapping한 일급 컬렉션을 만들어 관련된 처리를 위임합니다.

결과적으로 아래와 같이 깔끔하게 리팩토링 해보면 좋을것 같아요 😄 
<img width="1014" alt="스크린샷 2020-12-23 오전 5 38 16" src="https://user-images.githubusercontent.com/15867808/102931098-12487180-44e1-11eb-8101-0f7aea38c0f4.png">

2020-12-22 21:08 UTC, slamdunk7575 requested changes
안녕하세요. 세환님😃  볼링미션 함께하게 된 양경준 입니다.

질문 삭제하기 기능 리팩토링 관련하여 좀 더 리팩토링 해보시면 
좋을 것 같아 피드백과 함께 Request Changes 드렸습니다.

미션을 이해하는데 포비가 올리신 영상을 참고해보셔도 좋을것 같아요.
https://edu.nextstep.camp/s/MNii0Puk/ls/3uCFncwZ

궁금한점이나, 어려운점 있으면 슬랙을 통하여 DM 남겨주세요. 함께 고민해보아요.🔥_🔥
건강조심하시고😷  마지막 까지 화이팅 입니다!

2020-12-23 01:58 UTC, sehan commented on src/main/java/qna/service/Answers.java
> +}
> 안녕하세요. 세환님😃 볼링미션 함께하게 된 양경준 입니다.
> 
> 질문 삭제하기 기능 리팩토링 관련하여 좀 더 리팩토링 해보시면
> 좋을 것 같아 피드백과 함께 Request Changes 드렸습니다.
> 
> 미션을 이해하는데 포비가 올리신 영상을 참고해보셔도 좋을것 같아요.
> https://edu.nextstep.camp/s/MNii0Puk/ls/3uCFncwZ
> 
> 궁금한점이나, 어려운점 있으면 슬랙을 통하여 DM 남겨주세요. 함께 고민해보아요.🔥_🔥
> 건강조심하시고😷  마지막 까지 화이팅 입니다!

영상과 요구사항을 자세히 다시 살펴보고 나서 이해했습니다.
리팩토링 진행해보겠습니다.  감사합니다. 😄

2020-12-23 10:08 UTC, slamdunk7575 approved these changes
피드백 반영 잘해주셨네요 👍 
Step1 머지하겠습니다. 몇가지 소소한 코멘트 남겨드렸으니 확인해보시면 좋을거 같아요!
궁금한점이나, 어려운점 있으면 슬랙을 통하여 DM 남겨주세요. 함께 고민해보아요.🔥_🔥
건강조심하시고 따듯한 연말 보내세요~🎄

2020-12-23 10:08 UTC, merged

2020-12-24 01:11 UTC, sehan commented on src/main/java/qna/domain/DeleteHistories.java
> +    }
네, 정말 좋은 생각입니다. 👍

2020-12-24 01:35 UTC, sehan commented on src/main/java/qna/domain/Question.java
> +        }
네, 그렇게 해도 괜찮겠네요. 👍

2020-12-24 01:52 UTC, sehan commented on src/main/java/qna/domain/Question.java
> +        deleteHistories.add(new DeleteHistory(ContentType.QUESTION, getId(), getWriter(), LocalDateTime.now()));
한결 간결해 지겠네요 👍