[step3] 볼링 점수판(점수 계산) 제출합니다.
next-step/java-bowling pull request #453
Opened 2021-04-05 14:43 UTC by loop-study

안녕하세요 박현철입니다.
이번에 진행하면서 점수 구현에 대해 많은 고민을 하다가

프레임마다 종료되면 Score 를 생성하고
투구할 때 마다 Score 에 보너스기회가 있으면 점수를 누적하는 방식으로 
최대한 단순한 방식으로 접근을 해봤습니다.

스샷은 볼링 점수 최대점수 300점이 정상적으로 찍히는 모습입니다.
![image](https://user-images.githubusercontent.com/19161176/113586335-56164f80-9668-11eb-9c4d-c70731a1f6af.png)

확인 후 피드백 부탁드리겠습니다
감사합니다!

2021-04-06 09:39 UTC, wheejuni requested changes
구조는 워낙 튼튼히 잘 잡아주셔서 크게 피드백드릴 부분이 없습니다. 👍 💯 
남겨드린 피드백도 코어 구조에 관한 부분이라기보단 코드상의 표현에 관한 부분들입니다.
다만 고심끝에(?) 당부드리고 싶은 부분이 있어 조심스레 개선 제안해 드리고자 합니다. 

**프로젝트에 작성된 모든 메소드들의 이름을, 아래의 원칙에 입각해서 다시 고민해주세요.**

_원칙_
- 동사형 표현을 원칙으로 한다. 
- 클래스명과 같거나, 클래스명을 포함하는 메소드명의 사용은 가급적 삼간다.
- 메소드를 사용하는 측에서 다시 고민해 본다. `특정 상황에서 어떤 메소드명이 가장 먼저 떠오를지` 를 고민한다. 

다소 난감한 과제일 수도 있겠지만, 지금 전반적으로 메소드의 이름이 코드 전체의 가독성에 큰 악영향을 미치고 있어 제안드리게 되었습니다.
어려우시면 같이 고민해 봐요. 피드백 반영 기다리겠습니다. 🥇

2021-04-06 09:39 UTC, wheejuni commented on src/main/java/bowling/domain/BonusChance.java
> +        validMinBonusChance(bonusChance);
이 로직은 생성자보단 `.of()` 에 위치하는 것이 조금 더 나을 것 같습니다.

2021-04-06 09:39 UTC, wheejuni commented on src/main/java/bowling/domain/BonusChance.java
> +        return new BonusChance(bonusChance-1);
연산자 양 옆에는 한칸씩 띄어주세요.

```suggestion
        return new BonusChance(bonusChance - 1);

2021-04-06 09:39 UTC, wheejuni commented on src/main/java/bowling/domain/Frame.java
> +    }
`Score` 라는 래핑 클래스가 있는 것 같던데요,
여기선 사용하지 않으시는 이유가 궁금합니다.

2021-04-06 09:39 UTC, wheejuni commented on src/main/java/bowling/domain/Frame.java
> +    public int bonusChance() {
여기두요. `BonusChance` 가 왜 여기선 사용되지 않는지요?

2021-04-06 09:39 UTC, wheejuni commented on src/main/java/bowling/domain/FrameScore.java
> +        return score.score();
메소드명이 조금 어색하네요. `Score` 측에서 메소드 이름을 바꿔줘야 할 듯 합니다.
더 좋은 이름이 없을까요?

2021-04-06 09:39 UTC, wheejuni commented on src/main/java/bowling/view/ResultView.java
> +    private String stringToScore(int size, List<FrameScore> scores) {
메소드명때문에 순간 혼동했네요. `scoreToString` 이 맞는 방향 아닐까요.

2021-04-06 11:04 UTC, loop-study commented on src/main/java/bowling/view/ResultView.java
> +    private String stringToScore(int size, List<FrameScore> scores) {
혼동드려 죄송합니다 😂😂😂😂

2021-04-06 11:11 UTC, loop-study commented on src/main/java/bowling/domain/BonusChance.java
> +        return new BonusChance(bonusChance-1);
감사합니다!🙈

2021-04-06 11:12 UTC, loop-study commented on src/main/java/bowling/domain/Frame.java
> +    }
헛.... 값을 가져와서 만들어야겠다는 생각에 이런 걸 못보고 있었네요!🙈🙈
이름만 봐도 int 보다는 객체를 보내주는게 더 파악하기 좋겠습니다!👍👍
감사합니다!😂😂

2021-04-06 11:22 UTC, loop-study commented on src/main/java/bowling/domain/FrameScore.java
> +        return score.score();
aggregateScore 로 변경하겠습니다!🙈

2021-04-06 11:39 UTC, loop-study commented
안녕하세요 박현철입니다.
알려주신 피드백 덕분에 가독성과 문맥 흐름이 더 개선 되었습니다!

개인적으로 이름짓기가 설계보다 힘든거 같습니다.
영어 공부의 중요성을 다시 한번 깨닫고 갑니다.
감사합니다! 👍👍👍👍

2021-04-07 00:38 UTC, wheejuni approved these changes
쉽지 않은 고민이셨을텐데 잘 반영해주셔서 감사합니다. 👍

2021-04-07 00:38 UTC, merged