[Step4] 코드리뷰 요청드립니다.
next-step/java-bowling pull request #456
Opened 2021-04-07 10:09 UTC by jeonyeonbin

2021-04-08 11:47 UTC, vagabond95 requested changes
큰 수정사항없이 구현해주셨네요 👍 👍 

가독성과 관련하여 간단한 코멘트 남겼는데요, 확인 후 다시 리뷰요청 부탁드릴게요!
마지막 단계인 만큼 화이팅이십니다!

2021-04-08 11:47 UTC, vagabond95 commented on src/main/java/bowling/controller/BowlingGameController.java
> +	private Function<InputView, BiFunction<Integer, Players, Consumer<Player>>> playerRunFunc = (inputView) -> (turn, players) -> (player) -> {
중첩된 function 은 너무 가독성이 떨어지는 것 같아요 😢 
개별 메소드로 분리하여 구현해보는 것은 어떨까요?

2021-04-08 11:47 UTC, vagabond95 commented on src/main/java/bowling/entity/Players.java
> +		return players;
불변 컬렉션으로 리턴해주면 좋을 것 같습니다 :)

2021-04-08 11:47 UTC, vagabond95 commented on src/main/java/bowling/entity/Player.java
> +	public boolean isEnd() {
end, keepGoing 하는 기준이 Frame 인지, Game 그 자체인지 헷갈릴 수 있을 것 같아요.

Frame 을 기준으로 보더라도 frameIndex 가 11 미만인것은 end 로 보기 어렵지 않을까요?

2021-04-08 12:08 UTC, jeonyeonbin commented on src/main/java/bowling/controller/BowlingGameController.java
> +	private Function<InputView, BiFunction<Integer, Players, Consumer<Player>>> playerRunFunc = (inputView) -> (turn, players) -> (player) -> {
java에서의 커링은 typing하기는 조금 불편하긴 하더라구요 ... 그래서 고민하다가 일단 커링으로 작업하려고햇는데 한번 고민해보겠습니다

2021-04-08 12:58 UTC, jeonyeonbin commented on src/main/java/bowling/entity/Player.java
> +	public boolean isEnd() {
넵 메소드명이 너무 추상적이고 해당클래스에서 어떤게 끝나는지 어떤게 진행되는지 잘안보이네요 ㅠ

2021-04-08 13:06 UTC, jeonyeonbin commented
> 큰 수정사항없이 구현해주셨네요 👍 👍
> 
> 가독성과 관련하여 간단한 코멘트 남겼는데요, 확인 후 다시 리뷰요청 부탁드릴게요!
> 마지막 단계인 만큼 화이팅이십니다!

@vagabond95 
네 마지막미션이네요 ㅎㅎㅎ
멘토님도 리뷰하느라 고생많으셨습니다

피드백 반영하여서 진행완료하였습니다 확인요청드립니다 😄

2021-04-09 23:33 UTC, vagabond95 approved these changes
리뷰 확인이 늦어져 죄송합니다 😢 

피드백 잘 반영해주셨네요! 이전단계들에서 구조적으로 잘 잡아주셔서 크게 코멘트 드릴 부분이 없었던 단계였습니다. ㅎㅎ
굉장히 빠른 속도로 볼링미션까지 잘 마무리 해주셨는데요! Next step 과정 중 얻어가는 것이 있었던 미션이셨다면 좋겠습니다! 미션들 진행하시느라 고생 많으셨습니다.
미션이 끝난 후에도 관련하여 궁금하거나 논의하고싶은 점 있으시면 편하게 DM 주세요!

2021-04-09 23:33 UTC, merged