볼링 미션 - Step2
next-step/java-bowling pull request #458
Opened 2021-04-11 08:58 UTC by jhLim97

준일님, 안녕하세요!

이번 미션은 pr하기까지 많은 시간이 소요된 것 같습니다.
기능 구현 자체는 어렵지 않았지만, 클린코드와 리팩토링 측면에서 많은 고민이 생겨서 여러 번 갈아 엎은 것 같습니다.

아직 부족한 모습이 보이지만, 이쯤에서 피드백을 받아보고 싶어서 pr 드립니다.

리뷰해주시느라 고생 많으시고, 감사드립니다!!

2021-04-11 11:00 UTC, JunilHwang requested changes
안녕하세요 준혁님! 볼링 미션 잘 작성해주셨네요 👍
현재 `객체지향 생활체조`에 위배되는 코드도 있고, 한 메소드가 너무 긴 부분도 있습니다.
이러한 부분들을 개선해보면 좋을 것 같습니다.
저도 전체 미션을 통틀어서 볼링 미션 Step2가 제일 어려웠는데 초반에 Step2만 잘 설계하면 볼링미션도 빠르게 완수할 수 있을 것 같아요! 조금 더 힘내봅시다 😁

2021-04-11 11:00 UTC, JunilHwang commented on src/main/java/bowling/controller/BowlingController.java
> +    private final ResultView resultView;
상수와 멤버변수는 개행으로 구분해주면 좋을 것 같습니다!

2021-04-11 11:00 UTC, JunilHwang commented on src/main/java/bowling/controller/BowlingController.java
> +        }
for과 if가 중첩되었네요. 객체지향 생활체조 원칙에 맞게 작성해주세요!

2021-04-11 11:00 UTC, JunilHwang commented on src/main/java/bowling/controller/BowlingController.java
> +    }
한 메서드가 너무 길어요! 가능하면 10줄 이내로, 최대 15줄로 작성해보면 어떨까요?

2021-04-11 11:00 UTC, JunilHwang commented on src/main/java/bowling/view/ResultView.java
> +        }
if문 없이 작성해보도록 설계해보면 어떨까요?

2021-04-11 11:00 UTC, JunilHwang commented on src/main/java/bowling/domain/Frame.java
> +    }
state라는 이름을 메소드로 사용하기에는 조금 어색한 것 같습니다.

2021-04-11 11:00 UTC, JunilHwang commented on src/main/java/bowling/domain/Frame.java
> +abstract class Frame implements FrameStrategy {
LinkedList 형태로 만들어보면 어떨까요?

2021-04-22 15:00 UTC, jhLim97 commented on src/main/java/bowling/controller/BowlingController.java
> +    private final ResultView resultView;
반영했습니다!

2021-04-22 15:01 UTC, jhLim97 commented on src/main/java/bowling/controller/BowlingController.java
> +        }
기본적인 요구사항을 빠트렸네요.. 반영했습니다!

2021-04-22 15:01 UTC, jhLim97 commented on src/main/java/bowling/controller/BowlingController.java
> +    }
네 반영했습니다.

2021-04-22 15:01 UTC, jhLim97 commented on src/main/java/bowling/view/ResultView.java
> +        }
enum 클래스로 추출하여 if문 없이 구현해 보았습니다!

2021-04-22 15:02 UTC, jhLim97 commented on src/main/java/bowling/domain/Frame.java
> +    }
메서드명을 result로 변경해 보았습니다. 메서드명을 짓는게 어렵네요..ㅠ

2021-04-22 15:03 UTC, jhLim97 commented on src/main/java/bowling/domain/Frame.java
> +abstract class Frame implements FrameStrategy {
Frame 클래스에 단일 연결리스트의 구조인 next라는 인스턴스 객체를 생성하여 구현해보았습니다!

2021-04-22 15:04 UTC, jhLim97 commented
안녕하세요, 준일님! 

개인적인 사정으로 오랜만에 pr 드립니다.
부족한 부분은 피드백 주시면 다시 반영하도록 하겠습니다!!

2021-04-23 08:49 UTC, JunilHwang approved these changes
안녕하세요 준혁님! 피드백 반영 잘 해주셨네요 👍 
Step2는 여기서 마무리 하겠습니다. 바로 Step3 진행해주세요!

2021-04-23 08:49 UTC, JunilHwang commented on src/main/java/bowling/view/ResultByPlayNumber.java
> +    };
인상적이네요 👍

2021-04-23 08:49 UTC, merged