[볼링 점수판 - 1단계] 코드 리뷰 요청드립니다
next-step/java-bowling pull request #471
Opened 2021-04-17 11:56 UTC by cocahack

안녕하세요, 리뷰어님. 1단계 리팩토링 완료되어 PR 올립니다.

미션의 힌트를 활용해서 Answers 일급 컬렉션을 사용하고, 삭제 시 Validation 확인은 각자가 알아서 하도록 책임을 분리했습니다.  

그리고 기존 코드는 삭제할 때 내부 상태를 바꾸고 자기 자신을 리턴하는데, 이것을 새로운 객체를 반환하는 방법으로 변경했습니다.  
기존 테스트 코드들을 보면 상수로 테스트 데이터를 정의하니, 이것을 그대로 사용하려면 이 방법이 낫다고 생각했습니다.

제가 실제 업무에서 JPA를 사용하고 있지 않아서 잘못된 부분이 있는지 잘 모르겠습니다. 혹시 있다면 이 부분도 같이 피드백 부탁드리겠습니다. 

그럼 잘 부탁드립니다! 🙇‍♂️

2021-04-17 16:59 UTC, slamdunk7575 requested changes
안녕하세요😄  명철님.
볼링 미션 함께하게 된 양경준 입니다.

JPA에 대한 경험이 없다고 하셨지만 아주 잘 구현해주셨네요 👍
조금 더 깔끔하게 리팩토링 해볼 수 있을거 같아 피드백 남겨드렸습니다!

궁금한점이나 어려운점 있으면 슬랙으로 DM 남겨주세요. 함께 고민해보아요 🔥_🔥
끝까지 화이팅 입니다!

2021-04-17 16:59 UTC, slamdunk7575 commented on src/main/java/qna/domain/Question.java
> +    }
`List<DeleteHistory>`를 `일급 컬렉션`으로 만들어보면 어떨까요?

2021-04-17 16:59 UTC, slamdunk7575 commented on src/main/java/qna/domain/Question.java
> +        return new DeleteHistory(ContentType.QUESTION, getId(), this.writer, LocalDateTime.now());
`DeleteHistory` 내에 아래와 같은 `정적 팩토리 메소드`를 만들어보면
인자수도 줄면서 코드의 가독성을 높여줄수 있겠네요 😄 

```
    public static DeleteHistory ofQuestion(Long contentId, User deletedBy) {
        return new DeleteHistory(ContentType.QUESTION, contentId, deletedBy);
    }

    public static DeleteHistory ofAnswer(Long contentId, User deletedBy) {
        return new DeleteHistory(ContentType.ANSWER, contentId, deletedBy);
    }
```

2021-04-17 16:59 UTC, slamdunk7575 commented on src/main/java/qna/domain/Answers.java
> +public class Answers {
`Answers` 분리 잘해주셨네요 👍

2021-04-17 16:59 UTC, slamdunk7575 commented on src/main/java/qna/domain/Question.java
> +    }
이부분에서 `DeleteHistories` 리턴하도록 하여 `Question`과 `Answer`는 상태가 바뀌고 
`Service`에서 아래처럼 `DeleteHistory`를 저장하도록 해보면 좋을것 같아요 😄 
(참고로 JPA에서 Entity의 상태가 변경되면 감지하여 쿼리가 실행됩니다)

![스크린샷 2021-04-18 오전 1 31 22](https://user-images.githubusercontent.com/15867808/115120185-0714d680-9fe7-11eb-8f85-d0942dc547e9.png)

도움을 조금 드리면, 아래와 같이 변경해볼 수 있겠네요!

```
    public DeleteHistories beDeletedBy(User owner) {
        checkIfQuestionIsOwnedBy(owner);
        
        this.deleted = true;
        Answers answers = this.answers.beDeletedBy(owner);

        DeleteHistories deleteHistories = makeDeleteHistoryOfQuestion();
        deleteHistories.addHistories(answers.createDeleteHistories());

        return deleteHistories;
    }
```

2021-04-17 17:14 UTC, slamdunk7575 commented on src/main/java/qna/domain/Question.java
> +    private Answers answers = new Answers();
```suggestion
    @Embedded
    private Answers answers;
```

`생성자`에서 초기화 하는것이 좋겠지만 
현재는 `Answer`를 사용하는 아래에서 초기화 해줘도 좋겠네요 😄 

```
public void addAnswer(Answer answer) {
        this.answers = new Answers();
        answer.toQuestion(this);
        answers.add(answer);

```}

2021-04-18 06:08 UTC, cocahack commented on src/main/java/qna/domain/Question.java
> +    }
`DeleteHistory` 의 리스트는 지금까지 요구사항으로 봤을 때, 데이터베이스에 저장되기만 하면 되고 별 다른 기능은 없는 것으로 보입니다. 그래서 기능이 있지않다면 지금처럼 리스트의 기능만 사용해도 좋지 않을까 생각합니다.  

리뷰어님은 어떻게 생각하시나요?

2021-04-18 12:45 UTC, slamdunk7575 approved these changes
피드백 반영 잘 해주셨네요 👍 고생하셨습니다!
다음 단계 진행을 위해 머지할게요.
앞으로 미션도 화이팅 입니다~! 💪

2021-04-18 12:45 UTC, slamdunk7575 commented on src/main/java/qna/domain/Question.java
> +    }
피드백 반영 잘해주셨네요 👍

2021-04-18 12:45 UTC, slamdunk7575 commented on src/main/java/qna/domain/DeleteHistory.java
> +    }
👍

2021-04-18 12:47 UTC, merged