[1단계 - 질문 삭제하기 기능 리팩토링] 리뷰 요청드립니다!
next-step/java-bowling pull request #473
Opened 2021-04-17 16:49 UTC by seongbeenkim

안녕하세요 유라님!
리팩토링을 진행하면서 미션의 힌트와 온라인 강의를 참고하여 서비스 로직을 각 도메인에게 최대한 위임하려고 노력을 하였던 것 같습니다!

__1단계를 하면서 느낀점__

1. JPA에 대해서 살짝 공부만 해본 상태였는데 이번 리팩토링을 통해서 `@Embedded`와 `@Embeddable`에 대해서 더 공부해볼 수 있었던 것 같습니다! 또한, 기존의 미션처럼 처음부터 도메인을 설계하고 TDD로 구현하는 것이 아닌 기존의 서비스의 비즈니스 로직을 도메인으로 TDD를  하며 위임함으로써, 조금이나마 레거시 코드를 어떻게 리팩토링을 해야하는 지 느끼게 된 것 같습니다!

2. [`Arrays.asList`로 생성한 리스트는 고정된 리스트`new ArrayList<>(a)`를 반환하는데 `java.util.ArrayList`가 아닌 `java.util.Arrays.ArrayList`를 반환해 원소를 제거 또는 추가 할 수 없어 이와 같은 연산을 수행할 경우`UnsupportedOperationException` 런타임 예외가 발생한다는 것도 알게되었고 이를 해결하기 위해서 `new ArrayList()`로 한번 더 감싸주어 이와 같은 연산을 할 수 있게 해줄 수 있다](https://stackoverflow.com/questions/43020075/java-util-arrays-aslist-when-used-with-removeif-throws-unsupportedoperationexcep)는 것을 배울 수 있었던 것 같습니다!

앞으로 볼링 미션 잘 부탁드립니다!!
잘못된 부분이나 더 개선하면 좋겠는 부분들 피드백 주시면 공부해서 반영하도록 하겠습니다!! :)

2021-04-18 11:43 UTC, dbeod2 requested changes
안녕하세요! 
볼링 미션 리뷰를 맡게 된 원유라입니다. 

첫번째 미션 잘 진행해주신 것 같아요! 👏🏻👏🏻👏🏻
고민해보면 좋을 것 같은 부분 코멘트 남겨두었습니다. 🙏🏼
확인부탁드립니다 🙇‍♀️

2021-04-18 11:43 UTC, dbeod2 commented on src/main/java/qna/service/QnAService.java
> +        List<DeleteHistory> deleteHistories = question.delete(loginUser);
리팩토링 잘 진행해주신 것 같네용! 
다만 의견을 드리자면! 아래와 같이 설계해보시는건 어떠실지 의견드려봅니다! 
로직을 도메인에 위임하고 서비스는 조합만 하는 형태면 좋을 것 같다고 생각이 드네요 :)

2021-04-18 11:43 UTC, dbeod2 commented on src/test/java/qna/domain/AnswersTest.java
> +        //given
테스트 잘 작성해주셨네요 :) 

정말 답변이 삭제가 되었는지 검증하는 부분이 없네요 ㅠ.ㅠ 
한가지 의견을 드리자면 답변 여부를 도메인에서 체크해보는건 어떨까요?

2021-04-18 15:12 UTC, seongbeenkim commented on src/test/java/qna/domain/AnswersTest.java
> +        //given
저는 답변 삭제 이력이 삭제가 완료되야지만 반환이 되기 때문에 삭제가 되었다는 검증을 하고 있다고 생각을 했었던 것 같습니다.
하지만, 말씀하신 대로 답변 삭제가 되었는 지에 대한 명확한 검증 부분을 추가하는 것이 더 좋을 것 같네요!
`isDelete()` test 코드 작성하여 답변 삭제 후 삭제 여부 값을 통해 답변이 삭제되었는 지에 대한 검증하는 부분 추가하였습니다 :)

2021-04-18 15:52 UTC, seongbeenkim commented on src/main/java/qna/service/QnAService.java
> +        List<DeleteHistory> deleteHistories = question.delete(loginUser);
늦은 시간에 질문드렸는데 답변해주셔서 감사합니다!
해당 부분 옮기긴 했는데 맡게 한건지 한번 봐주시면 감사하겠습니다!

2021-04-19 04:30 UTC, dbeod2 commented on src/main/java/qna/service/QnAService.java
> +        List<DeleteHistory> deleteHistories = question.delete(loginUser);
피드백 제대로 반영해주셨습니다! 👍 👍

2021-04-19 04:30 UTC, dbeod2 approved these changes
빠르게 피드백 반영해주셨네요! 👍 

다른 이견 없어서 첫번째 미션 여기서 머지하겠습니다. 🙇🏻‍♀️
본격적으로 볼링 미션 진행해주세용!! 🎳🎳🎳

2021-04-19 04:30 UTC, merged