[볼링점수판 - Step1] 리뷰요청 드립니다!
next-step/java-bowling pull request #479
Opened 2021-04-19 14:08 UTC by juniqlim

용대님, 안녕하세요!
코드리뷰 요청드립니다. 미션의 의도대로 코드를 작성한 것인지 잘 모르겠습니다;;
이번 미션동안 열심히 배우겠습니다. 🙇🏻

2021-04-20 07:22 UTC, yongdae requested changes
안녕하세요. 준규님 😄 

볼링 미션을 함께하게된 리뷰어 권용대라고 합니다~
마지막 미션을 함께 할 수 있게되어 기쁩니다. :)

1단계 리팩토링 미션을 잘 진행해주셨네요. 👍
개선하면 좋을 부분이 있어 몇 가지 의견 드렸습니다~

확인하시고 다시 리뷰 요청 부탁드려요. 🙇

최종 미션인 만큼 끝까지 힘내주세요. 🔥🔥
그리고 언제든 의견이나 고민있으시면 DM 주세요!!

2021-04-20 07:22 UTC, yongdae commented on src/test/java/qna/domain/QuestionTest.java
> +    }
요구사항에 맞추어 테스트를 잘 만들어주셨네요. 👍

2021-04-20 07:22 UTC, yongdae commented on src/test/java/qna/domain/QuestionTest.java
> +        assertThatCode(() -> question.delete(UserTest.JAVAJIGI)).doesNotThrowAnyException();
then 조건으로 isDeleted도 사용해보면 좋을 것 같아요~

2021-04-20 07:22 UTC, yongdae commented on src/test/java/qna/domain/AnswerTest.java
> +    }
Answer에 대한 테스트도 잘 만들어주셨네요. 👍

2021-04-20 07:22 UTC, yongdae commented on src/test/java/qna/domain/AnswerTest.java
> +        assertThatCode(() -> A1.delete(UserTest.JAVAJIGI)).doesNotThrowAnyException();
이 부분도 isDelete를 사용해보면 어떨까요?

2021-04-20 07:22 UTC, yongdae commented on src/main/java/qna/domain/Question.java
> +    public void delete(User loginUser) throws CannotDeleteException {
void 대신 List<DeleteHistory> 를 반환해보면 좋을 것 같아요. :)

2021-04-20 07:22 UTC, yongdae commented on src/main/java/qna/domain/Answer.java
> +    }
DeleteHistory 객체에 [정적 팩토리 메소드](https://velog.io/@ljinsk3/%EC%A0%95%EC%A0%81-%ED%8C%A9%ED%86%A0%EB%A6%AC-%EB%A9%94%EC%84%9C%EB%93%9C%EB%8A%94-%EC%99%9C-%EC%82%AC%EC%9A%A9%ED%95%A0%EA%B9%8C)를 적용해보면 좋을 것 같아요!

2021-04-20 08:47 UTC, juniqlim commented on src/main/java/qna/domain/Question.java
> +    public void delete(User loginUser) throws CannotDeleteException {
List로 answer 의 id를 반환하면 좋을까요?

2021-04-20 09:14 UTC, yongdae commented on src/main/java/qna/domain/Question.java
> +    public void delete(User loginUser) throws CannotDeleteException {
QnA 서비스에서 어떻게 사용하는지를 생각해보시면 될 것 같아요!

2021-04-20 15:39 UTC, yongdae requested changes
안녕하세요. 준규님 :)

이전 피드백을 잘 반영해주셨네요. 👍 
진행해주신 부분에대해 추가로 몇 가지 의견드렸습니다.

확인하시고 다시 리뷰 요청 부탁드리겠습니다. 😄

2021-04-20 15:39 UTC, yongdae commented on src/main/java/qna/domain/DeleteHistory.java
> +    }
정적 팩토리 메소드를 잘 적용해주셨네요. 👍

2021-04-20 15:39 UTC, yongdae commented on src/main/java/qna/domain/Question.java
> +        return deleteHistorys;
```suggestion
        List<DeleteHistory> deleteHistories = new ArrayList<>();

        deleteHistories.add(deleteQuestion(loginUser));
        deleteHistories.addAll(answers.delete(loginUser));

        return deleteHistories;
```

이런 형태로 코드가 동작 할 수 있게 해보면 좋을 것 같아요. :)

2021-04-20 15:39 UTC, yongdae commented on src/main/java/qna/domain/DeleteHistory.java
> +
public static DeleteHistory ofQuestion(Long contentId, User deletedBy, LocalDateTime createDate) {
        return of(ContentType.QUESTION, contentId, deletedBy, createDate);
    }

    public static DeleteHistory ofAnswer(Long contentId, User deletedBy, LocalDateTime createDate) {
        return of(ContentType.ANSWER, contentId, deletedBy, createDate);
    }

정적 팩토리 메소드를 활용해보면 이렇게 해볼 수도 있을 것 같아요. 😄

2021-04-22 13:21 UTC, juniqlim commented
안녕하세요, 용대님! 
피드백 주신 것을 반영하니 코드가 더 깔끔해졌습니다. 👍
다시 리뷰 부탁드립니다!

2021-04-22 14:03 UTC, yongdae approved these changes
안녕하세요 ~ 준규님 :)

이전 피드백을 잘 반영해주셨네요!
이제는 별 다르게 의견을 드릴 부분이 없을 것 같아요. 😄

수고하셨습니다!!

그럼 본격적으로 볼링미션을 시작하러 가보시죠! 🙇

2021-04-22 14:04 UTC, merged