Step4
next-step/java-bowling pull request #483
Opened 2021-04-21 10:05 UTC by meme2367

이전 피드백 반영하고 코드 수정했습니다..!

피드백 반영 부분
1. FinalFrame의 State들을 모아 문자열을 만드는 행위는 View의 역할이므로 View에게 책임 전가하기 : ResultView에서 NormalFrame인지 FinalFrame인지에 따라 State를 출력하도록 했습니다.
 
2. 의존성 주입하지 말고 가운데 정렬 구현하기 : ResultView의 

3. Pin에서 gutter를 처리하면 안된다 : SecondGutter와 FirstGutter로 나뉘어  Gutter를 처리했습니다. 그런데 그 외 예외의 상황이 있어서 그런 부분은 if문 처리했습니다.(ex) 0번을 치고 3번을 쳤을 때 miss로 넘어가버리지만 -|3이 출력되도록 함)

4. FinalFrame은 calculateScore를 수행하지 않음에도 오버라이드 한 문제 : Frame을 추상클래스로 만들어서 해결했습니다. 맞는 방법인지 모르겠으나 의견을 듣고 싶어 이렇게 해봤습니다..!

5. 4번째 과제 부분은 BowlingGames 클래스를 만들어서 수행했습니다.

6.play를 할 때는 int형 pinCount를 넘기지 말고 Pin 형 으로 넘기도록 수정.

리뷰 감사합니다..!

2021-04-21 14:21 UTC, ohtaeg requested changes
마지막 4단계 볼링 미션도 구현을 잘해주셨습니다 👍 
마음 같아선 바로 클린 코드 강의를 수료시켜드리고 싶지만
사소하지만 설계적으로 좀 더 리팩토링해볼만한 부분이 존재하기에 Request changes 하였습니다 :)
여유를 가지시고 한번 더 고민해보시면 좋을 것 같아요!
마지막 한걸음 화이팅입니다!!

2021-04-21 14:21 UTC, ohtaeg commented on src/main/java/bowling/domain/frame/Frame.java
> +  }
> FinalFrame은 calculateScore를 수행하지 않음에도 오버라이드 한 문제 : Frame을 추상클래스로 만들어서 해결했습니다. 맞는 방법인지 모르겠으나 의견을 듣고 싶어 이렇게 해봤습니다..!

개인적으로는 이전 코드와 큰 차이는 없어서 조금 아쉬운 부분이라고 생각이 됩니다.
이전에는 재정의가 되어 있지않았더라면 이번엔 부모에 빈 구현체로 선언되어 있네요 😭 
그리고 어떤 구현체는 재정의하고 어떤 구현체는 재정의하지 않는 부분이 더 헷갈릴 것 같아요 :)

점수 계산 방식을 한번 같이 고민해보면 좋을 것 같아요! Frame 구현체들이 각각 자신의 State를 알고, Score를 아는데
Pin을 꼭 파라미터로 받아야 할 필요가 있을까요~? Frame이 가지고 있는 State를 활용해서 점수를 누적시켜보도록
해보면 어떨까요 :) ?

2021-04-21 14:21 UTC, ohtaeg commented on src/main/java/bowling/domain/state/FirstGutter.java
> +public class FirstGutter implements State {
거터를 두개로 분리 👍

2021-04-21 14:21 UTC, ohtaeg commented on src/main/java/bowling/domain/state/Miss.java
> +  }
State라는 인터페이스는 일종의 계약서라고 볼 수 있습니다. 
인터페이스라는 계약서는 구현체들이 계약에 따라 동작하도록 해주는 것인데요!
계약서를 작성할 때 일부 특정 객체만 별도로 동작하도록 차별하거나 예상해서는 안된다고 생각합니다..!
즉, 특정 상태값인지 아닌지 물어보는 오퍼레이션은 일부 목적을 위해 거터 미스등 구현체들을 차별하는 오퍼레이션 같아요 :)
isStrikeOrSpare() 메서드를 재정의하지 않도록 State 구조를 고민해보시면 좋을 것 같습니다!

2021-04-21 14:21 UTC, ohtaeg commented on src/main/java/bowling/view/ResultView.java
> +      sb.append(pad);
util을 제거하고 ResultView에 직접 구현 👍

2021-04-26 09:35 UTC, meme2367 commented
안녕하세요 태경 리뷰어님!

 4단계 과제를 다시 만들어보았습니다! bowling_step4라는 패키지에 다시 코드를 작성했어요ㅎㅎ

이전 리뷰에서 "Frame이 가지고 있는 State를 활용해서 점수를 누적시켜보는 것이 어떠냐"는 의견이 있었는데요!

또, 이와 관련해서 슬랙에서 태경님이 제게  State에 대한 일급컬렉션을 만들어보라는 힌트도 주셨습니다!

그런데 제가 과제 힌트를 보고 생각한 결과 각 프레임은 이미 State를 가지고 있으니 State에 Score를 기록하면 되지 않을까?라는 아이디어를 가지고 다시 코드를 짰습니다ㅎㅎ..

NormalFrame은 기존과 비슷하지만, nextFrame 변수를 가지도록 하여 다음 프레임의 정보를 활용할 수 있게 했습니다.

또한 Null처리때문에 점수 계산이 힘들어서  계산에 사용되지 않거나, 아직 계산에 사용할 수 없는 투구의 경우에는 Score의 undefined라는 객체를 따로 둬서 이 경우는 계산에 제외했습니다.

그리고 점수결과는 Scores라는 클래스에 누적됩니다..!

이번 과제를 하는 데 몇번이나 틀이 달라지는 것을 보고 제가 아직 한참 멀었다는 생각이 드네요ㅠㅠ..

한 일주일 간 너무 막막했는데 태경님 DM덕분에 다시 아이디어가 떠오르고 덕분에 힘받아서 다시 열심히 했네요 

감사합니다!!

2021-04-26 14:38 UTC, ohtaeg approved these changes
마지막 피드백 반영을 잘해주셨어요 👍 
마지막 미션은 이만 마무리해도 좋을 것 같아 마무리하겠습니다 👍

볼링 미션 완주 및 클린 코드 미션 수료를 축하드립니다 🎉
다연님께서 수료 못할까봐 노심초사 하셨었는데 수료하셔서 다행입니다!! (믿고있었다구..!)
제가 드린 피드백들이 다연님께 조금이나마 도움이 되었으면 하는 바램입니다 :)

다시 한번 완주를 축하드리며, 많은 피드백을 반영하시느라 고생 많으셨어요! 🎉
이만 merge 하겠습니다 🥇

2021-04-26 14:38 UTC, ohtaeg commented on src/main/java/bowling/domain/Pin.java
> +    return this.count + fallenPins.getCount() == MAX_PIN_COUNT;
자기 자신이기에 getter말고 바로 접근하시면 좋을 것 같아요 :)
```suggestion
    return this.count + fallenPins.count == MAX_PIN_COUNT;
```

2021-04-26 14:38 UTC, ohtaeg commented on src/main/java/bowling/domain/Pin.java
> +  }
가독성 좋게 isSpare() 근처에 위치하면 좋을 것 같아요 ㅎㅎ

2021-04-26 14:38 UTC, ohtaeg commented on src/main/java/bowling/domain/frame/FinalFrame.java
> +  }
구현이 비워져있는 부분이 아쉽네요 😭

2021-04-26 14:38 UTC, ohtaeg commented on src/main/java/bowling/domain/state/FirstGutter.java
> +    return "-";
사소하지만 매직넘버나 문자열을 상수로 관리하면 좋을 것 같아요 :)

2021-04-26 14:39 UTC, merged