Step1 리뷰 요청 드립니다.
next-step/java-bowling pull request #493
Opened 2021-04-24 06:35 UTC by ttokey

안녕하세요 리뷰어님?
step1 리뷰요청 드립니다.

2021-04-25 06:00 UTC, JunilHwang requested changes
안녕하세요 석희님! 볼링미션을 함께하게된 리뷰어 황준일입니다 🙇‍♂️
앞으로 잘 부탁드려요!

QNA 리팩토링 잘 진행해주셨네요.
다만 도메인에서 일급컬렉션으로 만들 수 있는 부분은 일급컬렉션으로 만들어보는게 어떨까요?
불필요해보이더라도 한 번 사용해보시는 권유합니다!

2021-04-25 23:29 UTC, JunilHwang approved these changes
안녕하세요 석희님! 피드백 반영 잘 해주셨네요 👍 
이제 본격적으로 볼링 미션 진행해봅시다! 화이팅 💪

2021-04-25 23:29 UTC, JunilHwang commented on src/main/java/qna/domain/Question.java
> +        deleteHistories.addAll(answers.deleteAnswers(user));
DeleteHistories를 만들 때 이 부분도 넘겨줄 수 있지 않을까요?

2021-04-25 23:29 UTC, merged

2021-04-26 01:42 UTC, ttokey commented on src/main/java/qna/domain/Question.java
> +        deleteHistories.addAll(answers.deleteAnswers(user));
그게 고민이었어요, 불변 객체로 만들고 싶은데, Add를 해야 하다 보니 변수를 final로 선언도 못하게 되는 문제가 발생하더라구요,

다만 또 다른 방향에서 보면 List<DeleteHistory> deleteHistories 처럼 List에다가 전부 담은 다음에
DeleteHistories 객체에 넣으면 그게 무슨 소용인가..? 라는 고민에 위와 같이 작성하게 되었습니다.

뭐가 좋을까요? 저도 얘기하다보니 리뷰어님이 말씀해주신 대로 후자가 맞아보이네요 ㅋㅋ