[볼링 점수판 - 3단계] 코드 리뷰 요청드립니다
next-step/java-bowling pull request #510
Opened 2021-04-28 11:35 UTC by cocahack

3단계 구현 완료했습니다! 2단계 때 열심히 해서 그런지 3단계는 의외로 수월하게 구현할 수 있었습니다. 😁

그런데 이걸 이렇게 해도 될까 하는 생각이 드는 부분도 있었는데요. 그 부분에 대한 질문은 아래에 따로 하겠습니다.

그럼 3단계 잘 부탁드립니다! 🙇‍♂️

2021-04-28 11:43 UTC, cocahack commented on src/main/java/bowling/domain/engine/frame/Frames.java
> +        }
모든 프레임의 점수를 추출하는 부분입니다. 

모든 프레임을 한 번에 초기화하는 방식으로 바꾸다보니, 일부 프레임들은 계산이 불가능한 경우가 발생했습니다.   
이걸 처리하려고 여러 가지 생각을 해보다가, 이렇게 구현했습니다.
NPE 의 위협에서 자유로워지고 싶어서 절대 `null` 을 반환하지 않으려고 했는데, 이번에는 그러지 못했네요.

아무리 `private`. 접근제어를 가진 메소드여도, `null` 을 반환하지 않는 것이 좋을 것 같은데, 어떻게 생각하시나요?

2021-04-29 07:47 UTC, slamdunk7575 requested changes
`Score` 클래스를 분리하여 점수 계산 잘 구현해주셨네요 👍

고민하시는 점수 출력 부분에 코멘트 남겨드렸는데 확인해보시고 요청 주시면 좋을것 같아요!

끝까지 화이팅 입니다! 🥇

2021-04-29 07:47 UTC, slamdunk7575 commented on src/main/java/bowling/domain/engine/frame/Frames.java
> +        }
우선 저도 `null`을 반환하는 것은 `안티 패턴`이라고 생각합니다. 
null 을 리턴하는 것은 메서드를 호출한 쪽에서는 null 체크를 해줘야 하는데 null 처리가 잘 안되어 있는 코드에서는 `NPE` 발생 확률이 높기 때문입니다.

`null` 관련해서는 아래의 내용도 참고해보시면 좋을거 같습니다.
[[Clean Code] 7장 | 오류 처리](https://velog.io/@jwkim/Clean-Code-7%EC%9E%A5-%EC%98%A4%EB%A5%98-%EC%B2%98%EB%A6%AC)
[악취나는 코드 개선하기 시리즈 - NULL](https://jojoldu.tistory.com/176)

현재 `Ready, Playing` 상태에서는 `점수 계산`을 하지 않으려고 `CannotCalculateScoreException`을 던지고 null을 반환하도록 처리하셨는네요 🤔 

제가 생각해본 방법은 `Ready, Playing` 도 현재 `Score` 를 반환하게 만들고 `isCalculationCompleted()` 를 이용하여 리팩토링 해볼 수 있을것 같네요. 

이건 제가 임의로 해본거라 참고만 하시고 명철님이 좀 더 좋은 방법으로 개선해보시면 좋겠네요 😄

<img width="868" alt="스크린샷 2021-04-29 오후 4 10 32" src="https://user-images.githubusercontent.com/15867808/116514881-959e2780-a906-11eb-9fcc-e5278feea28a.png">

<img width="488" alt="스크린샷 2021-04-29 오후 4 10 42" src="https://user-images.githubusercontent.com/15867808/116514908-9d5dcc00-a906-11eb-968e-2b094d7382d9.png">

<img width="578" alt="스크린샷 2021-04-29 오후 4 10 51" src="https://user-images.githubusercontent.com/15867808/116514934-a3ec4380-a906-11eb-821e-d18e1d5d0651.png">

2021-04-29 07:47 UTC, slamdunk7575 commented on src/test/java/bowling/domain/engine/frame/ScoreTest.java
> +class ScoreTest {
`ScoreTest` 잘 작성해주셨네요 👍
`NormalFrameTest`에도 아래처럼 `점수 계산 테스트`를 해보면 좋을거 같네요 😄

```
    @Test
    @DisplayName("일반 프레임에서 STRIKE 이면 추가 2번 보너스 투구로 점수 계산")
    void strike_calculate_score() {
        // given
        NormalFrame nextFrame = NormalFrame.init();
        NormalFrame currentFrame = NormalFrame.init(nextFrame);

        currentFrame.roll(RollResult.of(10));

        // when
        nextFrame.roll(RollResult.of(4));
        nextFrame.roll(RollResult.of(3));

        // then
        assertThat(currentFrame.getScore()).isEqualTo(Score.initReadyToUseScore(17));
    }
```

2021-04-29 07:47 UTC, slamdunk7575 commented on src/test/java/bowling/domain/concrete/frame/state/SpareTest.java
>  class SpareTest {
선택이 되지 않아 이부분에 남겨드려요.
아래 `cannotTransit()` 테스트의 `DisplayName`이 변경되어야 겠네요 😄

`@DisplayName("Spare 상태는 더 이상 다른 상태로 바뀔 수 없다.")`

2021-04-29 11:15 UTC, cocahack commented on src/test/java/bowling/domain/concrete/frame/state/SpareTest.java
>  class SpareTest {
👌

2021-04-29 12:42 UTC, cocahack commented on src/main/java/bowling/domain/engine/frame/Score.java
> +    private final int injectionCount;
👌

클래스로 분리한다면 이전 단계에서 피드백 주셨던 `FinalFrame` 의 Count 클래스처럼 구현해볼 수 있겠네요!

2021-04-29 12:48 UTC, cocahack commented on src/main/java/bowling/domain/concrete/frame/NormalFrame.java
> +    private Frame nextFrame;
하나도 맞추지 못했다면 Gutter 로 표기하는군요.

좀 찾아보니 프레임에서 모든 핀을 쓰러트리지 못했다면 Open Frame 또는 Open 이라고 표기한다고 나와있네요. 특정 상황에 대한 용어가 정리되어 있는 곳이 없어서 제대로 된 용어를 사용하기가 어렵네요. 😭

이런 경우에는 클라이언트(?) 인 포비의 미션 스크립트를 따라갈까 합니다. 실제 업무에서 고객이 사용하는 용어를 사용하는 경우도 있었는데, 그런 상황에 빠졌다고 상상하면 되지 않을까요? 적용하기 싫어서 이렇게 말씀드리는 건 아닙니다. 😁

2021-04-29 13:04 UTC, cocahack commented on src/test/java/bowling/domain/engine/frame/ScoreTest.java
> +class ScoreTest {
👌

2021-04-29 13:07 UTC, cocahack commented on src/main/java/bowling/domain/engine/frame/Frames.java
> +        }
https://github.com/next-step/java-bowling/pull/510#discussion_r622792782 코멘트 감사합니다. 

여러가지로 생각해봤는데, 사용할 수 없는 점수를 추상화해서 그걸 반환하는 것이 어떨까 해서 이렇게 바꿔봤습니다.

2021-04-30 06:14 UTC, slamdunk7575 commented
`File Changes`에 잡히지 않아 코멘트로 남겨드립니다 😄

- `DTO`는 데이터 전달 역할만 수행하도록 깔끔하게 리팩토링 해보면 좋을것 같아요.
<img width="598" alt="스크린샷 2021-04-30 오후 3 07 09" src="https://user-images.githubusercontent.com/15867808/116655805-a3b37d00-a9c6-11eb-90ab-005d0d04ad3d.png">

- 사용하지 않는 `ListUtils` 클래스는 제거하는게 좋겠네요.

2021-04-30 06:37 UTC, slamdunk7575 approved these changes
피드백 반영 잘해주셨네요 👍 고생하셨습니다.
개선해 볼 부분과 그동안 신경쓰지 못했던 소소한 피드백 드렸는데 다음 미션에서 같이 고민해보시면 좋을것 같아요.
마무리까지 얼마 남지 않으셨네요~ 끝까지 화이팅 입니다! 🥇

2021-04-30 06:37 UTC, slamdunk7575 commented on src/main/java/bowling/domain/engine/frame/FrameCreator.java
>      }
지금처럼 현재 `Frame`에서 `NextFrame`을 참조하고 있는 구조라면
`볼링 투구(transit)` 후에 다음 프레임을 생성한다면 `FrameCreator` 를 제거할 수 있을것 같네요 😄

2021-04-30 06:37 UTC, slamdunk7575 commented on src/main/java/bowling/view/ConsoleResultView.java
>          stringBuilder.append(alignCenter("NAME")).append(DELIMITER);
`매직 스트링 (예:NAME)`도 `상수`로 관리하여 의미를 나타낼수 있을거 같아요!

File Changes에 잡히지 않아 여기에 같이 남겨드립니다 😄

<img width="598" alt="스크린샷 2021-04-30 오후 3 07 09" src="https://user-images.githubusercontent.com/15867808/116656802-44566c80-a9c8-11eb-8217-4576d5e79538.png">

2021-04-30 06:37 UTC, slamdunk7575 commented on src/test/java/bowling/domain/concrete/frame/NormalFrameTest.java
> +    }
테스트 꼼꼼히 잘 해주셨네요 👍

2021-04-30 06:48 UTC, merged

2021-04-30 06:49 UTC, cocahack commented on src/main/java/bowling/domain/concrete/frame/state/Ready.java
> +    }
이 부분은 한 번 생각해보겠습니다. 

`Frame` 에서 점수를 가져올 때 추가 점수를 다른 프레임으로부터 가져오는 로직도 포함돼서 어느 시점에 에러가 발생할 지 가늠하기가 어렵네요. 

로직이 복잡한 걸보니, 뭔가 설계를 잘못한게 아닐까 의심스럽긴 하네요.

2021-04-30 06:50 UTC, slamdunk7575 commented on src/main/java/bowling/domain/concrete/frame/NormalFrame.java
> +    private Frame nextFrame;
`볼링 점수 계산`과 관련하여 참고해보시면 좋을 링크입니다 😄
[볼링 점수 계산법](https://kini.kr/510)

2021-04-30 12:43 UTC, slamdunk7575 commented on src/main/java/bowling/domain/concrete/frame/NormalFrame.java
> +    private Frame nextFrame;
저도 볼링 점수 계산에 대해 잘 몰라 헤맸었는데요 😭 
아래 링크도 한번 참고해보시면 좋겠네요!

[볼링 점수 계산법](https://kini.kr/510)