Step1 - 리뷰 요청합니다.
next-step/java-bowling pull request #511
Opened 2021-04-28 12:52 UTC by abcdsds

힌트에 Question을 일급컬렉션으로 만들라고했는데 Answer는 이해가가는데 Question은 모르겠네요..
최대한 get안쓰려고 노력해봤습니다
리뷰 잘부탁드립니다.

2021-04-29 11:10 UTC, siyoon210 commented
Question의 일급컬렉션을 고민하신것 같네요..ㅎㅎ Question은 굳이 만들필요가 없습니다. 
DeleteHistory를 일급컬렉션으로 만들어보세요. 🙂

2021-04-29 11:10 UTC, siyoon210 commented
저도 세숑케릭터 좋아하는데요.. 여기서 보니까 더 반갑네요 ㅋㅋ

2021-04-29 11:11 UTC, siyoon210 commented
수정하시고 테스트코드도 추가해주세요!

2021-04-29 11:13 UTC, siyoon210 requested changes
안녕하세요 대식님! 마지막 미션을 함께하게된 리뷰어 정시윤입니다! 
프로그래밍 요구사항을 다른방향으로 고민하셔서 어렵게 느껴지신것 같네요.. 해당 부분에 대해서 안내 드렸습니다.
진행중 어려운 부분이나 이야기 해보고 싶으신 사항이 있으시다면 메시지나 댓글 남겨주세요.
(댓글에 경우 확인이 어려울 수 있으니 댓글 남기시고 메시지 주시면 감사하겠습니다. 🙇 )
끝까지 화이팅입니다. 😄

2021-04-29 11:13 UTC, siyoon210 commented on src/main/java/qna/domain/Answers.java
> +                .anyMatch(answer -> answer.isOwner(loginUser));
이렇게 검사하면 Answer중에 단 하나만이라도 자신이 쓴 글이라면 true가 나오지 않을까요? 🤔

2021-04-29 11:13 UTC, siyoon210 commented on src/main/java/qna/domain/MyQuestions.java
> +public class MyQuestions {
Question은 굳이 일급컬렉션으로 만드실 필요 없습니다. 🙂

2021-04-29 11:13 UTC, siyoon210 commented on src/main/java/qna/domain/Answers.java
> +        }
- answer 내부에 유효성검사와 DeleteHisotry를 만들어서 반환하는 메서드를 만들어보는 방향은 어떨까요?
answers에서는 answer들을 순회하며 메서드를 호출하고 deleteHistory를 담기만 하는거에요.

- List\<DeleteHistory\>를 일급컬렉션으로 만들어보세요! 🙂

2021-04-29 11:13 UTC, siyoon210 commented on src/main/java/qna/service/QnAService.java
> +        myQuestions.delete(deleteHistories);
delete 메서드가 삭제한 내역을 반환하는건 어떨까요?
```suggestion
        DeleteHistories deleteHistories = question.delete(deleteHistories);
```

2021-04-29 11:49 UTC, abcdsds commented
> 저도 세숑케릭터 좋아하는데요.. 여기서 보니까 더 반갑네요 ㅋㅋ

세숑이를 아시는군요 ㅎㅎ

2021-04-29 12:46 UTC, abcdsds commented
리뷰 감사합니다 저는 객체반환을 무조건 하면안되는줄알고 객체반환자체를 안하는 방향으로 짜고 있어서 이상하게 짯었던것 같습니다.

2021-04-30 10:53 UTC, siyoon210 approved these changes
안녕하세요 대식님!
피드백사항을 바로 반영해주셨네요. 👏👏 
이번 단계는 머지하도록 하겠습니다. 본격적인 미션도 계속 진행해주세요! 😄

2021-04-30 10:53 UTC, siyoon210 commented on src/main/java/qna/domain/DeleteHistories.java
> +public class DeleteHistories {
일급컬렉션이 Iterable 인터페이스를 구현하도록 해보세요. Repository에서도 자연스럽게 동작할꺼에요!

```
public class DeleteHistories implements Iterable<DeleteHistory> {
    private final List<DeleteHistory> value;

    // ...

    @Override
    public Iterator<DeleteHistory> iterator() {
        return value.iterator();
    }
}
```

2021-04-30 10:53 UTC, merged