[4단계 - 볼링 점수판(n명)] 리뷰 요청 드립니다!
next-step/java-bowling pull request #517
Opened 2021-04-28 21:06 UTC by seongbeenkim

안녕하세요 유라님!

처음 구현 시 4단계는 큰 수정 및 시간이 들지 않고 완료되었습니다. 

하지만, State 패턴 공부하고 적용하여 리팩토링을 해본다면 하나라도 더 느낄 수 있고 성장할 수 있는 기회라고 생각했고 또한 미션을 제대로 마무리 짓고 싶어 기존 구현 완료된 소스를 step4라는 곳에 복사 후 전체적인 리팩토링 진행하였습니다!

이번 리팩토링 힌트를 보고 구현하며 전략 패턴과 비슷한 생성 패턴이라는 것도 공부하고 적용하면서 제가 이전에 불필요한 객체들을 많이 생성하여 더 복잡한 코드가 되었다는 것을 느꼈고, 각 상태에서 할 수 있는 일을 정의함으로써 더 간결하고 객체지향적이게 코드를 작성할 수 있다는 것을 느꼈던 것 같습니다!

현재 하루종일 밤을 새면서 계속 지웠다 썼다 리팩토링을 하느라 커밋이 뒤죽박죽 되어있어 초기화 후 하나의 객체당 커밋을 다시 작성하여 커밋 로그가 애매하게 보일 수도 있지만 감안해서 봐주시면 감사하겠습니다!!

부족한 점 피드백 주시면 공부해서 수정하도록 하겠습니다! :)

2021-04-29 15:23 UTC, dbeod2 requested changes
성빈님! 
4단계 미션 열심히 구현해주셨네요! 
테스트코드도 잘 작성해주셨고, 고민하신 부분이 녹아든 것같네요 
너무 고생많으셨어요! :)  
몇 가지 의견드린 부분이 있는데 확인 부탁드립니다.

2021-04-29 15:23 UTC, dbeod2 commented on src/main/java/bowling/domain/Player.java
import java.util.List가 사용되지 않고 있네용! ㅎㅎ 미사용 코드는 제거해주세용 :)

2021-04-29 15:23 UTC, dbeod2 commented on src/main/java/step4/domain/Frames.java
> +                .map(symbols -> String.join("|", symbols))
"|" <- view코드는 도메인과 분리 해야 할 것같습니당 
다른방법이 없을지 고민해보시는건 어떠실까용 ?

2021-04-29 15:23 UTC, dbeod2 commented on src/main/java/step4/domain/Score.java
> +    public Score add(Score score) {
미사용 메서드네요! 과감하게 지워주시면 될 것같습니다!

2021-04-29 15:23 UTC, dbeod2 commented on src/main/java/step4/controller/BowlingController.java
> +    protected void playGame(Players players) {
접근 제어자를 protected로 선언하셨네요!
어떤 이유로 선언하셨을까요 ?.?

2021-04-29 15:23 UTC, dbeod2 commented on src/main/java/step4/domain/Players.java
> +    }
players는 참여자에 대한 일급 컬렉터라고 판단이 됩니다.

marks, scores, names는 다른 역할이라고 판단되는데 어떻게 생각이 되시나용 ?

2021-04-29 15:23 UTC, dbeod2 commented on src/main/java/step4/domain/Player.java
> +    }
player에 역할이 아닌 부분들이 포함되어 있는 것같아요!
각자의 도메인에서 책임을 가지게 할 수있을 것같네용!

2021-04-29 17:41 UTC, seongbeenkim commented on src/main/java/bowling/domain/Player.java
앗 항상 커밋 전 reformat 코드를 해주게 하는 편인데 안해주었나보네요ㅠㅠ
수정하였습니다!

2021-04-29 17:41 UTC, seongbeenkim commented on src/main/java/step4/domain/Score.java
> +    public Score add(Score score) {
넵넵! 해당 부분도 지웠습니다! 감사합니다!

2021-04-29 18:02 UTC, seongbeenkim commented on src/main/java/step4/controller/BowlingController.java
> +    protected void playGame(Players players) {
3단계에서 `marks()`를 사용하는 볼링 컨트롤러 테스트 코드를 작성하라는 피드백 주신 것을 반영하기 위해서
컨트롤러의 해당 메서드 테스트 코드 작성하려고 `protected`로 선언했던 부분이었습니다.

2021-04-29 20:11 UTC, seongbeenkim commented on src/main/java/step4/domain/Frames.java
> +                .map(symbols -> String.join("|", symbols))
넵 도메인과 분리 되어있어야 할 것 같네요!!
해당 함수 제거 후 view에서 "|" 추가하도록 수정하였습니다!

2021-04-29 20:26 UTC, seongbeenkim commented on src/main/java/step4/domain/Players.java
> +    }
Player들의 상태 그리고 Player들을 가지고 어떤 행위를 할 수 있는 곳이 일급컬렉션이라고 생각을 했고 
그렇기 때문에 `List<Player>`를 stream을 사용한 필요한 목록들을 반환하게 하는 것도 가능하지 않을까라는 생각에 위와 같이 구현을 했던것 같습니다.
또한 marks, scores, names를 해주지 않는다면 players()를 반환한 후 이름 목록, 점수 목록, 결과 표시 목록을 사용하는 곳마다 players.stream()을 하면서 해야 하기 때문에 코드도 길어지고 반복되는 코드가 많아지지 않을까라는 생각도 있었습니다!

하지만, 피드백을 받은 후 생각해보니 현재 미션에서는 여러 곳에서도 사용하지 않고 한 곳에서만 하나의 목적에 맞게 사용하기 때문에 굳이 필요없다고도 생각하게 되었고 또한 단순 목록 반환이 아닌 Player들을 가지고 어떤 행위를 한 후 결과 값을 반환해주는 게 일급컬렉션내에서 더 어울린다고 생각하여 해당 함수들 제거해주었습니다!

2021-04-29 20:53 UTC, seongbeenkim commented on src/main/java/step4/domain/Player.java
> +    }
어떻게 리팩토링을 할 수 있을까?하면서 고민해본 결과 똑같은 구조가 나오게 되어 `Player` 이름을 `BowlingGame` 변경해서 사용하게 하였습니다..

__이유__
`Player`에는 `Name`, `Frames`이 있기 때문에
frames(), scores()를 분리해주게 된다면 `Player`는 `Name`만 가지게 된다고 생각하였습니다.

그리고 볼링 게임 시작전 사람 수의 따라 `사람 이름, 프레임 각 10개, 점수`를 각각 생성하게 한다면
`Players, Frames, Scores` 이렇게 세 개가 생성하게 될텐데
이를 개별적으로 관리하면 각자의 책임만 가지게 된다는 장점도 있지만 이렇게 개별적으로 수행하고 필요한 곳에 인자로 넘겨주는 것보다는 
볼링 게임 특성상 3개의 개념이 연관되어 있기 때문에 이를 담아줄 수 있는 객체가 있는 것이 좋다고 생각하였습니다.

`Player` 한 명의 플레이어당 `Frames` 10개의 프레임을 가지고,
`Frames` 10개의 프레임에 대한 `Scores` 점수를 반환해야하는 구조이기 때문에

`Player`와 `Frames`를 가지는 객체를 만들고
해당 객체에서 `Frames`를 인자로 가지기 때문에 해당 인자를 통한 점수`Scores`도 반환하면 되지 않을까라는 생각을 했습니다!

그러고 보니 현재 `Player`의 객체 구조가 같다는 결론이 나오게 되었고 이를 `BowlingGame`이라는 이름으로 변경한다면 말씀해주신 frames(), scores()도 해결되는 것이 아닐까? 라고 생각하여 위와 같이 이름만 변경하게 되었습니다.

저는 이렇게 생각하여 결국에는 이름만 변경하게 된 똑같은 구조로 돌아오게 되었는데
이 부분에 있어서 피드백 주시면 감사하겠습니다ㅠㅠ

2021-04-30 03:44 UTC, dbeod2 commented on src/main/java/step4/domain/Player.java
> +    }
BowlingGame이라는 객체에서 하는게 맞을 것같아요! 
지금 객체는 player (참여자)를 위한 객체라고 판단이 되어서 의견드린 부분이었습니다! 
하나의 책임만 가지고 있는 객체인데 다른 역할까지 동시에 진행되는 느낌이라서용 
bowlingGame이라는 객체에서 말해주신 구조로 가도 좋을 것같다는 의견 드립니다 : )

2021-04-30 04:07 UTC, seongbeenkim commented on src/main/java/step4/domain/Player.java
> +    }
넵넵 현재 미션에서 참여자는 이름에 대한 책임만 가지고 있는 도메인인데 
이미 이름에 대한 검증은 'Name'에서 해주고 있어 사실상 참여자를 위한 객체가 'Name'라고 봐도 무방하다고 생각하여 이름만 변경하면서 리팩토링을 한 것 같습니다! 피드백 감사합니다:)

2021-04-30 10:02 UTC, dbeod2 approved these changes
성빈님! :) 
마지막 볼링 미션까지 달려오시느라 고생많으셨습니다! 
피드백 잘 반영해주셔서 여기서 미션 머지하겠습니다. 👏🏻👏🏻👏🏻

그동안 너무 잘 수행해주셨습니다.
많이 고민하시고, 그것을 코드로 풀어내셨던 부분이 정말 저한테 많이 인사이트를 주었던 것 같습니다.🙇🏻‍♀️
여기까지 오시느라 고생 많으셨습니다.!

완주를 축하드립니다!! 🎳 🎳 🎳 🎳 🎳

2021-04-30 10:02 UTC, merged

2021-04-30 10:19 UTC, seongbeenkim commented on src/main/java/step4/domain/BowlingGame.java
> +public class BowlingGame {
유라님!
피드백을 주셔서 많이 배울 수 있었던 것 같습니다! :)
지난 2주 동안 4단계 미션 봐주셔서 감사했습니다!