[Step3] 볼링 점수판(점수 계산) 리뷰 요청드립니다.
next-step/java-bowling pull request #527
Opened 2021-05-01 15:53 UTC by PandaHun

안녕하세요 지훈님 :)

우선 지난 피드백 #500 에 대한 리팩토링도 진행했으나
https://github.com/next-step/java-bowling/pull/500#discussion_r621047805 에서
말씀하신 부분을 어떻게 개선해야할 지 모르겠어서 진행하지 못했습니다.

그리고 지난 구현에서 게임이 진행되지 않는 점도 있었어서 리팩토링 수행했습니다.

이번 미션에서는 단순한 점수 계산이라는 하나의 기능인데도 많은 복잡함과 어려움이 있었던 것 같습니다.
특히 객체지향 생활체조 원칙의 3개 이상의 상태를 안갖도록 하다보니, 설계에 어려움을 겪었습니다.

한가지 생각난 점은 Player와 Frame을 묶는 것도 좋은 방안이라 생각이 들기는 하지만, 우선 리뷰 요청드리겠습니다

그럼 날카로워도 부드러워도 좋으니 많은 피드백 부탁드립니다! 🙇‍♂️

2021-05-02 13:44 UTC, vagabond95 requested changes
이전 코멘트에서 제 설명이 부족했던 것 같습니다 😢 
점수 구현 스펙은 최대한 역할을 잘 나누어 수행하도록 노력하신 흔적이 보입니다!

다만, 좀 더 역할 배분을 다시해볼 수 있는 포인트가 몇군데 보이는데요, 이전 내용과 연관하여 남겼습니다 ㅎㅎ 
진행 중 의도 파악이 어렵거나 논의하고 싶은 점 있으시면 편하게 DM 주세요!

2021-05-02 13:44 UTC, vagabond95 commented on src/main/java/bowling/domain/Score.java
> +        this.leftOpportunity = leftOpportunity;
Score 는 득점한 점수를 관리하는 객체로 보이는데요!

* '점수'가 남은 횟수를 카운트하는 leftOpportunity 필드가 해당 클래스에서 필요할지 고민해보면 좋을 것 같아요. ㅎㅎ

해당 필드로 인해 다음과 같은 고민점이 생기고 있는데요.
1.  Score 가 throwBall() 이라는 행위를 가지는게 맞을까? 점수가 ball 을 던진다는 것은 어색하지 않을까
2. leftOpportunity 필드로 인해 자연스레 Spare 나 Strike 와의 의존성도 생기게 되는데 점수를 나태나는 필드에서 꼭 필요할까?
3. canCalculateScore() 의 내부 구현도 leftOpportunity 와 연관되어 있는데, 점수가 스스로 계산 가능하는지 판단하는 로직이 정작 점수와는 큰 관련이 없지않나?

정도의 생각이 드는거 같습니다!

2021-05-02 13:44 UTC, vagabond95 commented on src/main/java/bowling/domain/Frames.java
> +    public Frame nFrame(int n) {
축약어 사용은 되도록 지양하면 좋을 것 같습니다~!

네이밍을 봤을때 어떤 역할을 수행하는지 알기 어려울 수 있을 거 같아요 ㅎ

2021-05-02 13:44 UTC, vagabond95 commented on src/main/java/bowling/domain/Pins.java
> +    public boolean isStrike() {
이전단계에서 코멘트 드린  [ScoreMark](https://github.com/next-step/java-bowling/pull/500/files/99e506432ded1da783b380143f4dc8c121225166#diff-75612b3e5161f307e4fd129310e2af9059ba598ab91829e72702cfa88da0ec6c) 와 같은 맥락으로 코멘트 드릴 수 있을 것 같은데요! 

우선 제가 코멘트 설명이 부족했던것 같습니다 😢 
ScoreMark 는 도메인 영역에 속해있는 클래스임에도 불구하고 도메인이 어떻게 '표현'될지에 대한 정보를 담고 있어 코멘트를 남기게 되었습니다. Score 를 그리는 방식에 대한 요구사항이 변경될경우 도메인에 변경사항이 전파되는데 이는  MVC 패턴을 활용한 이점이 줄어들지 않을까요? ㅎㅎ

따라서 ScoreMark 를 각각 도메인 영역과 뷰 영역으로 분리해야한다고 생각이 들었어요. 도메인 영역에서는 쓰러진 핀의 개수에 따라서 어떤 점수가 되는지 나태내고, 뷰 영역에서는 각 특정 점수가 ( ex/ strike) 어떻게 그려지는지 알고 있는 것이죠 :)

만약 ScoreMark 를 도메인 영역으로 분리한 클래스가 생긴다면, STRIKE_COUNT  상수는 더이상 필요없게 되겠죠 ㅎㅎ

2021-05-02 13:44 UTC, vagabond95 commented on src/main/java/bowling/domain/Pins.java
> +    public boolean isBonusTry() {
pins 클래스는 'pin 콜렉션을 다루는' 일급 컬렉션으로 보이는데요,
 bonusTry 인지 firstTry 인지 판단하는 것은 일급 컬렉션의 역할을 넘어서는 행위 아닐까요?
 
 도메인 상 이는 Frame 에서 판단할 수 있는 영역 아닐까요? ㅎㅎ

2021-05-02 14:07 UTC, PandaHun commented on src/main/java/bowling/domain/Pins.java
> +    public boolean isStrike() {
음 이부분은 아직도 크게 잘 와닿지 않는 것 같습니다 😢 

저는 오히려 Score를 그리는 부분에 대한 기능을 ScoreMark가 해준다고 생각합니다.
물론 도메인 패키지 보다는 다른 위치가 좋겠지만 해당 위치가 모호해서 변경하지 못했습니다.

만약 Score를 그리는 부분이 변경된다면, ScoreMark의 View 부분만을 수정해 변경사항이 전파될 수 있다고 생각합니다.

2021-05-02 14:11 UTC, PandaHun commented on src/main/java/bowling/domain/Score.java
> +        this.leftOpportunity = leftOpportunity;
우선 Score가 각 프레임에 대한 점수를 관리하고 있는 객체가 맞습니다.
> '점수'가 남은 횟수를 카운트하는 leftOpportunity 필드가 해당 클래스에서 필요할지 고민해보면 좋을 것 같아요. ㅎㅎ
해당 부분에 대해선 `Strike`와 `Spare`가 이후 추가 투구의 점수를 필요하기에 남은 기회를 추가해주었습니다.

2,3번에 대해서도 위의 내용에 대한 차이로 생기는 거라고 생각합니다! 😢

2021-05-03 10:36 UTC, vagabond95 commented on src/main/java/bowling/domain/Pins.java
> +    public boolean isStrike() {
위치가 모호하다는 것이 곧 ScoreMark 의 역할이 SRP 관점에서 명확하지 않다는 의미 아닐까요? ㅎㅎ
Score 를 그리는 부분이 변경된다면 현재로서는 ScoreMark 의 View 부분만 수정하면 되지만, 그렇게 될경우 MVC 패턴으로 분리한 의미가 없다고 생각합니다.

MVC 와 같은 패턴을 차용하는 이유는 결국 계층을 분리하여 변경되는 이유가 같은것끼리 모아 변경에 유연한 구조를 만들기 위함이라고 생각하는데요, View 의 요구사항의 변경이 도메인 영역의 클래스에 영향을 끼친다면 계층을 나눈다는 의미가 사라지는 것이 아닐까 개인적으로 생각해봅니다 :)

2021-05-03 10:42 UTC, vagabond95 commented on src/main/java/bowling/domain/Score.java
> +        this.leftOpportunity = leftOpportunity;
'점수' 라는 것을 어떤 관점에서 보느냐에 따라 서로 다른 해석이 나온 것 같습니다 :)

제가 생각하는 'Score' 클래스는 는 말그대로 쓰러트린 핀의 개수만큼 상태(strike, spare 등) 가 결정되고, 그 상태에 의한 점수를 '표현'하는 객체 즉, 원시값 포장 클래스라고 생각을 해서 위 코멘트를 드렸었습니다. 따라서 점수가 ball 을 던진다라는 역할을 수행하는 것도 어색하다고 보았구요 ㅎㅎ

다훈님이 정의하신 Score 클래스는 점수를 관리하는 총체적인 클래스로 생각하셔서 위와같은 접근을 하신 것 같습니다~!

구현상의 정답은 없으며, 다만 Score 클래스에서 leftOpportunity 필드를 다뤘을때와 다루지 않았을 떄의 트레이드 오프를 한번쯤 고민해셨으면 좋겠습니다~!

2021-05-03 10:45 UTC, vagabond95 commented
리뷰어는 정답을 제시하는 것이 아니라 다른 방향에서 바라볼 수 있도록 도움을 드리는 역할이라고 생각하기 때문에, 그대로 따르지 않으셔도 당현히 괜찮고 당연히 제 코멘트 의도가 납득되지 않는 부분이 있으실 수 있을 것 같습니다 ㅎㅎ 
관점의 차이에 따라 얻고, 잃는 것이 있을 텐데 그 부분에 대입하여 한번 생각해보는 기회가 되셨으면 해서 남겼습니다! 저도 당연하게 생각했던 내용을 곰곰히 생각해보는 내용이 되었습니다. 감사합니다~!

2021-05-03 10:45 UTC, merged