[ Step2 볼링판 그리기 ] 리뷰 요청합니다.
next-step/java-bowling pull request #550
Opened 2021-05-04 11:53 UTC by abcdsds

마지막날이라 finalFrame에서 | 구분 맞추는걸 제대로 못맞췄습니다.
그리고 급해서 리팩토링도 못하고 올립니다..

마지막 리뷰 잘부탁드립니다...

2021-05-04 14:03 UTC, siyoon210 commented
![image](https://user-images.githubusercontent.com/15173693/117015519-c75f2600-ad2c-11eb-8542-cd7cfd02375f.png)

- 0, 10 입력시에 실행결과가 이상하네요. 🤔

2021-05-04 14:38 UTC, siyoon210 requested changes
안녕하세요 대식님! 본격적인 미션 구현하시느라 고생하셨습니다. 👏 
마지막 날이라 조금 조급한 마음이셨던것 같네요.. 🙂  
정규과정이 끝나게 되어도 미션에 대한 피드백은 계속 드리고 있습니다. 
몇가지 코멘트 드렸으니 천천히 고민해보시고 수정후에 다시 요청해주세요! 😄 
고생하셨습니다!

2021-05-04 14:38 UTC, siyoon210 commented on src/main/java/bowling/domain/BowlingGame.java
> +        BowlingController.start(player);
Player의 생성을 BowlingGame에서 하신 이유가 있을까요? 
BowlingGame이 어플리케이션을 실행시키는 역할이라면 Player의 생성도 Contoller에게 맡기는건 어떤가요?

2021-05-04 14:38 UTC, siyoon210 commented on src/main/java/bowling/domain/controller/BowlingController.java
> +package bowling.domain.controller;
패키지 구조가 domain이 가장 상위패키지이고 다른 패키지들이 domain의 하위 패키지로 설정되어있네요.
저는 domain을 핵심적인 로직과 값을 가지고 있는 객체라고 정의하는데요. 이런면에서 볼 때 Controller, View와 같은 패키지는 domain이라고 보기 힘들지 않을까요? 🤔

2021-05-04 14:38 UTC, siyoon210 commented on src/main/java/bowling/domain/controller/BowlingController.java
> +            int frameRoundCount = getFrameRoundCount(frame);
```suggestion
            int frameRoundCount = frame.getFrameRoundCount();
```
```java
//class Frame
public int getFrameRoundCount() {
    Round round = frame.getRound();
    return round.getRound();
}
```
frame 객체의 기능으로 제공해보는건 어떤가요? 🙂

2021-05-04 14:38 UTC, siyoon210 commented on src/main/java/bowling/domain/dto/FrameResponse.java
> +public class FrameResponse {
해당 클래스는 Frame을 담아서 이동만 하고 있는 걸로 보이는데요. 어떤의도인지 알기 어렵네요.. 💭 
domain을 DTO로 변환시키는것이 목적이라면 필요한 값들을 가지고 있는 구조는 어떤가요?
```suggestion
public class FrameResponse {
    private PitchState pitchState;
    //...
```

2021-05-04 14:38 UTC, siyoon210 commented on src/main/java/bowling/domain/frame/FinalFrame.java
> +    private Frame frame;
frame이 이전 frame으로 보이는데 맞을까요? 😄 좀 더 의미를 알기 쉬운 이름으로 바뀐다면 좋겠습니다.
```suggestion
    private Frame previousFrame;
```

2021-05-04 14:38 UTC, siyoon210 commented on src/main/java/bowling/domain/frame/NormalFrame.java
> +        return this;
NormalFrame과 LastFrame이 거의 유사하고 Frame을 반환하는 부분만 다르고,
이부분이 Round에 의존적인 것 같네요.. Round가 다형성을 갖는것도 괜찮을 것 같습니다. 🙂

2021-05-04 14:38 UTC, siyoon210 commented on src/main/java/bowling/domain/frame/Round.java
> +        return new Round(ResultView.MIN_FRAME, new Start());
🚨 domain 객체가 View 객체에게 의존하게 되었네요. 🚨 
저는 '의존'하다는 것은 `의존하고 있는 객체가 변화할때 그 변화를 함께 감수하겠다.` 라고 정의해요. 🙂
view가 변경될때 그 영향이 domain에 가는것은 불필요한 결합도라고 생각합니다.

2021-05-04 14:38 UTC, siyoon210 commented on src/main/java/bowling/domain/frame/Round.java
> +    public boolean isNext() {
pitch를 해야하는지 반환하는 메서드인데요. hasNext()라는 네이밍은 어떤가요?
```suggestion
    public boolean hasNext() {
```

2021-05-04 14:38 UTC, siyoon210 commented on src/main/java/bowling/domain/Player.java
> +    public static int NAME_MAX_SIZE = 3;
```suggestion
    public static final int NAME_MAX_SIZE = 3;
```
상수이니 final 키워드를 사용해주세요!

2021-05-04 14:38 UTC, siyoon210 commented on src/main/java/bowling/domain/Player.java
> +    public static int NAME_MAX_SIZE = 3;
ResultView, Round, Start, Strike 의 상수에도 같은 코멘트 드리겠습니다. 🙂

2021-05-05 13:33 UTC, abcdsds commented on src/main/java/bowling/domain/controller/BowlingController.java
> +package bowling.domain.controller;
급하게하냐고 domain안에다 넣어버렸네요..ㅠ

2021-05-11 13:30 UTC, siyoon210 approved these changes
안녕하세요 대식님!
전해드린 피드백을 잘 반영해주셨네요! 전체적으로 코드와 설계가 깔끔한 것 같습니다! 💯 
이번 단계는 여기서 머지하도록 하겠습니다! 😄

2021-05-11 13:30 UTC, siyoon210 commented on src/main/java/bowling/domain/frame/FinalRound.java
> +        return count > FINAL_MAX_COUNT;
isMaxRound()랑 구현이 같으니, 그대로 호출하는건 어떤가요? 🤔 
```suggestion
        return isMaxRound();
```

2021-05-11 13:30 UTC, siyoon210 commented on src/main/java/bowling/domain/Player.java
> +    public static int NAME_MAX_SIZE = 3;
Player NAME_MAX_SIZE는 final 키워드를 빠드리신거 같아요. 🙂

2021-05-11 13:30 UTC, merged

2021-05-13 09:26 UTC, abcdsds commented
> 안녕하세요 대식님!
> 전해드린 피드백을 잘 반영해주셨네요! 전체적으로 코드와 설계가 깔끔한 것 같습니다! 💯
> 이번 단계는 여기서 머지하도록 하겠습니다! 😄

리뷰 감사합니다.