[4단계 - 볼링 점수판(n명)] 리뷰 부탁드립니다
next-step/java-bowling pull request #556
Opened 2021-05-13 02:31 UTC by HJ-Woo

안녕하세요 리뷰어님 🙏  

이번 점수판에서는 ``Player``와 ``Players``를 새로 만들어서 수행했는데요,  
플레이어를 나타내는 ``Player``는 앞선 단계에서 프레임들의 목록이었던 ``Frames``와 이름인 ``Name``을 보유하고 있습니다.  
플레이어 목록을 나타내는 ``Players``에서는 플레이어간 차례를 구분하여 공을 굴릴 수 있게 해두었습니다.

고민인 부분이 있는데 혹시 의견 부탁드려도 될까요?  
``Player``에서는 내부 ``frames``의 로직을 재호출하는 역할밖에 제대로 수행하질 못해서, 플레이어를 새로 만들어내는 것보다는  
``Frames``에 이름을 추가해서 Player로 명명하는 것이 옳았을지 의견을 여쭙고 싶습니다 🙏 

수정이 필요한 부분이나 잘못된 부분이 있다면 바로 수정하겠습니다  
이번 리뷰도 잘 부탁드리겠습니다 감사합니다 :)

2021-05-13 02:58 UTC, javajigi requested changes
마지막 단계까지 구현하느라 수고했네요. 💯 
소소한 피드백 몇 개 남겼어요.

2021-05-13 02:58 UTC, javajigi commented on src/main/java/bowling/domain/player/Name.java
> +    public static Name of(String name) {
거의 대부분의 객체를 정적 팩토리 메서드로 구현하고 있다.
정적 팩토리 메서드를 지금과 같이 활용하는 것에 대해 어떻게 생각하나?
정적 팩토리 메서드 장,단점에 대해 생각해 보면 좋겠다.

2021-05-13 02:58 UTC, javajigi commented on src/main/java/bowling/domain/player/Player.java
> +    }
정적 팩토리 메서드로 구현하는 경우 굳이 생성자가 2개 이상이 필요한가?
`Player(Name name, Frames frames)` 생성자 하나로 구현하는 것은 어떨까?

2021-05-13 02:58 UTC, javajigi commented on src/main/java/bowling/domain/player/Player.java
> +public class Player {
질문에 대한 답변으로 Frames가 Name을 가지는 것도 좋은 선택지 중의 하나라 생각한다.
생각만 하기보다 Frames가 Name을 가지도록 구현해보고 현재의 코드와 비교 분석해 보면 어떨까?

2021-05-13 02:58 UTC, javajigi commented on src/main/java/bowling/domain/player/Players.java
> +    public List<Player> getWinner() {
메서드가 한 가지 일만 하도록 리팩토링하는 것은 어떨까?

2021-05-13 05:22 UTC, HJ-Woo commented on src/main/java/bowling/domain/player/Name.java
> +    public static Name of(String name) {
좋은 의견 주셔서 감사합니다! 🙇‍♀️🙇‍♀️

정적 팩토리 메서드의 **장점**으로는 
- 인스턴스를 구성하기까지 필요한 과정을 캡슐화할 수 있다는 점 (그리고 생성자에는 생성 역할만 수행할 수 있게 됨)
- 다형성을 제공 (`OneHit`의 `of`에서 생성자로 수행시 타입이 `OneHit`으로 고정되어야하겠지만, 수행 로직에따라 상태를 반환할 수 있도록 `State` 타입을 제공할 수 있음)

저는 두 가지 장점에 주목해서 설계해보았습니다.

다만, **단점**으로는 아래와 같은 점을 고려해야한다고 알고 있습니다.
-  정적팩토리 메서드로만 제공하고 생성자를 ``private``으로 두는 경우엔, `public`과 `protected` 생성자가 없어서 상속이 어렵기 때문에 확장성을 잃어버릴 수 있음  

지금의 설계로는 인터페이스나 추상클래스를 제외하고는 상속보단 **조합**으로 구성하고 있어서 정적 팩토리 메서드를 사용했는데 이후의 확장성을 고려하거나 오히려 장점이 독이 될 수는 없을지 고려해야할 것 같습니다.  

혹시 제가 생각하고 있는 부분에서 잘못되었거나 추가로 의견을 주실 수 있는 부분은 부탁드려도 괜찮으실까요? 🙏🙏

2021-05-13 05:24 UTC, HJ-Woo commented on src/main/java/bowling/domain/player/Player.java
> +public class Player {
> *생각만 하기보다 구현해보고*   

좋은 말씀인것 같습니다👍👍  
별 어려움 없이 리팩토링이 가능한걸로 보아 역할을 그대로 연결해주기만 했어서 이런 방법으로 구현했다면 좀 더 수월했을거란 생각이 듭니다. 😅

2021-05-16 02:48 UTC, javajigi approved these changes
피드백 반영 잘 했네요. 💯 
지금까지 미션 진행하느라 수고했어요.
이번 교육 과정이 개발자로서의 역량을 한 단계 성장시키는데 도움이 되었기를 바래요.

2021-05-16 02:48 UTC, merged