Feature/step1 review request
next-step/java-bowling pull request #595
Opened 2021-08-30 15:50 UTC by woung717

잘 부탁드립니다~

2021-08-31 12:49 UTC, ksundong requested changes
안녕하세요. 현웅님! 😊 리뷰어 김선동입니다.
저와 함께 마지막 미션인 볼링 미션을 하시게 되었군요! 정말 반갑습니다! 👏 👏 👏
부족한 리뷰어지만 현웅님의 성장을 위해서 노력하겠습니다~

미션 진행하느라 고생하셨습니다!
이대로 머지해도 충분하지만, 생각해보면 좋을거리들이 보여서 해당 부분에 대한 피드백을 남겨드렸습니다. 💪

확인하시고 다시 리뷰 요청 부탁드립니다! 💪
궁금한 점이나 고민이 되는 부분은 코멘트 혹은 DM으로 언제든 남겨주세요! 🙏🏼

2021-08-31 12:49 UTC, ksundong commented on src/main/java/qna/domain/Answer.java
> +    }
요구사항엔 없지만
답변도 작성자만 삭제가능해야하지 않을까요?
요구사항이 아니어서 언급만 드립니다!

2021-08-31 12:49 UTC, ksundong commented on src/main/java/qna/domain/Answers.java
> +    }
depth 2단계를 지켜주세요~

2021-08-31 12:49 UTC, ksundong commented on src/main/java/qna/domain/Question.java
> +    }
`validateOwner` 같은 식의 네이밍은 어떨까요?

2021-08-31 12:49 UTC, ksundong commented on src/main/java/qna/service/QnAService.java
> +        List<DeleteHistory> deleteHistories = question.deleteWithAnswers();
주석 말고 지워주시면 어떨까요?

2021-08-31 12:49 UTC, ksundong commented on src/main/java/qna/service/QnAService.java
> +        question.isOwnerElseThrow(loginUser);
이 부분도 도메인 스스로 판단할 수 있지 않을까요?

2021-08-31 12:49 UTC, ksundong commented on src/main/java/qna/service/QnAService.java
> +        question.hasOnlyOwnAnswersElseThrow();
이 부분도 마찬가지입니다~

2021-08-31 13:41 UTC, woung717 commented on src/main/java/qna/domain/Question.java
> +    }
일반적으로 validate라고 한다면 입력값에대한 검증을 하는 메소드라는 의미는 있지만 네이밍에서 리턴값으로 검증결과를 알려주는것인지 예외를 발생시키는것인지 직관적으로 인지를 하기 어려울것 같아 해당 ~ElseThrow와 같은 네이밍방식을 적용해보았습니다. 퍼블릭 메소드가 void validate~() 라고 한다면 메소드 내부를 살펴보기 전까지는 외부에서 검증에대한 처리를 어떻게 해야할지 알기 어려울것같습니다.

2021-09-01 12:22 UTC, ksundong commented on src/main/java/qna/domain/Question.java
> +    }
사실 확실하게 처리방법을 알려주는 방법은 Java에 이미 있습니다.
그건 바로 `CheckedException`을 사용하는 것이지요.
하지만 여기서 저희가 `UncheckedException`을 사용하는 이유는 무엇일까요?
해당 처리를 코드레벨에서 할 수 없기 때문이 아닐까요?
그렇다면 이 메서드를 사용하는 클라이언트 측에서는 굳이 `Exception`이 발생함을 알아야할까요?

2021-09-01 13:01 UTC, ksundong approved these changes
안녕하세요. 현웅님! 😊 리뷰어 김선동입니다.

1단계 피드백 반영하느라 고생하셨습니다!

이제 본격적인 볼링 미션이 시작되네요..! 파이팅입니다!
궁금한 점이나 고민이 되는 부분은 코멘트 혹은 DM으로 언제든 남겨주세요! 🙏🏼

2021-09-01 13:01 UTC, merged