[Step1] 리뷰 잘 부탁드립니다!
next-step/java-bowling pull request #602
Opened 2021-09-01 16:28 UTC by ckdgus08

2021-09-02 16:10 UTC, JunHoPark93 requested changes
안녕하세요 창현님~
새로운 미션을 같이 시작하게 되어 반갑습니다!
1단계 잘 구현해주셨어요 👍
간단한 피드백 몇가지 남겨두었는데요, 확인 후 의견 또는 반영 부탁드려요!

2021-09-03 14:04 UTC, ckdgus08 commented on src/main/java/qna/domain/Answers.java
> +    }
1. 기존방식 : 
 질문 작성자와 로그인 사용자 비교 -> 질문 삭제 ->  for(답변 작성자와 로그인 사용자 비교 -> 답변 삭제)
 
2. 개선방식 :
 질문 작성자와 로그인 사용자 비교 -> 질문 삭제 -> 준호님이 말씀해주신 방식으로 validation -> 답변 작성자와 로그인 사용자 비교하지 않고 답변 삭제
 
 기존 방식은 userId, name, email 등 String 값을 비교하는 로직이 항상 반복되고 있는데 준호님께서 말씀하신대로 개선하면 성능상 이점을 얻을 수 있을 것 같습니다! 좋은 피드백 감사합니다 !

2021-09-04 01:25 UTC, JunHoPark93 approved these changes
안녕하세요 창현님~
피드백 빠르게 잘 반영해주셨네요 고생하셨습니다!
그럼 본격적으로 미션 진행해주시면 될 것 같아요 :)
2단계에서 뵙겠습니다!

2021-09-04 01:25 UTC, JunHoPark93 commented on src/test/java/qna/domain/QuestionTest.java
> +    @DisplayName("글을 삭제할때, 본인이 작성하지 않은 답변이 있으면 에러가 발생한다.")
잘 추가해주셨네요 👍

2021-09-04 01:26 UTC, merged