Step2 - 볼링 점수판(그리기)
next-step/java-bowling pull request #603
Opened 2021-09-02 05:26 UTC by jaeyoungjang2

안녕하세요 리뷰어님!!

2단계 볼링 점수판을 구현하였습니다.
처음에는 막막 하였지만, 계속해서 수정하여 기능을 완성하였습니다.

많이 미숙하여 수정할 점이 많을 것으로 보입니다.
코드를 뒤집어 엎을 각오는 되어있습니다!!

열심히 하도록 하겠습니다!

피드백 부탁드립니다!
감사합니다!

2021-09-05 12:48 UTC, JunilHwang requested changes
안녕하세요 재영님! step2 진행 잘 해주셨네요 👍 
다만 View와 Domain이 조금 섞여 있는 것 같아요! 
이런 부분은 분리해서 관리해주면 어떨까요?

2021-09-05 12:48 UTC, JunilHwang commented on src/main/java/bowling/domain/BowlingGameManager.java
> +    }
domain 패키지인데 view 로직이 섞여있는 것 같아요! 
아예 명시적으로 Controller 라고 표현해주면 어떨까요?

2021-09-05 12:48 UTC, JunilHwang commented on src/main/java/bowling/domain/BowlingUser.java
> +    private static final BowlingScore bowlingScore = new BowlingScore();
멤버변수는 최대 2개로 유지해주세요.

2021-09-05 12:48 UTC, JunilHwang commented on src/main/java/bowling/util/BowlingScore.java
> +}
Domain에 View 로직이 섞여있는 것 같아요!
이런 부분은 명시적으로 View에게 위임해주면 어떨까요?

2021-09-06 10:27 UTC, jaeyoungjang2 commented on src/main/java/bowling/domain/BowlingUser.java
> +    private static final BowlingScore bowlingScore = new BowlingScore();
1. 멤버변수를 2개로 특정하신 이유가 있을까요??
2. 멤버변수를 적게 유지하라 == 클래스를 작게 나눠라  비슷한 의미로 이해하면 될까요??

2021-09-06 10:28 UTC, jaeyoungjang2 commented on src/main/java/bowling/domain/BowlingGameManager.java
> +    }
Controller로 변경하였습니다!

2021-09-06 10:29 UTC, jaeyoungjang2 commented on src/main/java/bowling/util/BowlingScore.java
> +}
view로 옮겨주었습니다.
리뷰어님께서 말씀하신 의도를 잘 이해한건가요??

2021-09-06 10:29 UTC, jaeyoungjang2 commented
리뷰어님이 주신 피드백을
반영하였습니다!!

확인 부탁드립니다.
감사합니다!

2021-09-07 00:49 UTC, JunilHwang commented on src/main/java/bowling/domain/BowlingUser.java
> +    private static final BowlingScore bowlingScore = new BowlingScore();
넵 ㅎㅎ 말씀해주신 것 처럼 객체를 작은 단위로 유지하기 위함입니다!

2021-09-07 01:00 UTC, JunilHwang requested changes
안녕하세요 재영님! 피드백 반영 잘 해주셨네요. 다만 의도 전달지 잘 안 된 것 같네요 ㅠㅠ
Domain은 View의 존재를 아예 몰라야한답니다!
지금은 Domain에서 View 패키지를 가져와서 사용하고 있어요. 이 부분은 꼭 개선해주세요!
그리고 테스트코드가 아예 없네요 😅
테스트 코드도 작성 부탁드려요!
이 외에 여러가지 리뷰 남겼으니 확인 부탁드립니다 🙇‍♂️

2021-09-08 03:06 UTC, jaeyoungjang2 commented on src/main/java/bowling/controller/BowlingGameController.java
> +    private static final RandomScore randomScore = new RandomScore();
제가 문제를 잘 못 이해하였습니다.
ㅜㅜ 사용자로 부터 입력값을 받아서 진행하도록 수정하였습니다.

2021-09-08 03:10 UTC, jaeyoungjang2 commented on src/main/java/bowling/domain/PlayerName.java
> +            throw new IllegalArgumentException(NAME_LENGTH_ERROR_MESSAGE);
검색해보니 customException을 사용하면 예외를 더 잘 알아볼 수 있다는 장점이 존재한다고 말하고 있습니다.
아래와 같이 수정을 하였는데, 정확한 방향으로 수정한 것이 맞는지 확인 부탁드립니다.
```
private void validUserName(String userName) {
        if (userName.length() != 3) {
            throw new UserNameLengthError();
        }
    }
```
customErrorMessage를 만드는 기준이 있을까요??
errorMessage는 무조건 Custom으로 만들어서 사용하는 걸까요??
그렇다면 errorMessage 클래스가 너무 많아질 것 같은데
이럴때는 어떻게 처리를 하시는 걸까요??

2021-09-08 03:24 UTC, jaeyoungjang2 commented
리뷰어님 안녕하세요!
구조적인 문제가 커 보여, 다시 작성해 보았습니다.

이번에는 더 많은 시간을 가지고, 신중히 구현을 하였습니다. 
리뷰어님의 피드백을 최대한 반영을 하려고 노력하였습니다!
확인 부탁드립니다.

감사합니다!

2021-09-09 12:22 UTC, JunilHwang requested changes
안녕하세요 재영님! 리뷰가 많이 늦었네요 ㅠㅠ 죄송합니다.
몇 가지 피드백 남겼으니 다시 확인 부탁드려요!

2021-09-09 12:22 UTC, JunilHwang commented on src/main/java/bowling/domain/PlayerName.java
> +            throw new IllegalArgumentException(NAME_LENGTH_ERROR_MESSAGE);
저는 일단 에러 메세지도 exception 내부에서 관리하고 있습니다!

2021-09-09 12:22 UTC, JunilHwang commented on src/main/java/step2/domain/BowLingScoreViewFormat.java
> +    MISS ("-") { public boolean apply(int bowlingScore, int totalScore, int tryNumber) {return bowlingScore == 0 && tryNumber >= 2;}},
이 enum이 지금 view와 domain이 뒤섞여 있는 것 같아요~ `X` `/` `-` 등의 문자는 view에서 표현해주면 어떨까요?

2021-09-09 12:22 UTC, JunilHwang commented on src/main/java/step2/domain/BowLingScoreViewFormat.java
> +    }
이건 view의 역할이 아닐까요?

2021-09-09 12:22 UTC, JunilHwang commented on src/main/java/step2/domain/FinalFrame.java
> +        if (score() > 10) {
상수를 선언해놓고 사용하질 않고 있네요!

2021-09-09 12:22 UTC, JunilHwang commented on src/main/java/step2/domain/FinalFrame.java
> +            throw new IllegalArgumentException("쓰러뜨린 볼린공의 개수는 10개 이하로 지정하여야 합니다.");
custom exception으로 만들어주면 좋을 것 같아요~

2021-09-09 12:22 UTC, JunilHwang commented on src/main/java/step2/domain/Frame.java
> +}
abstract로 선언한 다음에 하위 클래스에서 구현이 필요한 부분만 override 해서 사용해보면 어떨까요?

2021-09-09 12:22 UTC, JunilHwang commented on src/main/java/step2/domain/NormalFrame.java
> +    private List<Integer> frame;
NormalFrame은 2개의 frame만 가지는데, 이렇게 List로 관리할 필요가 있을까요?

2021-09-09 12:22 UTC, JunilHwang commented on src/main/java/step2/domain/NormalFrame.java
> +    }
앞선 리뷰와 동일합니다!

2021-09-09 12:22 UTC, JunilHwang commented on src/test/java/step2/domain/NormalFrameTest.java
> +}
테스트코드가 전체적으로 빈약한 것 같아요!
도메인의 메소드에 1:1 매칭 되도록 코드를 작성해주세요!

2021-09-10 00:43 UTC, jaeyoungjang2 commented on src/main/java/step2/domain/FinalFrame.java
> +        if (score() > 10) {
수정하였습니다!

2021-09-10 00:57 UTC, jaeyoungjang2 commented on src/main/java/step2/domain/Frame.java
> +}
수정하였습니다!

2021-09-10 01:01 UTC, jaeyoungjang2 commented on src/main/java/step2/domain/FinalFrame.java
> +            throw new IllegalArgumentException("쓰러뜨린 볼린공의 개수는 10개 이하로 지정하여야 합니다.");
수정하였습니다!

2021-09-10 01:01 UTC, jaeyoungjang2 commented on src/main/java/step2/domain/NormalFrame.java
> +    }
수정하였습니다!

2021-09-10 01:24 UTC, jaeyoungjang2 commented on src/main/java/step2/domain/BowLingScoreViewFormat.java
> +    MISS ("-") { public boolean apply(int bowlingScore, int totalScore, int tryNumber) {return bowlingScore == 0 && tryNumber >= 2;}},
리뷰어님 어떤 부분이 domain의 성격을 가지고 있는지 이해하지 못하였습니다.
해당 enum은 점수를 볼링 스크린에 나타나는 포맷 형태로 변환해주는 것입니다.

10 -> X
3|7 -> 3|/
3|0 -> 3|-

view에 성격이 강하여 해당 코드를 view 폴더로 옮기거나
util의 성격이 강하여 해당 코드를 util 폴더로 옮기는건 이해가 가는데
해당 코드를 view와 domain으로 나눠야 하는 것은 어떻게 진행해야 할 지 이해가 가지 않습니다.
조금만 더 자세하게 피드백을 주실 수 있을까요?
감사합니다!

2021-09-10 01:38 UTC, jaeyoungjang2 commented on src/main/java/step2/domain/NormalFrame.java
> +    private List<Integer> frame;
List로 관리하는 것이 유지 보수, 확장성 측면에서 조금 더 편리할 것 같았습니다.
해당 NormalFraame과 FinalFrame의 차이가 MAX_TURN 변수 한개만 바꿔주면 된다는 점에서 큰 이점이 있는 것 같습니다.

List를 사용하지 않는다면 
private int firstTurn;
private int secondTurn;
으로 지정하여 각각의 값을 따로 관리하는 것이 더 좋을까요??

2021-09-10 01:42 UTC, jaeyoungjang2 commented on src/main/java/step2/domain/Frame.java
> +}
제가 피드백을 제대로 적용한 것이 맞을까요?
추상메서드는 public abstract를 생략해도 되는것 같은데
abstract를 적어주는 이유는 메서드의 의도를 확실히 보여주기 위해서 일까요?

2021-09-10 02:23 UTC, jaeyoungjang2 commented on src/test/java/step2/domain/NormalFrameTest.java
> +}
테스트 코드를 추가하였습니다!

2021-09-10 03:55 UTC, jaeyoungjang2 commented on src/main/java/step2/domain/BowLingScoreViewFormat.java
> +    MISS ("-") { public boolean apply(int bowlingScore, int totalScore, int tryNumber) {return bowlingScore == 0 && tryNumber >= 2;}},
리뷰어님이 말씀해주시는 방향을 이해하였습니다.
enum의 구조를 변경하도록 하겠습니다!!
이 부분은 step3 을 진행하면서 적용을 해도 괜찮을까요??
감사합니다!

2021-09-11 00:55 UTC, JunilHwang commented on src/main/java/step2/domain/Frame.java
> +}
넵 맞습니다 !

2021-09-11 00:55 UTC, JunilHwang commented on src/main/java/step2/domain/NormalFrame.java
> +    private List<Integer> frame;
넵 ㅎㅎ 말씀해주신 내용이 맞습니다.

2021-09-11 00:56 UTC, JunilHwang approved these changes
안녕하세요 재영님! 피드백 반영 잘 해주셨네요 👍 
말씀해주신 것 처럼 이번에 적용하지 못한 것들은 다음 단계에 적용해도 무방하답니다 ㅎㅎ
일단 Step2는 여기서 마무리하겠습니다!
바로 Step3 진행해주세요!!

2021-09-11 00:56 UTC, merged