Step3 - 볼링 점수판(점수 계산)
next-step/java-bowling pull request #681
Opened 2021-09-14 17:00 UTC by SSONG22

안녕하세요 리뷰어님! 벌써 마지막날이네요..;ㅅ; 
마음은 급하고, 구현은 생각보다 어려워서 애를 먹었네요🥲
마지막날까지 잘 부탁드립니다! 감사합니다 😊

2021-09-15 12:04 UTC, ksundong requested changes
안녕하세요. 송이님! 😊 리뷰어 김선동입니다.

3단계 진행해주시느라 고생하셨고
https://github.com/next-step/java-bowling/pull/682
여기 참고하셔서 이곳에서 피드백 반영해주신 다음 4단계에 도전해주세요. 😊

확인하시고 다시 리뷰 요청 부탁드립니다! 💪
궁금한 점이나 고민이 되는 부분은 코멘트 혹은 DM으로 언제든 남겨주세요! 🙏🏼

2021-09-15 15:08 UTC, SSONG22 commented
4단계서 주신 피드백 내용으로 수정했습니다 :) 마지막까지 너무너무 감사드려요!

2021-09-16 11:21 UTC, ksundong approved these changes
안녕하세요. 송이님! 😊 리뷰어 김선동입니다.

3단계 피드백 잘 반영해주셨습니다. 바로 머지하고 다음 단계에서 해당 피드백을 반영한 후에
다시 리뷰요청 해주세요! 고생하셨습니다!

궁금한 점이나 고민이 되는 부분은 코멘트 혹은 DM으로 언제든 남겨주세요! 🙏🏼

2021-09-16 11:21 UTC, ksundong commented on src/main/java/bowling/domain/NormalFrame.java
> +        if (pitches.size() == 1) {
1은 특별한 의미가 있는 숫자로 보입니다~

2021-09-16 11:21 UTC, ksundong commented on src/main/java/bowling/domain/Pitches.java
> +        int sumOfNormalPitch = pitches.get(0).intValue() + countOfPins;
여기 0도 특별한 의미가 있는 숫자로 보이네요.

2021-09-16 11:21 UTC, ksundong commented on src/main/java/bowling/domain/Score.java
> +    private int leftPitch;
저라면 `Count`까지 붙여서 명확하게 나타냈을 것 같아요~

2021-09-16 11:21 UTC, ksundong commented on src/main/java/bowling/domain/Score.java
> +        return new Score(score += countOfPins, leftPitch -= 1);
저는 개인적으로 이런 경우에는 라인을 분리해서 표현해줍니다.
혼동의 여지가 많은 코드여서요!

2021-09-16 11:21 UTC, merged

2021-09-16 11:42 UTC, SSONG22 commented on src/main/java/bowling/domain/Score.java
> +        return new Score(score += countOfPins, leftPitch -= 1);
라인을 분리한다는게 잘 이해가 가지 않는데 `score += countOfPins`를 ` socre + countOfPins `로 쓰신다는 말씀이신가요 ?_?