Step1
next-step/java-bowling pull request #743
Opened 2021-12-19 14:15 UTC by jhsmyth99

안녕하세요.
1단계 - 질문 삭제하기 기능 리팩토링 
개발완료하여 풀리퀘스트 요청 드립니다.
감사합니다.

2021-12-20 04:58 UTC, wheejuni requested changes
수고 많으셨어요. 👍 
제출에 앞서 한번쯤은 코딩 컨벤션 미준수 사항이 있는지 확인을 부탁 드리겠습니다.
아울러 수정 시도해보실 만한 사항들 정리해서 피드백 남겼는데요, 확인 부탁드려요~ 💯

2021-12-20 04:58 UTC, wheejuni commented on src/main/java/qna/domain/Answers.java
> +    }
불필요한 개행이 있네요~

2021-12-20 04:58 UTC, wheejuni commented on src/main/java/qna/domain/Answers.java
> +        List<DeleteHistory> deleteHistories = new ArrayList<>();
이렇게 외부에 컬렉션 만들어 놓고 삽입/삭제하는 액션 취하지 않기 위해 스트림 사용하는 목적이 큰데요, 좀 아쉽네요.
스트림의 종단 연산을 활용하시면 이 변수가 선언되지 않고 바로 리턴할 수 있었을 텐데요. 수정 부탁드려요.

2021-12-20 04:58 UTC, wheejuni commented on src/main/java/qna/domain/DeleteHistories.java
> +    }
일급 컬렉션이라는 관점에서 이 클래스가 들고 있는 삭제 이력이 자유롭게 추가된다면 이 클래스는 해야할 임무를 다 하지 못하고 있는 상황으로 판단되네요.
내용물이 바뀐다면 기존 객체는 버리고 새로운 객체가 만들어지는 것이 일급 컬렉션의 기본인데요, 수정되면 좋을 것 같습니다.

2021-12-20 14:59 UTC, jhsmyth99 commented
안녕하세요.
피드백 주신 내용 반영하였습니다.
감사합니다.

2021-12-21 13:08 UTC, wheejuni requested changes
수고하셨습니다. 💯 
간단한 수정 조금만 해 주세요. 감사합니다. 👍

2021-12-21 13:08 UTC, wheejuni commented on src/main/java/qna/domain/Answers.java
> +import static qna.exception.ConsumerExceptionWrapper.wrapper;
스태틱 임포트는 조금 신중하셔야 할 부분이, 이게 아무런 맥락 없이 인라인에 `wrapper()` 라고 덩그러니 남게 되거든요;
컨텍스트 파악에 많은 시간이 걸릴 수도 있습니다. 물론 커맨드 누르고 찍으면 메소드 선언부로 넘어가긴 하겠지만요.

2021-12-21 13:08 UTC, wheejuni commented on src/main/java/qna/exception/ConsumerExceptionWrapper.java
> +    }
같은 인터페이스가 두 번 선언돼 있네요?

2021-12-21 13:08 UTC, wheejuni commented on src/main/java/qna/exception/ThrowableFunctionalInterface.java
> +    void doSomething() throws Exception;
명확하게 행동을 정의해주세요.

2021-12-22 10:14 UTC, jhsmyth99 commented on src/main/java/qna/domain/Answers.java
> +import static qna.exception.ConsumerExceptionWrapper.wrapper;
static import를 사용하지 않도록 변경하였습니다.

2021-12-22 10:14 UTC, jhsmyth99 commented on src/main/java/qna/exception/ConsumerExceptionWrapper.java
> +    }
중복된 인터페이스를 삭제했습니다.

2021-12-22 10:14 UTC, jhsmyth99 commented on src/main/java/qna/exception/ThrowableFunctionalInterface.java
> +    void doSomething() throws Exception;
해당 인터페이스는 사용하지 않아서 삭제처리 하였습니다.

2021-12-23 07:48 UTC, wheejuni approved these changes
👍

2021-12-23 07:48 UTC, merged