[볼링] Step4
next-step/java-bowling pull request #747
Opened 2021-12-22 03:46 UTC by ydh6226

드디어 마지막 단계네요 😂
꼼곰하게 리뷰해주신 덕에 다양한 관점에서 생각해볼 수 있었습니다 🙇‍♂️
마지막 리뷰도 잘 부탁드려요!

2021-12-23 00:24 UTC, sah3122 requested changes
기존 구조가 잘 잡혀있어 4단계 미션 구현도 어렵지 않게 해주신것 같아요. 
한가지 생각거리를 남겨두었는데 확인 부탁드립니다 😄

2021-12-23 00:24 UTC, sah3122 commented on src/main/java/bowling/domain/bowling/BowlingGame.java
> +    }
메소드가 하나의 일만 할 수 있도록 Pitch 와 remainPitch를 분리해보는건 어떨까요 ?

2021-12-23 00:24 UTC, sah3122 commented on src/main/java/bowling/domain/bowling/BowlingGame.java
> +    private final List<Bowling> fixedBowlings;
Bowlings 일급 컬렉션을 만들어 Queue를 사용하지 않고 메시지를 던지는 구조로 변경할수 있을것 같은데, 어떻게 생각하시나요 ?

2021-12-23 12:16 UTC, ydh6226 commented
pitch에 포함되어있던 '**게임이 끝났는지에 대한**' 로직을 `isGameInProgress()`으로 분리했습니다. 

Bowlings 일급컬렉션을 만들지 않고,
Queue대신 turn 이라는 변수로  볼링의 순서를 관리했는데 이 구조도 좋다고 생각이들어서 우선 리뷰요청드립니다!

2021-12-24 15:27 UTC, sah3122 approved these changes
마지막 미션까지 잘 구현해주셨습니다 😄 
많은 코멘트를 남겨드리지 못해 아쉽네요 😢  
볼링 미션은 여기서 마치도록 할게요 🙏 
그동안 강의 들으며 미션 진행해주신다고 너무 수고 많으셨습니다. 💯

2021-12-24 15:27 UTC, sah3122 commented on src/main/java/bowling/domain/bowling/BowlingGame.java
> +    private final List<Bowling> bowlings;
코멘트의 의도는 잘 반영된것 같습니다 ㅎㅎㅎ

2021-12-24 15:28 UTC, merged