🚀 3단계 - 볼링 점수판(점수 계산)
next-step/java-bowling pull request #764
Opened 2021-12-26 14:59 UTC by soosue

우선... 지금 커밋내역이 뭔가 꼬인 것 같은데... 방법을 모르겠네요. 😢

리뷰주신 내용을 먼저 적용해봤습니다. 책임을 분리하는 느낌으로?요.

사실 이전 방식대로 점수 계산까지 구현을 해놨었는데... 책임을 분리하고 하다보니.. 결국 새로 다시 짜야해서 살짝 멘붕왔었습니다.. ㅎㅎ

하지만 이 코드가 이전보다 더 나은 코드인 것 같아 기분이 좋네요! (아 물론.. 아직 고칠 것은 많겠지만요,)
리뷰 부탁드립니다! 😄

2021-12-27 13:13 UTC, liquidjoo requested changes
볼링 점수 계산 구현 너무 잘해주셨어요 👍 
몇가지 코멘트 남겼어요 확인하고 다시 요청주세요~

2021-12-27 13:13 UTC, liquidjoo commented on src/main/java/bowling/domain/PinCounts.java
> +    private static final int MAX_SIZE = 2;
클래스는 상수, 멤버 변수, 생성자, 메서드 순으로 작성합니다.
상수는 상위에 선언해주는 것이 좋을 것 같아요~

2021-12-27 13:13 UTC, liquidjoo commented on src/main/java/bowling/domain/state/Bonus.java
> +                .intValue();
```suggestion
        int sum = getValues().stream().map(KnockedPinCount::value)
                .reduce(ZERO, Integer::sum);
```
언박싱을 하지 않아도 될 것 같아요 ~ :)

2021-12-27 13:13 UTC, liquidjoo commented on src/main/java/bowling/view/OutputView.java
> +        if (state instanceof Bonus && isSpare(state)) {
instanceof 없이 어떻게 구현해 볼 수 있을까요?

2021-12-27 14:12 UTC, soosue commented on src/main/java/bowling/domain/NormalFrame.java
>      }
같이 혼용해서 사용하는 방법은 좋지 않은 방법일까요??

2021-12-27 14:23 UTC, soosue commented on src/main/java/bowling/domain/PinCounts.java
> +    private static final int MAX_SIZE = 2;
그러게요... 쟤가 왜 저기에 가있을까요 😭...

2021-12-27 14:26 UTC, soosue commented on src/main/java/bowling/domain/FinalFrame.java
>          return null;
이건 Frames.values()에서 List<Frame>을 만들 때 의도하고 이렇게 만든건데, 다른 방식으로 바꾸는게 좋을까요?

2021-12-27 14:29 UTC, soosue commented on src/main/java/bowling/domain/BowlingGames.java
> +    public List<BowlingGame> values() {
이건 다른 리뷰어분께서 클래스 이름과 인스턴스 변수의 이름이 같은건 좋지않다고 피드백을 주셔서 values라는 변수명으로 사용하고 해당 변수를 get할 때는, values()나 getValues()와 같이 사용하고 있었어요.

getBowlingGames()나, getBowlingGameList()라고 짓기에는 BowlingGames라는 클래스이름과 너무 겹치게 될 것 같은데 다른 좋은 이름이 있을까요?

2021-12-27 14:43 UTC, soosue commented on src/main/java/bowling/view/OutputView.java
> +        if (state instanceof Bonus && isSpare(state)) {
state에 isBonus, isSpare, isFinished의 메소드를 두어서 확인하는 방법이 있을 것 같은데, State의 메소드들이 너무 많아지는 것 같아서요. 괜찮을까요?

2021-12-27 14:50 UTC, soosue commented
리뷰 감사합니다~
다시 한 번 리뷰 부탁드립니다!

2021-12-28 15:51 UTC, liquidjoo approved these changes
3단계 볼링 미션 피드백 반영 너무 잘하셨어요 👍 
마지막 단계인 4단계 미션 하나 남으셨네요~ 끝까지 화이팅 입니다
다음 단계 진행해주세요 🙇

2021-12-28 15:51 UTC, liquidjoo commented on src/main/java/bowling/domain/AbstractFrame.java
> +        return roundNumber.getRoundNumber();
피드백 반영 좋습니다 👍

2021-12-28 15:51 UTC, liquidjoo commented on src/main/java/bowling/domain/BowlingGame.java
> +        return frames.getCurrentFrameNumber();
디미터 법칙 👍

2021-12-28 15:51 UTC, liquidjoo commented on src/main/java/bowling/domain/FinalFrame.java
> +        throw new IllegalArgumentException(FINAL_FRAME_MESSAGE);
null 반환 보다는 예외 처리 or Optional 등을 활용 👍

2021-12-28 15:51 UTC, liquidjoo commented on src/main/java/bowling/domain/FrameRoundNumber.java
> +    public int getRoundNumber() {
피드백 반영 👍

2021-12-28 15:51 UTC, liquidjoo commented on src/main/java/bowling/domain/Score.java
> +    private static final int ZERO = 0;
매직 넘버 제거👍

2021-12-28 15:51 UTC, liquidjoo commented on src/main/java/bowling/domain/state/Miss.java
> +    }
상태 값이 많아지는 것도 좋지만 각 상태 값 출력 부분을 인터페이스로 정의해도 괜찮을 것 같아요 :)
다만 아쉬운 점은 View의 처리가 로직으로 들어오는 단점은 있습니다
많은 분기를 할 것 인가 or `State` 에 display 와 같이 메서드를 통해 관리할 것인가
개발자의 선택일 것 같습니다 :)

2021-12-28 15:51 UTC, liquidjoo commented on README.md
> +* stream.reduce()는 언박싱하지 않아도 된다.
리뷰 내용 정리 👍

2021-12-28 15:51 UTC, merged