[볼링 점수판 - OOP] 2단계 - 볼링 점수판(그리기)
next-step/java-bowling pull request #766
Opened 2021-12-26 16:52 UTC by orgojy

안녕하세요. 표선동 리뷰어님!
리뷰이 안이민입니다.

1~3단계에서는 Out-In 방식으로 구현했었는데요.
이번 구현에서는 In-Out 방식으로 구현해봤습니다.
조금 어려웠네요.

이번 리뷰도 잘 부탁드립니다. 🙇

2021-12-27 06:20 UTC, seondongpyo requested changes
2단계 미션 잘 진행해주셨습니다 👍
드리고 싶은 말씀은
- 점수를 문자(`X`, `/`, `-`)로 표현하는 로직은 View로 옮겨보면 좋을 것 같습니다. 
- 2번 투구해서 쓰러뜨린 핀이 10개가 넘어도 진행이 되는데 확인해주시면 좋을 것 같아요.
![image](https://user-images.githubusercontent.com/64854054/147440646-3e2307d0-5fac-4c3b-9d25-22a28caff10f.png)

궁금하시거나 의견 나누고 싶은 내용 있으시면 편하게 DM 주세요.
추가로 고민해보실만한 부분들에 대해 코멘트 드렸는데
확인 후 다시 리뷰 요청 부탁드리겠습니다 🔥

2021-12-27 06:20 UTC, seondongpyo commented on src/main/java/bowling/domain/Pins.java
> +    static final int MAX_PINS = 10;
테스트 코드에서 재사용하시기 위해 상수들의 접근 제어자를 `default`로 하신 듯 보이네요.
이건 개인적인 의견입니다만, 단위 테스트들은 독립적으로 수행되도록 작성하기도 하고 내용이 길지 않기 때문에 
상수 리터럴 정도는 그대로 작성하는 것이 오히려 더 직관적으로 눈에 띌 수 있다고 생각합니다.
지극히 개인적인 의견이니 그냥 보시고 넘어가주셔도 좋을 것 같아요.

2021-12-27 14:23 UTC, orgojy commented on src/main/java/bowling/domain/frame/BasicFrame.java
> +    }
보통 접근 지정자 순으로 정렬하곤했는데요. 말씀처럼 가독성을 위해서 위치를 올린다면 더 좋겠네요.
말씀 감사합니다. 👍

2021-12-27 14:23 UTC, orgojy commented on src/test/java/bowling/domain/frame/LastFrameTest.java
> +    @DisplayName("LastFram 생성")
네 감사합니다. 오탈자가 많네요. 🥲 
수정하였습니다.

2021-12-27 14:23 UTC, orgojy commented on src/test/java/bowling/domain/frame/FramesTest.java
> +    @DisplayName("10프레임이면서 종료상태가 아니면 다음이 존재한다")
제가 다른 테스트 케이스를 작성하려다가 코드를 복사했는데 그대로 써버렸네요.
`프레임 진행 중에 다음 투구가 가능한지 확인`로 수정하겠습니다.

2021-12-27 14:24 UTC, orgojy commented on src/main/java/bowling/domain/frame/LastFrame.java
> +        return count == MIN_BOWL && states.getLast() instanceof Miss;
네 공유해주신대로 객체가 직접 해당하는 로직을 판별할 수 있게 SOLID을 구현하는 형태로 위임해주는게 좋을 것 같네요.

2021-12-27 14:24 UTC, orgojy commented on src/test/java/bowling/domain/frame/BasicFrameTest.java
> +    void bowlFistBowl() {
네 감사합니다. 빠져있었네요. 수정하였습니다 👍

2021-12-27 14:24 UTC, orgojy commented on src/test/java/bowling/domain/frame/BasicFrameTest.java
> +class BasicFrameTest {
네 당연한 케이스지만 중요한 케이스네요. 추가했습니다!

2021-12-27 14:24 UTC, orgojy commented on src/main/java/bowling/domain/frame/Frames.java
> +    }
말씀이 맞겠네요.
진행된 프레임 중에서 가장 최근이라서 현재 프레임이라는 네이밍으로 변경하겠습니다. 👍

2021-12-27 14:24 UTC, orgojy commented on src/main/java/bowling/domain/Pins.java
> +    static final int MAX_PINS = 10;
네 말씀하신 부분에 동감 합니다.
저도 개인적으로는 공개형태로 상수 리터럴을 사용합니다. default로 한 번 시도해봤습니다. 😅 
직관적으로 보일 수 있도록 접근 지정자를 public으로 변경하여 사용하도록 하는데 저도 더 동감되네요.

2021-12-27 16:15 UTC, orgojy commented on src/test/java/bowling/domain/frame/LastFrameTest.java
> +class LastFrameTest {
네 말씀하신 덕분에 볼링게임 외에서 bowl 메서드를 호출하는 경우, 예외 케이스를 찾아서 테스트 추가했습니다. 👍

2021-12-28 01:17 UTC, seondongpyo approved these changes
피드백 반영 잘해주셨네요 💯
추가로 코멘트 하나 드렸는데 확인 부탁드릴게요.
다음 단계도 힘내주시길 바랍니다 🔥

2021-12-28 01:17 UTC, seondongpyo commented on src/main/java/bowling/domain/state/Miss.java
> +    }
현재 두 번째 투구가 거터인 경우는 `-` 문자로 잘 처리가 될텐데
첫 번째 투구가 `거터`인 경우에 대한 처리는 없어서 숫자 `0`으로 출력될 것 같네요.

2021-12-28 01:17 UTC, seondongpyo commented on src/main/java/bowling/domain/state/Miss.java
> +    }
![image](https://user-images.githubusercontent.com/64854054/147517195-96198a22-efc6-4473-9603-bc0e1bdbdd2b.png)

2021-12-28 01:18 UTC, merged

2021-12-28 02:30 UTC, orgojy commented on src/main/java/bowling/domain/state/Miss.java
> +    }
네 제가 볼링 비즈니스에 대한 이해도가 떨어져서 구현을 안했네요.
말씀하신대로 Gutter 표현은 투구 순서 여부와 상관 없이 표시되게 구현하겠습니다.

추가로 첫 코멘트에 말씀해주신 것처럼 다음 단계에서 View로 점수판 표기 로직을 이관하도록 하겠습니다.