4단계 - 볼링 점수판(n명)
next-step/java-bowling pull request #800
Opened 2022-05-15 17:02 UTC by devyonghee

안녕하세요 리뷰어님!!
이전에 코멘트 남겨주신 부분들에 대해서 많이 고민해보고 실제 코드에도 반영해보았습니다!!
이번 단계에서는 요구사항 보다 이전 코드에 대해 리팩토링하는데 더 많은 시간을 투자한 것 같습니다. 😅😅
리뷰어님께서 제공해주신 아이디어를 토대로 구현해봤는데 지도해주신 방향대로 제가 잘한건지는 잘 모르겠네요🥲

구현하다보니 애매모호한 역할들이 모델로 분산되면서 복잡도가 어느정도 해소가 되는 것 같았습니다. 👍
이전 코멘트에 남겨주신대로 저도 설계에는 항상 정답이 없다고 생각합니다. 
그래서 항상 유연한 사고를 가지고 다양한 방법을 시도해보는 것이 좋은 것 같습니다 😄😄

그럼 이번 단계 리뷰도 잘 부탁드리겠습니다! 🙇‍♂️🙇‍♂️🙇‍♂️

2022-05-16 14:28 UTC, aiden-sim requested changes
구조적인 부분은 이미 많은 고민을 하셔서 크게 리뷰 드릴 부분이 없습니다.
고민해주신 만큼 도메인에 대한 역할들도 좀 더 명확해 진 것 같습니다 👍👍👍 

그래도 마지막 미션이다 보니 소소한 리뷰 좀 남겨 놓았으니 확인 한번 부탁드리며
그 동안 미션 하시느라 고생하셨습니다 💯

2022-05-16 14:28 UTC, aiden-sim commented on src/main/java/bowling/model/Bowlings.java
> +public final class Bowlings {
사소한건데 Bowling에 대한 복수형 형태가 조금 어색해 보여 BowlingGame 등의 단어를 생각해 보았지만..
이미 Controller 에서 사용하고 있군요.

저는 일급컬렉션 사용 시, groups 라는 단어도 종종 사용합니다.
참고만 해주세요 😄

2022-05-16 14:28 UTC, aiden-sim commented on src/main/java/bowling/model/Bowlings.java
> +        this.bowlings = new ArrayList<>(bowlings);
기본적으로 객체 생성 시, 필수값 체크와 방어적 복사가 습관화 되어 있으시네요 👍

2022-05-16 14:28 UTC, aiden-sim commented on src/main/java/bowling/model/Bowlings.java
> +        Assert.notEmpty(participantNames, "participantNames must not be empty");
이 부분은 생성해 놓으신 utility가 아닌 `org.springframework.util` 를 사용하고 계시네요.
Assert 이름이 같다 보니 실수 소지가 생길것 같아 명확하게 구분되면 좋겠다는 생각을 해보았습니다 😄

2022-05-16 14:28 UTC, aiden-sim commented on src/main/java/bowling/model/Bowlings.java
> +            throw new IllegalStateException("bowlings(%s) is already finished");
```suggestion
            throw new IllegalStateException(String.format("bowlings(%s) is already finished", this));

2022-05-16 14:28 UTC, aiden-sim commented on src/main/java/bowling/model/frame/BallState.java
> +    String mark();
저희가 step2 부터 논의했지만 이 부분의 역할에 대한 고민이 많으셨을 것 같은데
저는 개인적으로 mark가 이미 고정된 상태이기 때문에 도메인에 녹여도
크게 어색하지 않다는 생각이 들었습니다.

대신 UI에서는 여러 폰트에 따라 다르게 출력해 볼 수도 있을것 같네요. 😄

2022-05-16 14:28 UTC, aiden-sim commented on src/main/java/bowling/model/frame/Frame.java
> +    Frame addBonusPins(Pins countOfHit);
이 부분에 대한 이해도가 좀 떨어져서 질문드립니다.
처음에 bonusPins을 보았을때 FinalFrame의 3번째 Pin을 의미하는줄 알았는데
Strike, Spare 처리에 대한 보너스 투구를 의미하는 것일까요 ?! 🤔

2022-05-16 14:28 UTC, aiden-sim commented on src/main/java/bowling/model/frame/FrameState.java
> +        ballStates.add(NotThrown.INSTANCE.state(pins));
요 부분에 대해서도 이해도가 조금 떨어져서 질문 드립니다.
Strike 이후에 두개의 투구를 하면 FirstThrown, SecondThrown 가 아닌
 FirstThrown, FirstThrown 두개로 생성되는것 같더라고요.
어떤 방식으로 동작하는것인지 간단하게 설명해 주시면 감사하겠습니다. 😄

2022-05-16 14:28 UTC, simjunbo commented on src/main/java/bowling/model/frame/Frames.java
>      public List<Integer> accumulatedScores() {
해당 부분이 while, if 형태를 사용하고 있다 보니 뎁스가 2가 되었네요.
리팩토링 해볼만한 요소가 없을지 고민한번만 해주세요.

2022-05-16 14:28 UTC, simjunbo commented on src/main/java/bowling/view/dto/FramesResponse.java
> -        return BallStateMarkConverter.toString(state.state(), mapCount(extractPins(state.state())));
BallStateMarkConverter 클래스가 CountToMarkConverter 로 대체 되면서
사용되고 있지 않는것 같은데 삭제해 주세요~

2022-05-16 14:28 UTC, aiden-sim commented on src/main/java/bowling/view/ResultView.java
> +        printer.printf(ROW_FORMAT, bowling.getName(), framesMessage(bowling.getFrames().getMarks()));
StringBuilder를 사용하지 않고
PrintStream를 사용하면 성능상 크게 이점이 있는지 궁금합니다 🤔 

참고) https://donggov.tistory.com/53

2022-05-16 14:28 UTC, aiden-sim commented on src/main/java/bowling/model/frame/state/NotThrown.java
> +import java.util.List;
소소하지만 사용되지 않는 import는 삭제해 주세요~

2022-05-17 00:26 UTC, devyonghee commented on src/main/java/bowling/model/Bowlings.java
> +            throw new IllegalStateException("bowlings(%s) is already finished");
아... 감사합니다!! 버릇처럼 문구만 작성했네요 ㅎㅎ

2022-05-17 00:27 UTC, devyonghee commented on src/main/java/bowling/model/Bowlings.java
> +        Assert.notEmpty(participantNames, "participantNames must not be empty");
아 감사합니다!!
이 패키지는 spring 에 대한 의존성을 가지지 않기 위해 `Assert` 를 새롭게 작성했는데 그게 오히려 독이되었네요 🥲

2022-05-17 00:33 UTC, devyonghee commented on src/main/java/bowling/model/frame/Frame.java
> +    Frame addBonusPins(Pins countOfHit);
넵 맞습니다!!
위에서 remainCount 용어를 사용하고 있지만  남은 핀을 추가로 친다는 의미해서 bonus 단어를 사용했습니다. 
저도 용어에 대해 애매모호한 부분이 있다고 생각되는데 좋은 단어가 잘 안떠오르네요 🤔

2022-05-17 00:38 UTC, devyonghee commented on src/main/java/bowling/model/frame/FrameState.java
> +        ballStates.add(NotThrown.INSTANCE.state(pins));
넵 맞습니다. 
보너스 공들에 대해서는 첫번째 공과 두번째 공이 연관이 없고 
추가로 친 핀들에 대한 정보라고 생각되어 `SecondThrown`을 사용하지 않았습니다. 
예를 들어, 한 프레임에서 `Strike`를 치고 다음 투구에 5개의 핀 2번을 맞췄다면 
이 정보는 `Strike`, `Spare` 가 아니라  `Strike` 와 5개 핀 2번 맞춘 `FirstThrown`, `FirstThrown` 이 올바르다고 생각했습니다.

2022-05-17 00:41 UTC, devyonghee commented on src/main/java/bowling/model/frame/state/NotThrown.java
> +import java.util.List;
ide 설정을 잊어버리고 있었네요!! 코멘트 감사합니다!

2022-05-17 00:41 UTC, devyonghee commented on src/main/java/bowling/view/dto/FramesResponse.java
> -        return BallStateMarkConverter.toString(state.state(), mapCount(extractPins(state.state())));
아 놓치고 있던 부분이네요 코멘트 감사합니다!!

2022-05-17 00:46 UTC, devyonghee commented on src/main/java/bowling/view/ResultView.java
> +        printer.printf(ROW_FORMAT, bowling.getName(), framesMessage(bowling.getFrames().getMarks()));
아 감사합니다!! 
`PrintStream` 이 출력과정에 있어서 내부적인 동기화처리나 OS 에서도 화면에 나오기까지의 과정이 비용이 크다는 사실을 잊고 있었습니다.
고려하지 못한 부분이었는데 이부분은 수정하도록 하겠습니다!

2022-05-17 00:57 UTC, devyonghee commented on src/main/java/bowling/model/frame/Frames.java
>      public List<Integer> accumulatedScores() {
코멘트 감사합니다!! 이 부분은 수정하도록 하겠습니다.

2022-05-17 03:25 UTC, simjunbo commented on src/main/java/bowling/model/frame/FrameState.java
> +        ballStates.add(NotThrown.INSTANCE.state(pins));
@devyonghee 이 부분이 살짝 이해가 안가네요 😢 
점수를 계산 할때는 스트라이크, 스페어에 대한 누적점수로 처리하는건 맞는데

FinalFrame을 제외 하고는
정해진 핀(10) 내에 투구를 하는게 아닌가요 ?!
앞 프레임에서 Strike, Spare 를 쳤다고 해서 다음 프레임에 주어진 핀이
보너스 개념이 아닌것 같아서 질문 드립니다.

제가 조금 햇갈리는 포인트가 이 부분이 누적 점수를 위한 부분인것인지
Strike, Spare 가 나오면 다음 핀들을 보너스 개념으로 보는 것인지 궁금합니다 🤔

2022-05-17 04:04 UTC, devyonghee commented on src/main/java/bowling/model/frame/FrameState.java
> +        ballStates.add(NotThrown.INSTANCE.state(pins));
Final 이 아니더라도 Normal 에서도 동일하다고 생각했습니다.
초기의 목적은 누적 점수를 위한 부분이긴 한데 이부분 역시 final의 보너스 개념과 동일하다고 생각했습니다.
normal 에서 본인의 상태에서 Strike 가 나온다면 그 이후의 핀들은 spare, miss 는 신경쓰지 않고 개별 투구인 것이고
spare, miss 를 판단하는 역할은 다음 프레임 번호의 normalFrame 의 역할이라고 생각했습니다.

2022-05-18 00:59 UTC, simjunbo approved these changes
피드백 잘 반영해 주셨네요 👍 

저와 함께한 시간이 조금이라도 도움이 되셨길 바라며
마지막 볼링 미션까지 진행 하시느라 고생 많으셨고
과정 완주도 축하드립니다 💯💯💯

2022-05-18 00:59 UTC, merged