Step1 질문 삭제하기
next-step/java-bowling pull request #808
Opened 2022-05-17 15:30 UTC by asqwklop12

나름 한다고는 한것 같은데
잘 모르겠네요;;

2022-05-18 07:26 UTC, yongdae requested changes
안녕하세요. 용훈님 :)
볼링 미션을 함께 하게 된 리뷰어 권용대라고 합니다!

질문 삭제하기 리팩토링 미션을 잘 수행해주셨네요 ~
진행해주신 부분에 대해 몇 가지 의견을 남겨 놓았습니다. 😄 

확인하시고 다시 리뷰 요청 부탁드릴께요.

짧은 시간이지만 미션을 함께하는 동안 잘 부탁드리겠습니다. 🙇 
그리고 언제든 의견이나 고민이 있으시다면 코멘트나 DM을 통해 이야기 부탁드리겠습니다.

2022-05-18 07:26 UTC, yongdae commented on src/test/java/qna/domain/QuestionTest.java
> +            Q1.addAnswer(AnswerTest.A1);
addAnswer() 대신 Question에 delete()를 이용해서 테스트 할 수 있는 방법은 없을까요?

2022-05-18 07:26 UTC, yongdae commented on src/test/java/qna/domain/AnswerTest.java
> +            Answer answer = new Answer(1L, null, new Question("title", "contents"), "test");
Answer도 Question처럼 delete() 메서드를 추가해서 삭제에 대한 검증을 해보면 좋을 것 같아요. :)

2022-05-18 07:26 UTC, yongdae commented on src/main/java/qna/domain/Answers.java
> +public final class Answers {
일급 컬렉션을 추가 해주셨네요. 👍

2022-05-18 07:26 UTC, yongdae commented on src/main/java/qna/service/QnAService.java
> +        question.delete();
deleteQuestion() 메서드에서 DeleteHistories를 관리하지 않고
Question의 delete() 메소드가 DeleteHistories를 반환하게 해서 사용해 볼 수는 없을까요?

2022-05-18 16:28 UTC, asqwklop12 commented
QnaServiceTest에서 delete_성공_질문자_답변자_같음에서 자꾸만 에러가 발생하네요; ㅜㅜ
확인결과 답변이 들어오고 있지 않더라구요. 분명히 그전에는 되었던 것 같은데 수정하니 안되니 제가 뭘 잘못한것 같습니다. ㅜㅜ 
어디에서 잘못한건지 몰라 일단 mr요청드립니다.

2022-05-19 04:46 UTC, yongdae requested changes
새벽까지 열심히 피드백 드린 부분을 잘 반영해주셨네요. 👍 

테스트를 통과하지 못하는 부분은 이유를 확인해서 리뷰로 답변을 남겨두었습니다.
진행해주신 내용에 대해서는 추가로 몇 가지 의견을 드렸어요.

확인하시고 다시 리뷰 요청 부탁드리겠습니다. 🔥

2022-05-19 04:46 UTC, yongdae commented on src/test/java/qna/service/QnaServiceTest.java
> +    public void delete_성공_질문자_답변자_같음() throws RuntimeException {
테스트가 실패하는 이유는 지금 수정하신 Question에 Answers를 불러오지 못하기 때문이에요.

<img width="912" alt="스크린샷 2022-05-19 오후 1 29 04" src="https://user-images.githubusercontent.com/4317804/169205411-7d917d4e-ecef-4b3b-a2c4-15a2cfb61b21.png">

Answers이 맵핑 될 수 있게 비지니스를 수정하거나 

    @OneToMany(mappedBy = "question", cascade = CascadeType.ALL)
    @Where(clause = "deleted = false")
    @OrderBy("id ASC")
    private List<Answer> answers = new ArrayList<>();

이전처럼 List<Answer>를 사용하시면 될 것 같아요. :)

2022-05-19 04:46 UTC, yongdae commented on src/main/java/qna/service/QnAService.java
> +        deleteHistoryService.saveAll(question.delete(loginUser));
피드백을 잘 반영해주셨네요. 💯

2022-05-19 04:46 UTC, yongdae commented on src/main/java/qna/domain/Question.java
> +    public List<DeleteHistory> delete(User loginUser) {
매개변수의 이름을 loginUser 대신 user를 사용해보면 어떨까요?

2022-05-19 04:46 UTC, yongdae commented on src/main/java/qna/domain/Question.java
> +        List<DeleteHistory> deleteHistories = answers.delete(loginUser);
👍

2022-05-19 04:46 UTC, yongdae commented on src/main/java/qna/domain/Answers.java
> +            answer.validateConfirmWriter(loginUser);
Answer의 delete() 메서드에서 내부적으로 validateConfirmWriter() 메서드를 호출하고 있으니
여기서는 호출하지 않아도 괜찮지 않을까요?

2022-05-19 04:46 UTC, yongdae commented on src/main/java/qna/domain/Answer.java
> +        return new DeleteHistory(ContentType.ANSWER, id, writer, LocalDateTime.now());
DeleteHistory에 [정적 팩토리 메서드](https://7942yongdae.tistory.com/147)를 적용해보면 좋을 것 같아요!

2022-05-19 12:29 UTC, asqwklop12 commented
제가 실수로 add를 하지 않았네요;; ㅜㅜ

2022-05-21 06:37 UTC, yongdae approved these changes
피드백을 잘 반영해주셨네요. 👍 
이제 본격적인 볼링 점수판 미션 진행을 하러 다음 단계로 넘어가도록 하겠습니다.

수고하셨습니다. 🙇

2022-05-21 06:37 UTC, yongdae commented on src/main/java/qna/domain/DeleteHistory.java
> +    public static DeleteHistory from(ContentType contentType, Long contentId, User deletedBy) {
💯

2022-05-21 06:37 UTC, yongdae commented on src/main/java/qna/domain/Answers.java
> +        return deleteHistories;
```suggestion
    return answers.stream()
                    .map(answer -> answer.delete(user))
                    .collect(Collectors.toList());
```

스트림을 사용하면 이렇게 만들어 볼 수 있을 것 같아요. :)

2022-05-21 06:37 UTC, merged