Step1 질문 삭제하기 기능 리팩토링 - pangnem
next-step/java-bowling pull request #817
Opened 2022-05-21 16:44 UTC by pangnem

안녕하세요. step1 제출합니다.
재성님이 라이브에서 이 step1은 반드시 해보면 좋겠다고 하셔서 이 과정 먼저 진행하게 되었습니다.
점진적인 리팩토링으로 코드를 개선하는 과정이 꽤나 재밌었습니다.

리뷰 잘 부탁드립니다.

2022-05-21 16:46 UTC, pangnem commented on src/main/java/qna/domain/qna/QnA.java
> +    protected boolean deleted = false;
너무 잘게 쪼갠건 아닐까 하는 생각이네요

2022-05-21 16:46 UTC, pangnem commented on src/main/java/qna/domain/qna/answer/Answer.java
> +    }
deleted를 출력하기 위해 접근제어자를 protected로 선언하였습니다.

2022-05-22 04:13 UTC, yongdae requested changes
안녕하세요. 주영님 ~ :)
볼링 미션을 함께 하게 된 리뷰어 권용대라고 합니다!

직문 삭제하기 기능 리팩토링 미션을 잘 진행해주셨네요. 👍 

소소하지만 몇 가지 의견을 남겨 놓았습니다.
확인하시고 다시 리뷰 요청 부탁드릴께요  ~ 🔥 

미션을 함께 하면서 의견이 있으시거나 고민이 있으시다면
언제든 코멘트나 DM을 통해 이야기를 부탁드릴께요. 😄

2022-05-22 04:13 UTC, yongdae commented on src/main/java/qna/domain/qna/QnA.java
> +    protected boolean deleted = false;
QnA라는 객체가 하는 역할이 크게 없다고 생각되요. :)

2022-05-22 04:13 UTC, yongdae commented on src/main/java/qna/domain/qna/answer/Answer.java
> +    public DeleteHistory delete() {
Answer의 delete()도 매개변수로 User를 받게 만들어보면 어떨까요?

2022-05-22 04:13 UTC, yongdae commented on src/main/java/qna/domain/AbstractEntity.java
> +    public DeleteHistory createDeleteHistory(ContentType contentType, User writer) {
AbstractEntity가 DeleteHistory의 의존성을 가져야 할 필요가 있을까요?
DeleteHistory 클래스를 활용하는게 더 좋을 것 같아요. :)

2022-05-22 04:13 UTC, yongdae commented on src/main/java/qna/service/QnAService.java
> +        DeleteHistories deleteHistories = question.delete(loginUser);
👍

2022-05-22 04:13 UTC, yongdae commented on src/main/java/qna/domain/qna/question/Question.java
> +    public DeleteHistories delete(User loginUser) throws CannotDeleteException {
매개변수의 이름을 loginUser가 아니라 user을 쓴다면 더 좋을 것 같아요.

2022-05-22 04:13 UTC, yongdae commented on src/main/java/qna/domain/qna/question/Question.java
> +        }
이 부분도 함수로 분리해본다면 좋지 않을까요? 😄

2022-05-22 04:29 UTC, pangnem commented on src/main/java/qna/domain/qna/QnA.java
> +    protected boolean deleted = false;
> 3개 이상의 인스턴스 변수를 가진 클래스를 쓰지 않는다.
이 원칙 때문에 이렇게 분리한 것인데 좋은 방법은 아닌 것 같군요

2022-05-24 13:14 UTC, jxmen commented on src/main/java/qna/domain/AbstractEntity.java
> +    public DeleteHistory createDeleteHistory(ContentType contentType, User writer) {
id의 getter를 쓰는걸 최대한 피하려다 보니 AbstractEntity 까지 가게 된 것 같네요.

2022-05-24 15:46 UTC, pangnem commented on src/main/java/qna/domain/AbstractEntity.java
> +    protected Long id;
getter 사용을 최소화 하기 위해 question, answer에서 `this.id`로 바로 사용할 수 있도록 접근 제어자를 변경하였습니다.

2022-05-24 16:42 UTC, jxmen commented
Service -> Domain으로 로직 이동, 객체 분리 등 항상 테스트가 중복되게 되는데 어떻게 관리해야 될지 항상 고민이네요. 종종 새로 추가한 테스트는 성공하는데, 기존에 테스트가 실패하는 경우도 경험했기 때문이에요..

2022-05-24 23:31 UTC, pangnem commented on src/main/java/qna/service/DeleteHistoryService.java
>      }
getter를 안쓰기 위해 다음과 같은 형태로 작성해보았습니다. 저는 요즘 너무 getter를 안쓰려고 하는 강박도 있는 것 같아요. 기존 형태대로 쓰는 것도 나쁘지 않은 것 같네요.

2022-05-25 01:52 UTC, pangnem commented on src/main/java/qna/service/DeleteHistoryService.java
>      }
근데 이러면 이 `saveTo`메서드는 void형이고 테스트가 없습니다. 어떤걸 검증해야 할지 잘 모르겠네요.

2022-05-25 05:33 UTC, yongdae requested changes
의견 드린 부분을 잘 반영해주셨네요. 👍 

아직 Answer와 관련 된 부분이 반영되지 않은 것 같아 한번 더 의견을 드렸습니다.
확인하시고 다시 리뷰 요청 부탁드릴께요. 🔥

2022-05-25 05:33 UTC, yongdae commented on src/main/java/qna/service/DeleteHistoryService.java
> +        deleteHistories.saveTo(deleteHistoryRepository);
[질문](https://github.com/next-step/java-bowling/pull/817#discussion_r881134273)을 주셨는데 이 부분은 QnaServiceTest의 verifyDeleteHistories()를 통해서 검증되는 부분이 아닐까요? 🤔

2022-05-25 05:33 UTC, yongdae commented on src/main/java/qna/domain/answer/Answer.java
> +    public DeleteHistory delete() {
[이 피드백](https://github.com/next-step/java-bowling/pull/817#discussion_r878790001)이 반영되지 않은 것 같아요.

2022-05-25 05:33 UTC, yongdae commented on src/main/java/qna/domain/question/Question.java
> +    private void checkAnswerHasWrittenByOthers(User user) throws AnswerOtherWrittenException {
Answer가 삭제 기능에 User를 매개변수로 전달 받는다면 이 부분을 Answer로 옮겨 볼 수 있지 않을까요? 🤔

2022-05-25 05:33 UTC, yongdae commented on src/main/java/qna/domain/question/Question.java
> +    private void checkIsNotOwner(User user) throws DeleteQuestionPermissionException {
check 대신 validate 같은 이름을 사용해보면 어떨까요?

2022-05-25 05:33 UTC, yongdae commented on src/main/java/qna/domain/deleteHistory/DeleteHistory.java
> +    }
💯

2022-05-25 13:51 UTC, jxmen commented on src/main/java/qna/domain/question/Question.java
> +    private void checkIsNotOwner(User user) throws DeleteQuestionPermissionException {
validate란 단어가 꽤 맘에 드네요.

2022-05-25 16:00 UTC, pangnem commented on src/main/java/qna/service/DeleteHistoryService.java
> +        deleteHistories.saveTo(deleteHistoryRepository);
해당 부분에서도 검증이 되긴 하지만, 저는 도메인 클래스의 테스트 코드를 의미하는 것이였습니다.
[7b667aa](https://github.com/next-step/java-bowling/pull/817/commits/7b667aa45b2f2839b137dc501dec420dc0a3fd7a) 여기서 이렇게 작성해보았습니다.

다만 여기서까지 Mock을 써야한다는 것이 그닥 좋아보이지는 않은 것 같기도 하네요...

2022-05-26 04:22 UTC, yongdae approved these changes
의견 드린 부분을 잘 반영해주셨네요.

그럼 이번 단계는 여기서 마무리 하도록 하겠습니다.
리뷰한 내용은 다음 단계에서 반영해주시면 될 것 같습니다. 😄 

수고하셨습니다. 🙇

2022-05-26 04:22 UTC, yongdae commented on src/main/java/qna/service/DeleteHistoryService.java
> +        deleteHistories.saveTo(deleteHistoryRepository);
코드의 맥락은 데이터를 제어하지만 미션에서는 DB를 사용하지 않기 때문에 생기는 문제라고 생각하는게 좋을 것 같아요. 사실 그런 경우를 위해 Mock을 사용하기도 하고요.

2022-05-26 04:22 UTC, yongdae commented on src/test/java/qna/domain/question/QuestionTest.java
> +                assertThatThrownBy(() -> question.delete(UserTest.JAVAJIGI))
👍

2022-05-26 04:22 UTC, yongdae commented on src/main/java/qna/domain/answer/Answer.java
> +    private void checkAnswerWrittenByOthers(User user) {
이 메서드의 이름도 Question의 validateIsNotOwner()처럼 만들었으면 더 좋았을 것 같아요. :)

2022-05-26 04:22 UTC, merged