[Step04] 볼링 점수판(n명)
next-step/java-bowling pull request #831
Opened 2022-05-25 13:27 UTC by pbg0205

안녕하세요 리뷰어님 😄
CC-TDD Java 14기 박병기 입니다.
`볼링 점수판(n명)` 미션 완료하여 리뷰요청 드립니다.
진행한 작업 내용은 아래와 같습니다.

```
1. BowlingGames 객체 추가 및 n명의 게임을 위한 로직 구현
2. Running & Finish abstract class -> interface 변경
   - interface로 변경하다보니 Running과 Finish interface에 선언할 추상 메서드가 존재하지 않아 기존과 같이 State interface 에서 구현하는 방법으로 변경하였습니다.
```

소소한 피드백도 언제든 환영입니다!!!
항상 꼼꼼한 리뷰 감사드려요.
잘 부탁드립니다 🙏

2022-05-26 15:43 UTC, orgojy requested changes
안녕하세요. 병기님! 😄 
앞서 미션에서 잘 구현해주셨기 때문에,
이번 미션에서도 수월하게 좋은 코드를 보여주셨네요. 👍 
코멘트 몇 가지 남겼습니다.
마지막 미션이다보니 생각하시던 코드를 충분히 반영해주셔도 좋을 것 같습니다.
다시 요청 주시면, PR은 빠르게 머지하도록 할게요!

2022-05-26 15:43 UTC, yiminan commented on src/main/java/README.md
> +1. `BowlingGames` : 다수의 플레이어 볼링 게임을 관리하는 객체
단계마다 기능 요구 사항을 구분해서 잘 작성해주셨네요. 👍

2022-05-26 15:43 UTC, yiminan commented on src/main/java/bowling/domain/BowlingGames.java
> +    private final int LAST_PLAYER_TURN_INDEX;
인스턴스 필드는 자바 컨벤션으로 Lower Camel Case 를 활용해주시는건 어떨까요?
```suggestion
    private final int lastPlayerTurnIndex;
```

2022-05-26 15:43 UTC, yiminan commented on src/main/java/bowling/domain/BowlingGames.java
> +    }
매직 넘버를 가독성있게 바꾸어보는건 어떨까요? 😄 
<br/><참고자료><br/>[매직 리터럴(매직 넘버)을 다루는 법](https://orgojy.oopy.io/2e24b1bc-c412-4d58-8b76-1edb0cac49cc)

2022-05-26 15:43 UTC, yiminan commented on src/main/java/bowling/domain/state/finish/Miss.java
> +public class Miss implements State {
상속보다는 인터페이스로 더 좋은 방향성을 제시해주셨네요.
캡슐화에 있어서 더 좋은 방법이라고 생각합니다.
한 가지 아이디어를 공유드리면,
"상위 인터페이스 <- 하위 인터페이스 <- 구현체" 를 아이디어도 활용해보셔도 좋으실 것 같습니다.
예시로 Collection 링크 공유드릴게요! 😄 
<br/><참고자료><br/>[Java Collection을 사용할 때 다형성이 필요한 이유](https://velog.io/@woply/Collection-다형성-사용이유)

2022-05-26 22:34 UTC, pbg0205 commented on src/main/java/bowling/domain/BowlingGames.java
> +    }
앗! 변경하겠습니다 😅

2022-05-26 23:51 UTC, pbg0205 commented
안녕하세요 리뷰어님!
피드백 주셨던 내용 반영하여 다시 리뷰요청 드립니다 😃
아래에 하위 인터페이스를 구현하면서 했던 고민했던 내용에 대해 리뷰어님의 의견 궁금하여 아래 코멘트 남겼습니다.
확인 부탁드립니다. 🙏

### `1. 하위 인터페이스 피드백`

이전 피드백에서 언급주신 인터페이스를 변경하는 과정에서 Finish, Running이 빈 인터페이스로 사용되는 것 같아 이전의 State interface로 변경하였지만 언급해주신 `개발자의 의도를 분명히할 수 있는 장점`에서 비어있는 인터페이스를 분리하였습니다. 커밋 내역에 남아있는 `default method` 하위 메서드의 코드 중복을 줄이고자 하는 의도였습니다. 하지만 중복을 제거하기 위한 상속과 부모의 세부로직을 알고 있는 것은 부모 자식 간의 강한 결합을 초래하고 캡슐화를 위반하여 빈 인터페이스를 선언하고 구현체에서 로직을 구현하였습니다.
 사실 이전 코드 수정작업에서도 이 부분에 대해서 고민하다가 State 인터페이스로 하나로 묶었는데 제가 코드를 읽으면서 오히려 포괄적인 의미로 받아들여지고 이전에 비해 어색하게 느껴졌습니다.(이전 코드의 역체감인 것 같습니다.😅) 의미를 분명하게 하기 위한 비어있는 인터페이스 선언에 대해 리뷰어님은 어떻게 생각하지는지 의견 궁금합니다. 🤔

2022-05-27 12:14 UTC, orgojy commented
안녕하세요. 병기님! 😄 
하위 인터페이스로 마커 인터페이스를 활용하신 부분에 대한 질문을 해주셨네요!
이전에 리팩토링해주신 State를 구현하는 형태도 충분하다고 생각합니다.
하위 인터페이스로 마커 인터페이스 형태로 활용하는데에 조금 어색함을 느끼신 것 같습니다.
오히려 하위 인터페이스에 아무 추상 메서드가 없는 마커 인터페이스 형태로 활용된 부분에서 캡슐화 문제는 없구요.
그리고 타입별 구분을 통해서 견고한 코드를 구성할 수 있다고 생각합니다.
타입별 구분이 목적이라면, 이펙티브 자바에서도 적극 권장하고 있습니다.
충분한 답변이 될 지 모르겠네요. 그래서 참고 자료를 첨부드리겠습니다!
의문점이 있으시면, 언제든지 DM 주세요~! 😄 
<br/><참고자료><br/>[Effective Java Item 41. 정의하려는 것이 타입이라면 마커 인터페이스를 사용해라](https://dahye-jeong.gitbook.io/java/java/effective_java/2021-06-14-use-marker-interfaces-to-define-types)

2022-05-27 12:17 UTC, orgojy approved these changes
안녕하세요. 병기님.
이번 미션도 잘 구현해주셨네요. 👍 
미션 과정에 리팩토링도 잘 진행해주셔서 깔끔한 볼링 애플리케이션이었습니다.
마지막 미션까지 고생 많으셨습니다. 💯 
PR은 머지하도록 하겠습니다.

2022-05-27 12:17 UTC, merged