🚀 2단계 - 볼링 점수판(그리기)[younlll]
next-step/java-bowling pull request #832
Opened 2022-05-25 21:25 UTC by younlll

안녕하세요! 볼링 2단계 미션 완료해서  리뷰 요청드립니다. 😄
이번에도 잘 부탁드리겠습니다. 🙏

---

1. 처음에는 스트라이크, 스페어, 미스, 거터에 대한 상태 판단을 Enum으로 하려 했는데 분기가 늘어나다 보니 상태 패턴을 참고하여 구현하게 되었습니다.
2. 초반에 생각했던 도메인보다 많은 도메인들이 필요하게 되면서 많은 어려움이 있었네요... 😥
3. 구현 중 어려워서 힌트를 참고하게 되었습니다.
힌트에 NormalFrame과 LastFrame을 나누어 구현하라 되어있어 나누게 되었는데 하나의 클래스에서 10프레임인지 판단 후, 기능 구현을 하는 것과의 차이가 궁금합니다.
(10프레임의 경우, 두 번째 공을 던져 스페어 처리가 된 경우, 한번 더 볼링 공을 던질 기회를 얻기 때문에 이런 차이가 역할과 책임이 다르다고 판단되어 나누는 것인걸까요?)

---

1단계 완료 후, 브랜치 삭제 후, next-step과 동기화를 하지 않고 1단계 브랜치에 그냥 구현을 해버려서...
다시 구현하다보니 커밋 단위가 조금 커졌습니다. 😥

2022-05-26 14:50 UTC, vagabond95 requested changes
볼링 게임이 정말 어려운 도메인인데, 정말 깔끔하게 잘 구현해주셨네요 👍 

테스트 코드만 보고서도 비즈니스로직을 잘 유추할 수 있었습니다 ㅎㅎ
상태 패턴도 잘 적용해주신 것 같아요.

구현해주신 내용 중 개선해보면 좋을 점들에 대해 간략히 남겼는데요, 확인 후 리뷰요청 부탁드리겠습니다~!

2022-05-26 14:50 UTC, vagabond95 commented on src/main/java/bowling/view/OutputView.java
> +    private static final String BOWLING_SCORE_BOARD_FRAME = "| NAME |  01  |  02  |  03  |  04  |  05  |  06  |  07  |  08  |  09  |  10  |";
문자열 상수화 👍

2022-05-26 14:50 UTC, vagabond95 commented on src/main/java/bowling/view/OutputView.java
> +    public static void printBowlingScoreBoard(BowlingGame bowlingGame) {
BowlingGame 전체를 넘기기보다 print 에 필요한 필드만 넘겨주는 것은 어떨까요?

2022-05-26 14:50 UTC, vagabond95 commented on src/main/java/bowling/domain/Frame.java
> +    String symbol();
symbol() 은 어떻게 '표현'되어야 할지에 대한 메소드 이므로 도메인 인터페이스에는 적절하지 않을 것 같아요!

2022-05-26 14:50 UTC, vagabond95 commented on src/main/java/bowling/domain/Pitching.java
> +    public boolean isStrike() {
state 패턴을 사용하셨으므로

이러한 상태를 체크하는 메소드는 각 state 에서 판단하는 것은 어떨까요~?

pitching 이 각 state 에 엮이게 되면 점점 복잡도가 높아질수도 있을 것 같아요.

2022-05-26 14:50 UTC, vagabond95 commented on src/main/java/bowling/domain/LastFrame.java
> +public class LastFrame implements Frame {
질문 주신 내용에 대한 제 생각을 남겨보자면, 남겨주신 내용이 맞다고 생각합니다. ㅎㅎ

LastFrame 은 기존의 Frame 과는 다르게 처리되어야하는 비즈니스 로직이 있고, 이것을 NormalFrame 에서 if 문을 통해 구현할 수 도 있지만 역할을 분리하여 관리하면 유지보수 및 확장에 좀 더 용이하기 때문에 클래스를 나누는 가이드를 주셨다고 봅니다!

2022-05-27 12:24 UTC, younlll commented on src/main/java/bowling/view/OutputView.java
> +    public static void printBowlingScoreBoard(BowlingGame bowlingGame) {
필요하지 않는 정보를 domain 객체를 통해 전부 넘겨주는 것보다 리뷰어님 피드백대로 필요한 정보만 넘겨주는 것이 좋을 것 같습니다! 👍

2022-05-27 23:04 UTC, younlll commented on src/main/java/bowling/domain/Frame.java
> +    String symbol();
인터페이스는 객체가 할 수있는 행위가 모여있는건데 거기에 표현이 들어가있는게 적절하지 않다고 하신게 맞게 이해한걸까요??

2022-05-27 23:17 UTC, younlll commented on src/main/java/bowling/domain/Pitching.java
> +    public boolean isStrike() {
Pitching이 State를 실제로 갖고 있지 않게 때문에 엮여있다고 생각하지 않았는데 단순히 피칭한 결과 쓰러진 핀의 갯수가 10개인지 비교해서 방금 볼링 공을 던진 결과 피칭의 상태는 스트라이크가 True야라고 알려주는거라고 생각했습니다.
이 부분에 대해 리뷰어님 의견이 궁금합니다.

2022-05-28 02:48 UTC, vagabond95 commented on src/main/java/bowling/domain/Frame.java
> +    String symbol();
인터페이스의 정의는 적어주신 내용이 맞다고 생각합니다 ㅎㅎ

다만, 도메인에서 다루는 인터페이스에서 '어떻게 표현될지'에 대한 행위를 다루는 것이 적절할지 고민해보면 좋겠다는 의도였습니다 ㅎㅎ 
도메인을 '어떻게 표현할 것'인지에 대한 요구사항이 바뀌었을때, 그것이 도메인 코드의 변경으로 이어진다면 View 와 Domain 의 경계가 모호해질 수 있을 것 같아서요~!

도메인과 view 를 잇는 enum 성격의 클래스를 따로 두는 것도 방법일 수 있겠습니다 ㅎㅎ

2022-05-28 02:50 UTC, vagabond95 commented on src/main/java/bowling/domain/Pitching.java
> +    public boolean isStrike() {
넵 얘기 주신 것처럼 pitching 이 각 상태를 판단하는 것도 적절한 방향이라고 볼 수 있다고 생각합니다 ㅎㅎ 가지고 있는 상태를 이용하여 비즈니스 로직을 구현한 것이니까요!

다만, 제 개인적인 경험으로는 도메인 마다 계층이 존재한다고 하면 (좀더 구체적인 것, 추상적인 것) 구체적인 도메인이 추상적인 도메인의 비즈니스 로직에 의존할 경우 재사용성이 조금 어려웠던 경험이 있어 코멘트를 남기게 되었습니다 ㅎㅎ 
여기서 제 기준으로는 state 는 좀 더 추상적인 것(high level), pitching 은 구체적인 것(low level) 이라는 생각이 들었구요. 이 부분은 정답은 없으므로 하나의 관점으로 봐주시면 될 것 같습니다 :)

2022-05-28 02:51 UTC, vagabond95 approved these changes
피드백 빠르게 반영해주셨네요 👍 

질문 주신 내용에 대해서는 하위 코멘트로 남겼습니다 :) 더 궁금하거나 논의하고 싶은 점 있으시면 편하게 DM 주세요 ㅎㅎ
2단계는 머지하도록 하겠습니다~!

2022-05-28 02:51 UTC, merged