[볼링 점수판 - OOP] 2단계 - 볼링 점수판(그리기)
next-step/java-bowling pull request #834
Opened 2022-05-26 13:24 UTC by ch0213

안녕하세요 준보님! 단계를 착각해서 점수 계산을 같이 해버렸습니다 😅
이번 단계도 잘 부탁드립니다.

2022-05-27 13:01 UTC, simjunbo requested changes
@ch0213 리뷰이님 미션 너무 너무 잘 구현해주셨습니다.
상태 패턴도 잘 구현해 주셨네요 👍

전체적으로 구조를 잘 잡아 주셔서 구조에 대해서는 크게 리뷰 드릴 부분은 없으나
toString에 대한 부분을 중점으로 리뷰 드렸으니 확인 후 수정 부탁드립니다.

2022-05-27 13:01 UTC, aiden-sim commented on src/main/java/bowling/BowlingApplication.java
> +                break;
예외 처리로 종료를 시키는게 조금 어색해 보이는데 
flag로 제어해 보는것은 어떻게 생각하시나요 ?! 🤔

2022-05-27 13:01 UTC, aiden-sim commented on src/main/java/bowling/domain/Board.java
> +    public String toString() {
현재 toString을 출력에 대한 용도로 사용하고 있는데
출력에 대한 메소드를 다르게 분리해 보는것은 어떨까요 ?! 🤔 

참고) https://hudi.blog/java-correct-purpose-of-tostring/

2022-05-27 13:01 UTC, aiden-sim commented on src/main/java/bowling/domain/Score.java
> +            throw new IllegalArgumentException("[ERROR] 남은 횟수는 " + MIN_COUNT + "~" + MAX_COUNT + "사이여야 합니다.");
예외 메시지를 만들때 하드코딩말고 String.format을 이용해 보면 좋을것 같네요 😄

2022-05-27 13:01 UTC, aiden-sim commented on src/main/java/bowling/domain/User.java
> +        validateName(name);
null에 대한 값도 같이 체크해보면 좋을것 같습니다 😄

2022-05-27 13:01 UTC, aiden-sim commented on src/main/java/bowling/domain/frame/Frames.java
> +        List<Frame> frames = new LinkedList<>();
인스턴스 변수와 이름이 같아서 실수소지가 생길 것 같은데
로컬변수명을 분리해 보는것은 어떨까요 ?! 🤔

2022-05-27 13:01 UTC, aiden-sim commented on src/main/java/bowling/domain/frame/Frames.java
> +            result.append(format)
이 부분도 출력에 대한 역할인것 같은데 상태를 분리해서 처리해 보는것은 어떨까요 ?! 🤔

2022-05-27 13:01 UTC, aiden-sim commented on src/main/java/bowling/domain/frame/LastFrame.java
> +        return 10;
의미있는 상수로 도출해 봅시다 😄

2022-05-27 13:01 UTC, aiden-sim commented on src/main/java/bowling/domain/frame/LastFrame.java
> +            throw new GameOverException("[INFO] 게임 종료");
앞에서도 의견드렸지만 예외를 통해 비즈니스 로직 제어를 하는게 조금 어색해 보이네요.
별도로 분리해 볼 수 없을지 고민해 주세요 😄

2022-05-27 13:01 UTC, aiden-sim commented on src/main/java/bowling/domain/frame/LastFrame.java
> +    public String toString() {
전체적으로 toString 메서드를 출력 용도로 사용하고 있는데
별도 분리할 방법이 없을지 고민해 주세요.

2022-05-27 13:01 UTC, aiden-sim commented on src/main/java/bowling/domain/state/FirstBowl.java
> +        throw new IllegalArgumentException();
어떠한 이유로 예외가 발생되었는지 명시되어 있으면 좋을것 같습니다. 😄

2022-05-27 13:01 UTC, aiden-sim commented on src/main/java/bowling/domain/state/FirstBowl.java
> +    public boolean canCalculate(Score beforeScore) {
````

    @Override
    public boolean canCalculate(Score beforeScore) {
        beforeScore.bowl(firstPins);
        return beforeScore.canCalculate();
    }
````

IDE에서는 조금 더 간단하게 이런형태로도 제안을 하고 있네요 😄

2022-05-27 13:01 UTC, aiden-sim commented on src/main/java/bowling/domain/state/FirstBowl.java
> +    public String toString() {
이 부분도 toString을 사용하지 말고 별도 getMark 등의 메소드로 분리해 보는것은 어떨까요 ?! 🤔

2022-05-27 13:01 UTC, aiden-sim commented on src/main/java/bowling/domain/state/Miss.java
> +        beforeScore.bowl(secondPins);
````
        beforeScore.bowl(secondPins);
        return beforeScore.canCalculate();
````

이런 식으로도 처리해볼 수 있겠네요.

2022-05-27 13:01 UTC, aiden-sim commented on src/main/java/bowling/domain/state/Ready.java
> +        throw new IllegalArgumentException();
score와 이 부분도 사유를 같이 넣어주면 좋을것 같아요.

2022-05-27 13:01 UTC, aiden-sim commented on src/main/java/bowling/domain/state/Strike.java
> +        return new Score(10, 2);
이 부분도 상수로 도출해 보면 어떨까요 ?! 🤔

2022-05-27 13:01 UTC, aiden-sim commented on src/main/java/bowling/domain/state/State.java
> +public interface State {
상태 패턴을 잘 사용해 주셨네요 😄

2022-05-27 13:01 UTC, aiden-sim commented on src/test/java/bowling/domain/state/FirstBowlTest.java
> +        assertThat(firstBowl.canCalculate(new Strike().score())).isFalse();
조건이 여러개인 경우 assertAll 을 사용해 보면 어떨까요 ?! 🤔 

참고) https://it-mesung.tistory.com/45

2022-05-27 13:12 UTC, ch0213 commented
상세한 피드백 감사합니다! 반영한 후 다시 요청보내겠습니다 😄

2022-05-28 07:42 UTC, ch0213 commented on src/main/java/bowling/domain/frame/Frames.java
> +            result.append(format)
출력에 관한 메서드가 두 개로 (toString, score)로 분리되어 이 둘을 mark로 통합했습니다 😄

2022-05-28 09:09 UTC, simjunbo approved these changes
@ch0213 리뷰이님 피드백 잘 반영해 주셨습니다.
바로 머지 하겠습니다.
추가로 소소한 의견 남겨 놓았으니 다음 미션 시 같이 고민해 보시기 바랍니다. 😄 
그리고 step3 미션을 미리 같이해 주셨기 때문에 step4로 바로 넘어가도 좋을것 같습니다.

미션의 끝이 얼마 남지 않았습니다.
끝까지 화이팅 입니다 ❗❗❗

2022-05-28 09:09 UTC, aiden-sim commented on src/main/java/bowling/domain/Board.java
> +        StringBuilder stringBuilder = new StringBuilder();
@ch0213 
이 부분은 아직도 출력에 대한 역할로 보인은데요.
user.mark, frames.mark를 가지고 ResultView에서 처리해 보는것은 어떨까요 ?! 🤔

2022-05-28 09:09 UTC, aiden-sim commented on src/main/java/bowling/domain/Score.java
> +    public String toString() {
혹시 이부분은 아직도 toString 에서 출력 역할을 담당하고 있는것일까요 ?! 🤔

2022-05-28 09:09 UTC, simjunbo commented on src/main/java/bowling/domain/frame/LastFrame.java
> +        StringBuilder scores = new StringBuilder(SPACE);
이 부분도 일부는 ResultView의 역할 처럼 보이긴 하는데 어떻게 생각 하시나요 ?! 🤔 
score 계산한 하고 나머지는 View 처리 시켜 볼 순 없을까요 ?! 🤔 

LastFrame 이나 Board 등에서 출력 목적을 위해 StringBuilde로 데이터를 가공하는 것은 도메인 역할이 아니란 생각이듭니다.
최소한의 상태 정보를 넘겨서 View에서 처리해 보면 좋을것 같습니다.
리뷰이님 의견이 궁금합니다 🤔

2022-05-28 09:09 UTC, merged