[볼링 점수판 - OOP] 2단계 - 볼링 점수판(그리기)
next-step/java-bowling pull request #837
Opened 2022-05-26 17:57 UTC by Wu22e

안녕하세요 재석님! 볼링 게임 2단계 미션 구현 후 PR 드립니다!

지난번 리뷰 주신 null 리턴에 대해 Optional을 통한 처리를 진행하였습니다!

---

이번 볼링 미션은 정말 어려웠네요 ..

클래스 분리를 아무리 해도 볼링 게임의 복잡한 상태들을 로직으로 처리하려는 생각이 자꾸 들어서 힌트를 참고하여 인터페이스를 이용한 스테이츠 패턴을 적용하였습니다. (볼링 게임에서 일어날 수 있는 모든 경우의 수, 특히 코너케이스에 대한 처리를 계속 하다보니 늦어 졌습니다 .. ㅠㅠ)

이번 미션 리뷰 잘 부탁드립니다..!

2022-05-27 05:33 UTC, seok-2-o requested changes
다형성을 이용해서 멋지게 볼링 미션 진행해주셨네요.
몇가지 피드백 남겨드렸으니 확인 후 리펙토링 진행해보면 좋을 것 같아요 :) 
날씨가 많이 더워졌네요 늘 건강 유의하시고 즐거운 주말되시기 바랍니다.

2022-05-27 05:33 UTC, seok-2-o commented on src/main/java/bowling/README.md
> +## 기능 목록
세세한 기능 정의 👍

2022-05-27 05:33 UTC, seok-2-o commented on src/main/java/bowling/domain/BowlingGame.java
> +    public static BowlingGame create(Player player) {
정적팩토리 메소드  👍

2022-05-27 05:33 UTC, seok-2-o commented on src/main/java/bowling/domain/frame/NormalFrame.java
> +    private final FrameNumber frameNumber;
FrameNumber 는 어떨때 사용되나요?

2022-05-27 05:33 UTC, seok-2-o commented on src/main/java/bowling/domain/frame/NormalFrame.java
> +        return frameState instanceof BeforeProgress;
`instanceof` 보다 `state.isStrike()` 처럼 객체에게 물어보는것은 어떨까요?

2022-05-27 05:33 UTC, seok-2-o commented on src/main/java/bowling/domain/frame/NormalFrame.java
> +        return frameState.isFrameEnd();
state 에게 질의하는 것이기떄문에 FrameEnd 보다 더 적합한 메소드명은 없을까요?

2022-05-27 05:33 UTC, seok-2-o commented on src/main/java/bowling/domain/state/FirstBowl.java
> +public class FirstBowl implements FrameState {
다형성을 통해 상태를 잘 구현해주셨네요.
투구 가능한 상태와 투구 불가능한 상태를 한번 더 나눠보는것은 어떤까요?

2022-05-27 05:33 UTC, seok-2-o commented on src/main/java/bowling/domain/state/FirstBowl.java
> +    private void validateMaxHitPins(Pins hitPins) {
지금 구조라면 Pins이 검증할 수 있지 않을까요?

2022-05-28 23:17 UTC, Wu22e commented on src/main/java/bowling/domain/state/FirstBowl.java
> +    private void validateMaxHitPins(Pins hitPins) {
지금은 Pins에게 첫번째, 두번째 투구의 합이 10개를 넘는가? 에 대한 true / false값만 받아오고 검증은 FirstBowl에서 검증하는 형태인데,

아예 pins.validateMaxHitPins 와 같이 검증을 Pins로 위임하는 것을 말씀하시는걸까요?

2022-05-28 23:18 UTC, Wu22e commented on src/main/java/bowling/domain/frame/NormalFrame.java
> +        return frameState instanceof BeforeProgress;
해당 메서드가 현태는 사용되고 있지 않는 형태여서 제거하도록 하였습니다..! 피드백 감사합니다!

2022-05-29 00:10 UTC, Wu22e commented on src/main/java/bowling/domain/frame/NormalFrame.java
> +        return frameState.isFrameEnd();
상태 종료를 의미하기 때문에 Frame을 뺸 isEnd로 바꾸어 보았습니다..!

2022-05-29 00:32 UTC, Wu22e commented on src/main/java/bowling/domain/frame/NormalFrame.java
> +    private final FrameNumber frameNumber;
NormalFrame에서 다음 Frame을 반환할 때 프레임 넘버를 증가시키고, 마지막 프레임인지 확인하고 FinalFrame을 반환 하도록 하고있습니다!

2022-05-29 00:37 UTC, Wu22e commented
안녕하세요 재석님! 리팩토링 진행 후 리뷰 요청 드립니다!

마지막 Pins에 대한 검증 제가 생각한 것이 맞는지 궁금하네요. 맞다면 바로 적용하도록 하겠습니다!

2022-05-29 01:17 UTC, seok-2-o approved these changes
피드백 반영 정말 잘해주셨네요 👍 
피드백 반영사항에 따라 요구사항도 수정해주신것은 정말 좋네요 💯 
보통 신경쓰지 않게되는데 제가 하나 배운것 같습니다.

이어서 다음 미션진행해주세요.

2022-05-29 01:17 UTC, seok-2-o commented on src/main/java/bowling/domain/state/FirstBowl.java
> +    private void validateMaxHitPins(Pins hitPins) {
앗 제가 착각을 한것 같습니다. 지금 구조도 조습니다. 👍

2022-05-29 01:18 UTC, merged