[심성헌] - 2단계 - 볼링 점수판(그리기)
next-step/java-bowling pull request #845
Opened 2022-05-28 19:20 UTC by dip0cean

### 요구사항
- [X] 최종 목표는 볼링 점수를 계산하는 프로그램을 구현한다. 1단계 목표는 점수 계산을 제외한 볼링 게임 점수판을 구현하는 것이다.
- [X] 각 프레임이 스트라이크이면 "X", 스페어이면 "9 | /", 미스이면 "8 | 1", 과 같이 출력하도록 구현한다.
    - [X] 스트라이크(strike) : 프레임의 첫번째 투구에서 모든 핀(10개)을 쓰러트린 상태
    - [X] 스페어(spare) : 프레임의 두번재 투구에서 모든 핀(10개)을 쓰러트린 상태
    - [X] 미스(miss) : 프레임의 두번재 투구에서도 모든 핀이 쓰러지지 않은 상태
    - [X] 거터(gutter) : 핀을 하나도 쓰러트리지 못한 상태. 거터는 "-"로 표시
- [X] 10 프레임은 스트라이크이거나 스페어이면 한 번을 더 투구할 수 있다.
---
안녕하세요, 리뷰어님!
많이 늦었지만 볼링 점수판 미션 리뷰 요청드립니다!

다만 요구사항을 구현하면서 화면에 점수를 출력하기 위해 Pitches 클래스 내부에서 toString() 을 오버라이딩하여 출력 할 수 있도록 하고 있는데 이 부분이 좋은 방법인지 잘 모르겠습니다. 별도의 유틸성 클래스를 이용해서 (점수 Enum 같은) Frame 을 전달하여 점수판을 그릴 수 있도록 하는게 좋을지.. 리뷰어님은 어떻게 생각하시는지 궁금합니다!

2022-05-29 08:57 UTC, simjunbo requested changes
본격적인 볼링 미션이 시작되었네요.
미션 잘 구현해 주셨습니다 👍 

몇가지 리뷰 남겨 놓았으니 확인해 보시고 재요청 부탁드립니다!

**질문++)**
코멘트로 질문 주신 toString 에 대한 부분은 밑에 댓글에도 달아 놓았지만
출력용도로 사용하면 안된다고 생각합니다.
상태 패턴을 통해 구체적인 상태를 도출 후, 표식(X, /) 등을 제공해 보면 좀 더 간단하게 
나타내 볼 수 있지 않을까 생각되네요 😄 

**기타++)**
마지막 라운드 일때, 스트라이크와 스페어 처리가 정상적으로 처리 안되고 있는 것 같은데
같이 확인 부탁드립니다.

2022-05-29 08:57 UTC, simjunbo commented on src/main/java/bowling/controller/BowlingController.java
> +public class BowlingController {
여기도 생성자를 제어해서 외부에서 별도 인스턴스 생성하지 못하도록 처리해 보면 어떨까요 ?! 🤔

2022-05-29 08:57 UTC, simjunbo commented on src/main/java/bowling/domain/frame/FinalFrame.java
> +        if (pitches.isSpare()) {
볼링 핀에 상태를 현재는 pitch로 관리하고 있는데
이렇게 되면 isSpare, isStrike 등 여러 분기가 생길 것 같습니다.
상태 패턴을 이용해서 Strike, Spare, FirstBowl 등의 구체적인 상태를 
나타내 보면 해당로직들이 자연스럽게 각 상태별로 녹아들고, 점수 출력이나, 계산도 더 하기 쉽지 않을까 생각되네요.

꼭 이번 단계에서 반영하지 않아도 되니 상태패턴도 고려해 보시기 바랍니다.

참고) https://tecoble.techcourse.co.kr/post/2021-04-26-state-pattern/

2022-05-29 08:57 UTC, simjunbo commented on src/main/java/bowling/domain/frame/Frames.java
> +        int lastRound = Math.subtractExact(this.frames.size(), ONE);
이 부분은 제가 잘 몰라서 질문 드리는 것일 수도 있는데

````
return this.frames.size() - 1
````

대략적으로 이런식으로 간단하게 처리할 수도 있지 않나요 ?! 
Math 클래스를 사용하는 이유가 있을까요 ?! 🤔

2022-05-29 08:57 UTC, simjunbo commented on src/main/java/bowling/domain/game/Game.java
> +        OutputVIew.printGameInfo(player);
현재 도메인에 출력을 위한 부분이 결합되어 있습니다.
BowlingController 등에서 Player의 결과를 받아와서 OutputVIew 로 넘겨 보는 것은 어떨까요 ?! 🤔

2022-05-29 08:57 UTC, simjunbo commented on src/main/java/bowling/domain/game/Game.java
> +            int count = InputView.inputCount(this.frames.currentRound());
참고만 해주세요.
개인적으로 count 보다는 pins 등의 단어가 좀 더 직관적일 것 같네요 😄 
count의 원시값 포장 객체가 Pitch 가 맞죠 ?! 
좀 더 직관적으로 표현해 보면 좋을 것 같습니다.

2022-05-29 08:57 UTC, simjunbo commented on src/main/java/bowling/domain/game/Game.java
> +            OutputVIew.printGameResult(this.player, this.frames);
여기도 현재 도메인에 출력에 대한 부분이 결합되어 있습니다.
개인적으로 상태를 외부에 제공하는 것은 지양하지만, 단순 DTO나 View 에서 출력 용으로 정보를 제공하는 것은 변경에 대한 부수효과가 적기 때문에 괜찮다고 생각합니다. 😄

2022-05-29 08:57 UTC, simjunbo commented on src/main/java/bowling/domain/frame/exception/UnableBowlingException.java
> +public class UnableBowlingException extends RuntimeException {
상황에 맞는 사용자 예외를 잘 구현해 주셨네요 👍

2022-05-29 08:57 UTC, simjunbo commented on src/main/java/bowling/domain/pitch/Pitches.java
> +    public boolean isSpare() {
앞에서도 의견드렸지만 상태패턴을 이용하면 isStrike, isSpare 등의 로직이
구체적인 상태로 이동되기 때문에 좀 더 간단하게 처리해 볼 수 있을 것 같습니다. 😄

2022-05-29 08:57 UTC, simjunbo commented on src/main/java/bowling/domain/pitch/Pitches.java
> +    public String toString() {
리뷰이님은 toString의 용도로를 무엇이라고 생각하시나요 ?! 
toString을 출력용도로 사용하지 말고 별도 메서드로 분리해 보는것은 어떨까요 ? 🤔 

사실 이부분도 상태 패턴을 적용해 보면 각 상태에 따른 표식(mark)을 가지고 있을 수 있을 것 같네요.

참고) https://hudi.blog/java-correct-purpose-of-tostring/

2022-05-29 08:57 UTC, simjunbo commented on src/main/java/bowling/domain/player/Player.java
> +        checkNameLength(name);
static factory method에서 유효성 체크를 하는것보다 생성자에서 체크를 시키면
나중에 다른 static factory method가 추가된다고 해도 공통으로 사용할 수 있을 것 같은데 어떻게
생각하시나요 ?! 🤔

2022-05-29 08:57 UTC, simjunbo commented on src/main/java/bowling/domain/player/Player.java
> +                .filter(length -> length <= 3)
사소하지만 이런 부분도 상수로 처리되면 좀 더 가독성이 높아질것 같네요 😄

2022-05-29 08:57 UTC, simjunbo commented on src/main/java/bowling/view/OutputVIew.java
> +    private static final String FIRST_COLUMN = "| %s |";
```suggestion
    private static final String FIRST_COLUMN = "| %7s |";
```

사실 View에 대한 부분을 UI 영역이라고 생각해서 피드백을 잘 안드리긴 하는데
현재 출력에 대해서 좀 보기가 힘든것 같습니다.
공백을 추가해 보면 좀 더 가독성이 올라갈 것 같네요. 😄 
OTHER_COLUMN 쪽도 동일 합니다.

참고) https://blog.jiniworld.me/68

2022-05-29 08:57 UTC, simjunbo commented on src/main/java/bowling/view/OutputVIew.java
> +        IntFunction<String> indexFunc = i -> {
```
        IntFunction<String> indexFunc = i -> {
            int index = i + 1;
            return String.format("%02d", index);
        };
```

String.format을 이용해 보면 좀 더 간단하게 출력할 수 있겠네요 😄

2022-05-29 13:37 UTC, dip0cean commented
> 본격적인 볼링 미션이 시작되었네요. 미션 잘 구현해 주셨습니다 👍
> 
> 몇가지 리뷰 남겨 놓았으니 확인해 보시고 재요청 부탁드립니다!
> 
> **질문++)** 코멘트로 질문 주신 toString 에 대한 부분은 밑에 댓글에도 달아 놓았지만 출력용도로 사용하면 안된다고 생각합니다. 상태 패턴을 통해 구체적인 상태를 도출 후, 표식(X, /) 등을 제공해 보면 좀 더 간단하게 나타내 볼 수 있지 않을까 생각되네요 😄
> 
> **기타++)** 마지막 라운드 일때, 스트라이크와 스페어 처리가 정상적으로 처리 안되고 있는 것 같은데 같이 확인 부탁드립니다.

답변해주셔서 감사합니다!

2022-05-29 14:15 UTC, dip0cean commented on src/main/java/bowling/domain/frame/Frames.java
> +        int lastRound = Math.subtractExact(this.frames.size(), ONE);
@simjunbo 
int 범위를 벗어난 값인 경우 ArithmeticException 를 발생하기 때문에 사용했습니다!

2022-05-29 14:32 UTC, dip0cean commented on src/main/java/bowling/domain/pitch/Pitches.java
> +    public String toString() {
@simjunbo 
참고로 올려주신 아티클을 읽어보니 제가 사용하고자 하는 의도는 옳지 않는 방향이라는 것을 알게되었습니다! 
리뷰어님 말씀과 아티클 참고하여 메소드 분리 해보도록 하겠습니다ㅎㅎ☺️

2022-05-29 16:33 UTC, dip0cean commented on src/main/java/bowling/domain/game/Game.java
> +        OutputVIew.printGameInfo(player);
@simjunbo 
당시의 Game 클래스가 도메인으로써 책임을 지지 않는다고 생각해 View 부분과 결합 했었습니다..🥲
하지만 Game 클래스도 Player 와 Frames 의 속성과 이들의 상태를 가지고 있기 때문에 도메인 객체가 맞다고 생각됩니다.
가볍게 넘어갈 수 있었는데 체크해주셔서 감사합니다!

2022-05-29 16:39 UTC, dip0cean commented on src/main/java/bowling/domain/frame/FinalFrame.java
> +        if (pitches.isSpare()) {
@simjunbo 
참고로 남겨주신 아티클 잘 읽어봤습니다!
제가 작성한 구조에서 상태패턴을 적용할 아이디어가 잘 떠오르지 않아서 조금 더 고민해보고 해당 부분 고려하여 구현할 수 있도록 하겠습니다!

2022-05-30 01:09 UTC, simjunbo commented on src/main/java/bowling/domain/frame/FinalFrame.java
> +        if (pitches.isSpare()) {
@dip0cean 넵 다음 미션시, 좀 더 고민해 주세요 😄

2022-05-30 01:15 UTC, simjunbo approved these changes
피드백 잘 반영해 주셔서 빠르게 머지하겠습니다 💯 

![image](https://user-images.githubusercontent.com/7076334/170900381-0dd42b1b-8925-4410-a7e4-5a9be79c9b08.png)

추가로 마지막 프레임에서 연속 스트라이크 처리 시, 보너스 투구 및 출력에 대한 부분이 잘못된것 같은데
요 부분도 다음 미션 때 같이 확인 부탁드립니다 😄 

미션의 끝이 얼마 남지 않았습니다.
끝까지 화이팅 입니다 ❗❗❗

2022-05-30 01:15 UTC, simjunbo commented on src/main/java/bowling/controller/BowlingController.java
> +//        OutputVIew.printGameInfo(name);
의미 없는 주석은 제거해 주세요 😄

2022-05-30 01:15 UTC, merged

2022-05-30 01:23 UTC, dip0cean commented
> 

리뷰어님, 해당 부분 문제 체크해주셔서 감사합니다!
보너스 투구에 대한 스트라이크 또한 `X` 로 표현해야 하는 것 인가요?

요구사항에서
- 스트라이크(strike) : 프레임의 첫번째 투구에서 모든 핀(10개)을 쓰러트린 상태

라고 되어 있어 보너스는 첫 번째 프레임의 투구가 아니라고 생각해 `X` 로 표현하지 않았는데, 해당 부분은 다음 미션에서 수정할 수 있도록 하겠습니다!

2022-05-30 03:21 UTC, simjunbo commented
@dip0cean 
넵 맞습니다. 마지막 프레임은 보너스 투구시에도 X로 표현해 줘야 합니다.
그리고 연속 스트라이크 처리 시, 3번째 보너스 투구도 입력 받을 수 있도록 처리 부탁드립니다 😄