1단계 - 질문 삭제하기 기능 리팩토링
next-step/java-bowling pull request #911
Opened 2022-11-04 18:45 UTC by Yunsik-Choi

안녕하세요 준호님 마지막 볼링 점수판 미션 동안 잘 부탁드립니다 🙇‍♂️

추가적으로 미션 진행하면서 몇가지 의문점이 생겨 질문 남깁니다!

## 기능 목록
### 질문
- [x] 질문을 삭제한다
    - [x] 사용자와 질문자가 아닌 경우 CannotDeleteException 예외를 throw한다.
    - [x] 질문의 상태를 삭제 상태로 변경한다.
    - [x] 모든 답변의 상태를 삭제로 변경한다.
      - [x] 사용자가 답변자가 아닌 경우 CannotDeleteException 예외를 throw한다.
    - [x] 질문 삭제시 상태를 삭제 상태로 변경한다.
    - [x] 질문 삭제시 삭제이력을 남긴다.

### 답변
- [ ] 답변을 삭제한다.
    - [x] 사용자가 답변자가 아닌 경우 CannotDeleteException 예외를 throw한다.
    - [x] 답변 삭제시 상태를 삭제 상태로 변경한다.
    - [x] 답변 삭제시 삭제이력을 남긴다.

## 질문
- **클래스 내부에서 필드 사용**
하나의 클래스 내부에서 필드에 접근시 getter가 존재한다면 this로 접근하는 것과 getter 중 어느 것이 더 좋을까요?

- **public 메소드 테스트를 통한 private 메소드 테스트**
public 메소드를 통해 private 메소드를 테스트 하는 경우 
1. 다른 요소에 의해 테스트가 깨질 수 있다.
2. 테스트하고자하는 private메소드를 호출하지 않고 넘어갈 수 있다.
이 두가지 문제점이 발생할 수 있다고 생각합니다.
이를 해결할 수 있는 방법이 있을까요?

긴 글 읽어주셔서 감사합니다. 🙇‍♂️

2022-11-05 06:32 UTC, JunHoPark93 requested changes
안녕하세요~ 볼링 미션 만나서 반갑습니다 
꼭 같이 완주해보아요~
질문 주신 내용 답변 남겨두었으니 확인 부탁드려요 😊

2022-11-05 06:32 UTC, JunHoPark93 commented on README.md
> +    - [x] 답변 삭제시 삭제이력을 남긴다.
> 기능 목록을 너무 상세히 작성하면 안 된다는 글을 보았습니다.
> 저는 기능 목록이 상세히 작성하면 좋은 줄 알고 있어서 이 부분이 잘 이해가 가지 않아 준호님께 여쭙고 싶습니다.
> 추가로 제가 작성한 기능 목록은 적당한가요??

어디서 그런 글을 보신걸까요?
중요한 요구사항들을 잘 정리해주셨어요. 지금 작성해주신것 너무 좋습니다. 

아마 그 글의 의도가 너무 디테일한 개발 내용까지 다 쓰지말아라 아마.. 이런 내용이지 않을까 싶은데요, 요구사항이 수시로 바뀐다면 문서와의 sync가 맞지 않는 경우가 있는 단점이 있긴한데요. 저는 그럼에도 불구하고 업무할때는 문서화를 최대한 상세히 남겨놓는편이에요. 물론 기획자의 기획서가 있지만 개발자의 시선으로 작성한 문서도 꼭 필요하다고 생각해요. 만드는 사람이 수고로우면 그 뒤에 오는 사람은 그만큼 편해질 수 있습니다.

2022-11-05 06:32 UTC, JunHoPark93 commented on src/test/java/qna/domain/QuestionTest.java
> +import static org.assertj.core.api.Assertions.*;
> public 메소드 테스트를 통한 private 메소드 테스트
> public 메소드를 통해 private 메소드를 테스트 하는 경우
> * 다른 요소에 의해 테스트가 깨질 수 있다.
> * 테스트하고자하는 private메소드를 호출하지 않고 넘어갈 수 있다.
> 이 두가지 문제점이 발생할 수 있다고 생각합니다.
> 이를 해결할 수 있는 방법이 있을까요?

첫 번째 문제는 제가 잘 이해를 못해서요! 예시 혹은 부연설명 부탁드려요~

두 번째는 당연한 말이지만 private메서드를 호출하도록 코드를 작성하면 됩니다. 호출하지 않고 넘어가는 경우가 생긴다면 해당 public메서드가 너무 많은 일을 하고 있진 않은지 점검하고 로직을 나눠야합니다. 만약 public메서드가 단순한 구조로 private 메서드를 호출할지 말지 분기가 나눠진다면 테스트케이스를 추가하면 됩니다. 누락된다면 line coverage를 통해서 확인할 수도있구요.

2022-11-05 06:32 UTC, JunHoPark93 commented on src/main/java/qna/domain/Answer.java
> +    }
💡 질문을 삭제할 때 답변 또한 삭제해야 하며, 답변의 삭제 또한 삭제 상태(deleted)를 변경

질문 삭제할때 답변도 함께 삭제하는 로직이 들어가야 맞지 않을까요~?

2022-11-05 06:32 UTC, JunHoPark93 commented on src/main/java/qna/domain/Answer.java
> +    }
CannotDeleteException은 Runtime으로 변경하는건 어떨까요?

2022-11-05 07:36 UTC, Yunsik-Choi commented on src/test/java/qna/domain/QuestionTest.java
> +import static org.assertj.core.api.Assertions.*;
```
    public List<DeleteHistory> delete(User user) throws CannotDeleteException {
        validateWriter(user);

        setDeleted(true);

        List<DeleteHistory> answersDeleteHistories = deleteAllAnswers(user);

        return createDeleteHistories(answersDeleteHistories);
    }
```

만약 위 코드에서 `setDeleted(true);`에서 던지는 예외를 검증하려 했는데 `setDeleted(true);`가 호출되기 전 `validateWriter(user);`코드에서 예외를 던져 성공하는 테스트가 될 수도 있을 것 같아서 질문드렸습니다!

아래에서 답변해주신 내용에서 어느 정도 궁금증이 해결된 것 같습니다 😁

2022-11-05 07:44 UTC, Yunsik-Choi commented on src/main/java/qna/domain/Answer.java
> +    }
> CannotDeleteException은 Runtime으로 변경하는건 어떨까요?

이 이유는 다른 예외가 던져지거나 `CannotDeleteException`이 아닌 다른 예외로 변경될 수 있어서 그런 것 일까요?

2022-11-05 07:45 UTC, Yunsik-Choi commented
준호님 코멘트 주신 내용들 반영했습니다!!!

리뷰 부탁드립니다 🙏

2022-11-06 10:14 UTC, JunHoPark93 commented on src/main/java/qna/domain/Answer.java
> +    }
예외를 명시적으로 잡아서 처리해줘야해서요~ 어차피 계속 최상위로 던지고있어서 굳이 필요없지 않을까 싶어요.

2022-11-06 10:19 UTC, JunHoPark93 approved these changes
안녕하세요!
리뷰 반영하느라 고생많으셨습니다.
수정내용 코멘트는 남겨두었어요! 다음 step에서 뵙겠습니다!

2022-11-06 10:19 UTC, JunHoPark93 commented on src/main/java/qna/service/QnAService.java
> +    public void deleteQuestion(User loginUser, long questionId) throws Exception {
앗 Exception을 던지는게 아니라 기존 클래스가 RuntimeException을 extends하라는 의미였어요!
다음 step에서 수정부탁드려요. 혹시 이해가 잘안되면 dm주세요~

2022-11-06 10:19 UTC, merged