1단계 - 질문 삭제하기 기능 리팩토링
next-step/java-bowling pull request #923
Opened 2022-11-07 07:59 UTC by yeonsuyang

안녕하세요 리뷰 잘부탁드립니다~

2022-11-07 12:42 UTC, lowoon requested changes
안녕하세요 연수님!
1단계 잘 구현해주셨네요 👍 
코멘트 남겼으니 확인해 주세요ㅎㅎ

궁금한 점은 언제든지 DM이나 코멘트 남겨주세요 :)

2022-11-07 12:42 UTC, lowoon commented on src/main/java/qna/domain/Question.java
> +    private void isCanDelete(User loginUser) throws CannotDeleteException {
영어 문법에 맞지 않는 것 같아서요.
canDelete 혹은 isPossibleToDelete 가 맞을거 같아요.
근데 메서드가 하는 기능을 보면 검증인 것 같아 validate가 맞지 않을까요?

2022-11-07 12:42 UTC, lowoon commented on src/main/java/qna/domain/DeleteHistories.java
> +    public List<DeleteHistory> deleteHistories() {
getDeleteHistories인거 같아요. 메서드명만 보면 history를 지우는 동작인 거 같네요.

2022-11-07 12:42 UTC, lowoon commented on src/test/java/qna/service/QnaServiceTest.java
> -    private void verifyDeleteHistories() {
메서드에서 history를 삭제하는 로직이 있는데 history에도 정상적을 저장이 되었는지 확인을 해야하지 않을까요?

2022-11-07 12:42 UTC, lowoon commented on src/main/java/qna/domain/Question.java
> +        return new DeleteHistory(ContentType.ANSWER, questionId, this.writer, LocalDateTime.now());
기존의 기능과 다른 것 같아요.
`deleteHistories.add(new DeleteHistory(ContentType.ANSWER, answer.getId(), answer.getWriter(), LocalDateTime.now()));`

2022-11-07 13:43 UTC, yeonsuyang commented on src/main/java/qna/domain/Question.java
> +        return new DeleteHistory(ContentType.ANSWER, questionId, this.writer, LocalDateTime.now());
앗 실수하였네요 반영하였습니다.

2022-11-07 13:43 UTC, yeonsuyang commented on src/test/java/qna/service/QnaServiceTest.java
> -    private void verifyDeleteHistories() {
리턴이없는 메서드를 테스트하는 것보다는, 객체를 감싸는 것을 반영하는 것이 더 낫다고 판단하였었습니다. verify메서드로 다시 저장을 검증할 수 있도록 하였습니다.

2022-11-07 13:43 UTC, yeonsuyang commented on src/main/java/qna/domain/DeleteHistories.java
> +    public List<DeleteHistory> deleteHistories() {
객체명 자체가 그렇게 느껴지는 것 같아 deletedHistories로 변경하였습니다.

2022-11-07 13:44 UTC, yeonsuyang commented on src/main/java/qna/domain/Question.java
> +    private void isCanDelete(User loginUser) throws CannotDeleteException {
validate로 변경하였습니다!

2022-11-08 10:05 UTC, lowoon commented on src/main/java/qna/domain/DeleteHistories.java
> +    public List<DeleteHistory> deleteHistories() {
get을 붙이지 않는 이유가 있을까요?
의미상 get이 가장 명확한것 같아서요.

2022-11-08 10:12 UTC, lowoon approved these changes
안녕하세요 연수님!
코멘트반영 잘 해주셨네요 👍 
이만 1단계를 머지하도록 하겠습니다!
코멘트 남겼으니 확인해 주세요ㅎㅎ

궁금한 점은 언제든지 DM이나 코멘트 남겨주세요 :)

2022-11-08 10:12 UTC, lowoon commented on src/test/java/qna/service/QnaServiceTest.java
> -    private void verifyDeleteHistories() {
리턴이 없다고 하더라도 로직을 통해 테스트할 수 있다면 개인적으로는 테스트하는 것이 좋다고 생각합니다.
객체를 감싸는 것과 로직이 정상적으로 동작을 했는지에 대한 테스트는 다른 것이니까요.

테스트는 내가 작성한 코드가 내가 의도한대로 동작했는지 확인하는 작업입니다. 그렇다면 어디가 제대로 동작했는지, 확인하고 싶으신 부분을 생각해보시면 좋을거 같아요.

2022-11-08 10:12 UTC, lowoon commented on src/main/java/qna/domain/Question.java
> +        }
조금 더 도전한다면 anwser도 answers로 감싸도록 하고 해당 for문이 answers의 메서드가 되도록 할 수도 있을것 같아요.

2022-11-08 10:12 UTC, merged