Step1 : 질문 삭제하기 기능 리팩토링
next-step/java-bowling pull request #926
Opened 2022-11-07 13:47 UTC by sienna011022

안녕하세요 리뷰어님 😄
저는 김성윤이라고 합니다!
저는 아직 대학생이라 많이 부족합니다...!! 😢
최선을 다해 구현을 하였습니다! 세세한 피드백 부탁드립니다
감사합니다 ❤️

2022-11-08 10:34 UTC, gch01410 requested changes
안녕하세요! 볼링점수판 리뷰어 이도원입니다.
잘 부탁드리겠습니다!
간단한 피드백 남겼으니 확인 부탁드릴게요~

2022-11-08 10:34 UTC, ghost commented on src/main/java/qna/domain/Question.java
> +	}
메서드명이 is-로 시작하면 메서드의 반환값으로 boolean값을 기대합니다.
리턴타입이 void니 valid- 혹은 check- 등으로 네이밍하면 좋을것 같네요.

2022-11-08 10:34 UTC, ghost commented on src/main/java/qna/service/QnAService.java
> +		deleteHistories.deleteAnswerHistories(question);
답변을 삭제하는 로직을 질문을 삭제하는 로직안으로 넣어보면 어떨까요~?
질문이 삭제되면 답변도 삭제해야하므로 같이 처리하는게 어떨까합니다.

2022-11-08 10:34 UTC, ghost commented on src/test/java/qna/domain/QuestionTest.java
> +	}
테스트 코드에서만 사용하는 메서드를 만들어서 테스트 코드를 작성하는것은 지양해야합니다.
테스트 코드를 작성하는것의 의미를 고민해보면 좋을 것 같습니다.
프로덕션 코드에서 사용하는 메서드의 로직을 테스트 코드로 검증해봐야 하지않을까요~?

2022-11-08 13:30 UTC, sienna011022 commented on src/test/java/qna/domain/QuestionTest.java
> +	}
앗 validWriter() 대신 전에 만들어놓은 함수인데 지우는걸 잊었네요 ㅎㅎ

2022-11-09 11:13 UTC, gch01410 requested changes
안녕하세요!
추가 피드백 몇개 남겼습니다. 확인 부탁드릴게요!~

2022-11-09 11:13 UTC, ghost commented on src/main/java/qna/domain/Question.java
>  public class Question extends AbstractEntity {
클래스 내의 메서드 선언순서에도 자주 사용하는 컨벤션이 있습니다.

```java
public class Question extends AbstractEntity {

    1) static 메서드

    2) 생성자

    3) public 인스턴스 메서드 (getter, setter 아님)

    4) private 인스턴스 메서드

    5) getter, setter

    6) override 메서드(toString, equals, hashcode 등)
}
```

위 순서에서 3번과 4번을 구분하지않고 작성하기도 합니다. 
(public메서드에서 호출하는 private메서드를 public메서드 바로 아래에 위치)

2022-11-09 11:13 UTC, gch01410 commented on src/main/java/qna/domain/Question.java
> +    }
deleteAnswer 메서드는 Question 클래스 내에서만 호출되고 있어서 private으로 변경이 필요해보입니다!

2022-11-09 11:13 UTC, gch01410 commented on src/main/java/qna/domain/Question.java
>      }
이 메서드도 테스트 코드에서만 사용되고 있어서 삭제해주는게 좋아보입니다!

2022-11-09 11:13 UTC, gch01410 commented on src/test/java/qna/domain/QuestionTest.java
> +    }
Question의 delete 메서드에서 answer를 삭제하고 있으니, delete 메서드를 검증함으로써 answer가 삭제됐는지 확인해야하지 않을까요~?

2022-11-10 12:07 UTC, gch01410 requested changes
안녕하세요!
실패하는 테스트 코드 수정후에 다시 리뷰요청 부탁드리겠습니다!

2022-11-10 12:07 UTC, gch01410 commented on src/test/java/qna/service/QnaServiceTest.java
>  public class QnaServiceTest {
QnaServiceTest 가 실패하고 있네요!
수정 후 다시 리뷰요청 부탁드릴게요!

2022-11-12 00:54 UTC, gch01410 requested changes
안녕하세요!
이번에도 테스트 코드가 실패하네요 😢 
코멘트 남겼으니 확인부탁드릴게요~
궁금한점 있으시면 DM주세요~

2022-11-12 00:54 UTC, gch01410 commented on src/test/java/qna/domain/QuestionTest.java
> +    public static final Question Q2 = newQuestion(2L,"title2", "contents2").writeBy(UserTest.SANJIGI);
static으로 선언된 Question객체를 여러 테스트 메서드에서 사용하고 있는데요!
다른 테스트 메서드에서 Q1,Q2의 상태를 변경했다면 다른 테스트 메서드에서도 상태가 변경된 Q1,Q2를 사용하게 됩니다.
모든 메서드가 공유해서 사용하고 있기때문에 상태가 변경될 가능성이 있고, 예상했던것과 다른 결과가 나올 수 있습니다.
각 테스트 메서드는 서로 테스트 메서드에서 영향을 주지않고 받지도않으며, 독립적으로 실행되어야 합니다.

`@BeforeEach`가 붙은 메서드는 테스트 메서드들이 실행되기전에 매번 호출되고 있어서 여기서  Q1,Q2를 초기화하면 좋을 것 같습니다.

2022-11-12 00:54 UTC, gch01410 commented on src/test/java/qna/service/QnaServiceTest.java
> +        deleteQuestion.addAnswer(answer);
deleteQuestion이 갖고있는 Answer는 deleted값을 true로 셋팅해줘야하지 않을까합니다!

2022-11-12 00:54 UTC, gch01410 commented on src/test/java/qna/service/QnaServiceTest.java
> +        assertThat(Q1).isEqualTo(deleteQuestion);
Question, Answer 객체의 Equals 메서드 때문에 에러가 발생하고 있네요.
둘 중 하나의 Equals 메서드를 제거하거나 아예 둘다 제거하고 테스트 코드를 다시 작성해보는 것을 추천드려요!
DM으로 말씀드렸다시피 단순히 값(deleted)의 변화만 확인해도 충분히 괜찮습니다.

2022-11-14 02:30 UTC, gch01410 approved these changes
안녕하세요! 확인이 늦어 죄송합니다.
이번 단계는 여기서 머지하겠습니다.
다음 단계 진행해주세요~

2022-11-14 02:33 UTC, merged