🚀 Step2 - 볼링 점수판(그리기)
next-step/java-bowling pull request #927
Opened 2022-11-07 15:38 UTC by o3ozzvb

안녕하세요. 볼링 점수판 그리기 미션 제출합니다.

처음에 볼링 결과 상태값들을 enum 클래스로 구현하고 싶었는데,
각 상태값들이 가지는 변수가 달라 enum 클래스 구현에 어려움이 있어 추상클래스를 사용하는 방식으로 수정하였습니다.
이런 경우에는 Enum 클래스로 구현하는 것이 어려운 걸까요?

리뷰 잘 부탁드립니다. 감사합니다 !

2022-11-08 11:04 UTC, seokhongkim requested changes
은경님, 2단계 미션 잘 구현해주셨습니다. 👍 

질문 남겨주신 부분에 대해 제 생각 먼저 말씀 드립니다.
> 처음에 볼링 결과 상태값들을 enum 클래스로 구현하고 싶었는데, 각 상태값들이 가지는 변수가 달라 enum 클래스 구현에 어려움이 있어 추상클래스를 사용하는 방식으로 수정하였습니다.
이런 경우에는 Enum 클래스로 구현하는 것이 어려운 걸까요?

enum 의 각 값은 하나의 객체이므로, 상태를 가지는 객체는 enum 으로 표시하기에 적절하지 않다고 생각합니다. 싱글톤 패턴을 enum 으로 구현하는 코드를 학습해보시면 현재 패턴을 enum 으로 변경하기에 왜 어려운지 이해하시는데 도움이 될 것 같습니다.

코드를 보며 코멘트를 조금 남겼으니 확인 부탁드립니다. 🙏

2022-11-08 11:04 UTC, seokhongkim commented on README.md
> +## 볼링 게임 점수판 기능 요구사항
기능 요구사항 잘 정리해주셨습니다. 👍 
strike, spare, miss 의 경우 점수 계산 방법의 하위 목록인 것 같기도 하네요. 맞다면, indent 를 사용해서 계층 구조를 나타내주면 더 보기 좋을 것 같네요! :)

2022-11-08 11:04 UTC, seokhongkim commented on src/main/java/bowling/domain/Name.java
> +public class Name {
이름을 감싼 객체 사용 좋습니다. 👍

2022-11-08 11:04 UTC, seokhongkim commented on src/main/java/bowling/domain/Pin.java
> +public class Pin {
핀을 감싼 객체 사용 좋습니다. 👍 
`isStrike` 는 살짝 고민되는데, 첫 번째 투구에 10개의 핀을 넘기면 `strike` 지만 두 번째 투구인 경우 `spare` 라서 적절한 이름인지 고민이 되네요.

2022-11-08 11:04 UTC, seokhongkim commented on src/main/java/bowling/domain/frame/Frames.java
> +    public int getFramesSize() {
`getFrameSize` 는 이해하기 좋은 이름이지만 크기라는 구현의 관점에서 설명한 이름인 것 같기도 합니다.
이 메소드를 `현재 프레임이 몇 번째인지` 알려주는 기능으로 이름을 지어봐도 좋을 것 같아요.
코드를 읽을 때 1) `현재 프레임이 몇 번째인지` 가져와서 투구를 요청한다, 2) `프레임의 크기`를 가져와서 투구를 요청한다 라고 적었을 때 저는 1번 코드가 더 잘 읽히고 이해될 것 같다는 생각이 들었어요.

2022-11-08 11:04 UTC, seokhongkim commented on src/main/java/bowling/domain/frame/Frames.java
> +    public Frames addNextFrame(Frame frame) {
`Frames` 를 불변으로 유지하도록 결정하신 이유가 있을까요? :)
저는 `Frames` 가 볼링 한 게임을 관리하는 것으로 보여서, 다음 투구가 진행되거나 다음 프레임으로 넘어가더라도 `Frames` 는 동일한 게임이라고 생각이 들었어요. 그래서 `Frames` 는 게임 진행에 따라 상태가 변경되고, 게임 시작과 종료라는 상태가 있는 가변 객체가 아닐까 싶었습니다.
은경님께서 불변으로 만드신 이유가 궁금하고 같이 이야기 나눠보면 좋을 것 같네요!

2022-11-08 11:04 UTC, seokhongkim commented on src/main/java/bowling/domain/frame/NormalFrame.java
> +    public static final int LAST_FRAME_NO = 9;
상수를 public 접근 제어자로 관리하신 이유가 있을까요?

2022-11-08 11:04 UTC, seokhongkim commented on src/main/java/bowling/domain/frame/Frame.java
> +    Frame bowl(Pin pin) {
`bowl` 은 abstract method 로 만드시지 않은 이유가 있을까요?

2022-11-08 11:04 UTC, seokhongkim commented on src/main/java/bowling/domain/status/Status.java
> +public abstract class Status {
상태 패턴을 이용해 투구의 결과를 잘 관리해주셨네요. 💯

2022-11-08 11:04 UTC, seokhongkim commented on src/main/java/bowling/domain/frame/FinalFrame.java
> +    public FinalFrame(List<Status> statuses) {
내부에서만 호출된다면 접근 제어자를 private 으로 바꿔보면 어떨까요?

2022-11-08 11:04 UTC, seokhongkim commented on src/main/java/bowling/domain/frame/FinalFrame.java
> +        return new FinalFrame(statuses);
`NormalFrame` 처럼 this 를 반환하도록 구현하지 않으신 이유가 있을까요?
새로운 `FinalFrame` 을 만들어서 반환해도 현재 로직상 잘 동작하겠지만, 실제로 사용하지 않을 객체이며 이 `FinalFrame` 을 이미 존재하는 `FinalFrame` 과 비교하는 경우 문제가 될 수 있을 것 같아요!

2022-11-08 11:04 UTC, seokhongkim commented on src/main/java/bowling/view/FrameView.java
> +    private static String getFinalFrameContents(Frames frames) {
normal frame 에 대한 출력이 선행되니, 메서드의 배치 순서도 normal frame 에 대한 코드를 위로 올리면 어떨까요?

2022-11-08 11:04 UTC, seokhongkim commented on src/main/java/bowling/view/FrameView.java
> +        if (frames.getCurrentFrame().isFinalFrame()) {
early return 을 활용해서 indent 를 줄어보시면 좋겠습니다. :)

```suggestion
        if (!frames.getCurrentFrame().isFinalFrame()) {
            return "";
        }
```

2022-11-08 11:04 UTC, seokhongkim commented on src/main/java/bowling/view/FrameView.java
> +                            return STRIKE_MARK + BAR_MARK;
마지막의 `BAR_MARK` 대신 `Collectors.joining()` 의 인자로 `BAR_MARK` 를 전달해보면 어떨까요?
현재 코드만 봤을 때는 strike + miss 로 끝나면, `X|1|2|` 의 문자열이 만들어질 것 같기도 하네요.

2022-11-08 11:04 UTC, seokhongkim commented on src/main/java/bowling/view/FrameView.java
> +        contents.add(getFinalFrameContents(frames));
각 프레임별 contents 를 만드는 곳 내부에서 프레임과 프레임 사이의 `BAR_MARK` 도 만들어주면서 조금 더 복잡해지는 것 같기도 합니다.
contents 에서는 프레임 중간의 점수를 표시하는 것에 집중하고, 점수 틀을 만드는 것을 stream 과 `Collectors.joining()` 의 delimiter, prefix, suffix 인자를 이용해서 만들어보시면 좀 더 쉽게 표현할 수 있을 것 같습니다. :)

2022-11-08 11:04 UTC, seokhongkim commented on src/main/java/bowling/view/ResultView.java
> +public class ResultView {
`FrameView` 로 프레임 표시와 관련된 복잡한 로직을 분리해서 두 클래스 모두 너무 복잡하지 않도록 관리해주셨네요. 👍

2022-11-08 11:04 UTC, seokhongkim commented on src/test/java/bowling/domain/NameTest.java
> +class NameTest {
꼼꼼한 단위 테스트 작성 좋습니다. 👍

2022-11-08 11:04 UTC, seokhongkim commented on src/test/java/bowling/domain/NameTest.java
> +}
파일 마지막에 빈 newline 이 없다고 경고를 띄워주네요.
파일 마지막의 newline 은 왜 필요할까요? 학습하셨다면 IDE 설정을 이용해서 휴먼에러를 방지해보셔도 좋겠습니다.

2022-11-08 12:42 UTC, o3ozzvb commented on src/main/java/bowling/domain/frame/NormalFrame.java
> +    public static final int LAST_FRAME_NO = 9;
View 클래스나 외부 클래스와 공용으로 사용하고 싶어서 public으로 하였습니다. 
보통 상수는 private으로 선언하여 사용하나요??

2022-11-08 13:02 UTC, seokhongkim commented on src/main/java/bowling/domain/frame/NormalFrame.java
> +    public static final int LAST_FRAME_NO = 9;
저는 외부 클래스와 공용으로 사용할 필요가 없다면 private 으로 우선 만드는 것을 선호합니다. 경험상 private 으로 만든 후 필요한 시점에 public 으로 변경하는 것은 비용이 적었으나, public 으로 만들어서 외부에서 필요 이상으로 사용할 때 private 으로 변경하는 비용은 컸습니다.

2022-11-08 13:39 UTC, o3ozzvb commented on src/main/java/bowling/view/FrameView.java
> +        contents.add(getFinalFrameContents(frames));
Collectors.joining() 메서드로는 전체 문자열의 앞,뒤에만 문자열을 붙이는 게 가능한 것 같아 다른 방식으로 시도해보았습니다,,
더 나은 방법이 있다면 알려주세요 !

2022-11-08 13:40 UTC, o3ozzvb commented on src/main/java/bowling/domain/frame/Frame.java
> +    Frame bowl(Pin pin) {
아니요! 선언자가 누락되었네요 ㅠㅠ

2022-11-08 13:42 UTC, o3ozzvb commented on src/main/java/bowling/domain/frame/Frames.java
> +    public Frames addNextFrame(Frame frame) {
'불변 객체가 좋다' 라는 인식이 무의식에 내재되어 있었던 것 같습니다..
앞으로는 객체가 불변으로 사용이 될 지, 가변으로 사용이 될 지 한 번 더 고민해보고 코드를 작성해야 할 것 같네요... ㅎㅎ

2022-11-08 13:47 UTC, o3ozzvb commented on src/main/java/bowling/domain/frame/Frames.java
> +    public Frames addNextFrame(Frame frame) {
아..! 저는 외부에서의 무분별한(?) 변경을 막기 위해 불변객체 사용을 지향해야 한다고 생각했습니다..
불변 객체는 변함이 없을 객체에만 사용해야 하는 걸까요?

2022-11-08 23:52 UTC, seokhongkim commented on src/main/java/bowling/domain/frame/Frames.java
> +    public Frames addNextFrame(Frame frame) {
저는 어떤 값을 가지고 있는 객체(e.g., 나이, 금액)이면서 이 값이 달라졌을 때 다른 객체가 되는 경우(e.g., 1000원과 10000원은 다른 금액)에 불변 객체를 사용합니다.
상태를 가지고 있는 경우(e.g., 사람은 이름과 나이를 가지고 있음) 나이가 달라지더라도 같은 객체이므로 가변 객체로 표현하는 것이 더 적절하다고 생각합니다.

DDD에서는 특정한 값을 나타내는 경우 값 객체라고 하며, 라이프사이클을 가지고 있고 상태가 변할 수 있는 객체는 엔티티라고 하는 것으로 알고 있습니다. 저는 값 객체는 불변으로 구현하고, 엔티티는 가변으로 구현합니다.

2022-11-09 00:11 UTC, seokhongkim approved these changes
은경님, 2단계 코멘트 중 일부 내용 잘 반영해주셨네요!
미션 진행 기간이 얼마 남지 않아 2단계 PR 머지하도록 하겠습니다.

구조와 관련된 부분은 다음 단계를 진행하면서 더 고민해보시면 좋을 것 같고, 이외에 파일 마지막의 newline 은 학습하신 후 IDE 설정도 해보시면 은경님께 도움이 될 것 같습니다.

3단계 미션에서 뵙겠습니다. 😀

2022-11-09 00:11 UTC, seokhongkim commented on src/main/java/bowling/domain/Name.java
> +        if (name.length() != 3) {
3도 이름 길이의 제약조건임을 나타내는 상수로 선언해서 사용하시면 좋겠습니다. :)

2022-11-09 00:11 UTC, seokhongkim commented on src/main/java/bowling/domain/frame/Frames.java
> +    public int getCurrentFrameIdx() {
이 메서드는 내부에서 현재 인덱스를 가져오기 위한 용도로 사용하고, 현재 몇 번째 프레임이 진행중인지는 별도의 메서드로 분리해보셔도 좋을 것 같네요!
`getCurrentFrameNumber` 정도의 이름이 생각나네요.

2022-11-09 00:11 UTC, seokhongkim commented on src/main/java/bowling/domain/status/FirstBowl.java
> +    public boolean isFinished() {
`FirstBowl`, `Ready` 는 프레임이 진행중인 상태이고 `Strike`, `Spare`, `Miss` 는 게임이 끝난 상태이니 이를 나타낼 수 있는 추상 클래스를 추가해보셔도 좋겠네요! :)

2022-11-09 00:11 UTC, seokhongkim commented on src/main/java/bowling/view/FrameView.java
> +        contents.add(getFinalFrameContents(frames));
`contents` 에 들어 있는 값의 형태를 `_X__`, `_5|/`, `_7|-` (공백을 밑줄로 표시) 관리할 수 있다면, 프레임의 점수 부분은 아래와 같이 만들 수 있을 것 같네요.
```java
contents.stream()
    .collect(Collectors.joining(" | ", "| ", " |");
```

2022-11-09 00:11 UTC, merged

2022-11-10 05:44 UTC, o3ozzvb commented on src/main/java/bowling/domain/frame/Frames.java
> +    public int getCurrentFrameIdx() {
getCurrentFrameNumber 의 역할은 뭘까요..?

2022-11-10 12:08 UTC, seokhongkim commented on src/main/java/bowling/domain/frame/Frames.java
> +    public int getCurrentFrameIdx() {
인덱스는 0-based 값을 사용하고, 프레임 번호는 1-based 값을 가져온다는 차이가 있을 것 같습니다. :)

인덱스를 가져오는 것은 클래스 내부에서 편의를 위한 private method 로 사용한다면, 프레임 번호를 가져오는 것은 도메인 외부에서 호출할 때 `몇 번째 프레임`인지를 알 수 있도록 제공해주는 public method 가 될 수 있다고 생각합니다.

큰 차이는 없겠지만, 코드를 읽을 때 프레임 외부에서는 메서드 이름만 보고 '이 메서드는 몇 번째 프레임인지를 알려주는구나(= 1번부터 시작하겠구나)'라고 생각할 수 있고, 프레임 내부에서는 '이 메서드는 현재 진행중인 프레임의 인덱스(프레임 목록에서 현재 프레임을 가져오기 위한 값)을 제공해주는구나'라고 알 수 있을 것 같아요.

외부에서는 내부의 구현을 모르기에 (예를 들면, `List` 가 아니라 FirstFrame, SecondFrame, ..., NinthFrame, FinalFrame 으로 필드를 가지고 있을 수도 있죠) size / index 보다는 현재 진행중인 프레임이 몇 번인지에 관심이 있을거라고 생각했습니다. 한편, 내부에서는 구현을 알고 있으므로 `List` 에서 현재 진행중인 프레임을 조회하기 위해 `마지막 프레임 인덱스`를 가져오는 것이 필요할 거라고 생각했습니다.