2단계 - 볼링 점수판(그리기)
next-step/java-bowling pull request #930
Opened 2022-11-08 08:45 UTC by Yunsik-Choi

안녕하세요 준호님 2단계 구현 완료했습니다.

리뷰 부탁드립니다 🙏

추가로 1단계 코멘트로 남겨주신 CannotDeleteException을 Checked Exception에서 unchecked Exception으로 변경했습니다!

# 볼링 게임 점수판

## 기능 목록

## 도메인

<hr>

### 점수판

### 프레임

### 기본 프레임

- [x] 두 점수를 입력받는다.
    - [x] 첫 번째 점수와 두 번째 점수의 합이 10을 넘으면 IllegalArgumentException 예외를 throw 한다.

### 마지막 프레임

- [x] 세 점수를 입력받는다.
    - [x] 스트라이크가 아니고 첫 번째 점수와 두 번째 점수의 합이 10을 넘으면 IllegalArgumentException 예외를 throw 한다.

### 점수

- [x] 점수를 입력받는다.
    - [x] 0 ~ 10 이외의 숫자를 입력하면 IllegalArgumentException 예외를 throw 한다.
- [x] 스트라이크이면 true를 반환한다.

### 이름

- [x] 이름을 입력받는다.
    - [x] 3글자가 아니면 IllegalArgumentException 예외를 throw 한다.
    - [x] 영어가 아니면 IllegalArgumentException 예외를 throw 한다.

## 입출력

<hr>

### 입력

- [x] 플레이어 이름을 입력한다.
- [x] 점수를 입력한다.

### 출력

- [x] 점수판을 출력한다.

**출력 예시**

```
| NAME |  01  |  02  |  03  |  04  |  05  |  06  |  07  |  08  |  09  |  10  |
|  PJS |  X   |  8|/ |  7|- |      |      |      |      |      |      |      |
```

- [x] 점수를 출력한다.
    - 스트라이크면 “X”
    - 스페어이면 “9|/“,
    - 미스이면 “8|1”
    - 거터이면 “-“

2022-11-09 10:38 UTC, JunHoPark93 requested changes
안녕하세요~
볼링 2단계 잘 구현해주셨어요!
전체적으로 깔끔하게 잘해주셨는데요, 개선 포인트 몇가지 남겨두었으니 확인 부탁드려요 😊

2022-11-09 10:38 UTC, JunHoPark93 commented on src/main/java/qna/CannotDeleteException.java
> +public class CannotDeleteException extends RuntimeException {
잊지 않고 반영해주셨네요 👍

2022-11-09 10:38 UTC, JunHoPark93 commented on src/test/java/bowling/domain/RoundTest.java
> +    void isGameEnd_defaultFrame() {
테스트 깨지는 부분들 전체적으로 확인 부탁드려요 :)

2022-11-09 10:38 UTC, JunHoPark93 commented on src/main/java/bowling/domain/DefaultFrame.java
> +    }
보통 validation을 먼저하여 일찍이 error를 throw하는구조가 더 가독이 좋은데요, 순서를 바꿔볼까요?

2022-11-09 10:38 UTC, JunHoPark93 commented on src/main/java/bowling/domain/DefaultFrame.java
> +    }
함수를 잘 나눠주셨습니다 👍 가독도 정말 좋은거같아요~
지금구조도 정말 좋지만, scores를 포장하면 .get(0)등등의 로직도 개선할 수 있을거같아요!
남은 시간 고려해서 반영 부탁드려요~

2022-11-09 10:38 UTC, JunHoPark93 commented on src/main/java/bowling/domain/DefaultFrame.java
> +    }
개인적으로는 테스트를 위한 public 메서드를 지양하고있는데요, validation이 있긴하지만 실제 production 코드에서 사용되는 메서드를 통해서 테스트할 수 있게 만들어보면 어떨까요?

2022-11-09 10:38 UTC, JunHoPark93 commented on src/main/java/bowling/domain/LastFrame.java
> +    }
인터페이스를 활용해도 좋지만 공통된 기능에 대한 중복코드들이 발생하는거같아요~ DefaultFrame에도 같은 로직이 들어있는데 abstract class를 활용해서 공통된 기능에 대한 코드 중복을 없애보면 어떨까요?

2022-11-09 10:38 UTC, JunHoPark93 commented on src/main/java/bowling/domain/LastFrame.java
> +    public boolean isRemainChance() {
요 메서드만 서로 다르게 구현을 해주면 될거같네요

2022-11-09 10:38 UTC, JunHoPark93 commented on src/main/java/bowling/domain/ScoreValidator.java
> +public class ScoreValidator {
Scores 도메인이 만들어지면 validator로직도 간결해질거같아요!

2022-11-09 17:32 UTC, Yunsik-Choi reviewed
안녕하세요 준호님 코멘트 주신 내용들 모두 반영해보았습니다!
리뷰 부탁드립니다 🙏

코멘트 주신 내용을 반영하면서 몇가지 궁금한 점들이 생겨 질문 여쭙고 싶습니다 

1. ScoreValidator 로직 개선
Scores 도메인을 만들었는데도 ScoreValidator 로직이 간결해지지가 않네요 
준호님의 뜻을 완전 잘못 이해한 것 같기도 합니다 😂
만약 생각하신 방향과 다르다면 개선 방향을 알려주실 수 있을까요??

2. 패키지 분리
지금 domain 패키지를 보게되면 너무 많은 클래스가 있어 파악이 쉽지 않은 것 같습니다.
패키지를 분리하려고 찾아보았습니다.
그런데 하위 패키지가 상위 패키지를 참조하면 안된다는 내용이 있어 분리하지 못했습니다 😂
조언을 구할 수 있을까요??

나머지 질문들은 코드에 리뷰 형태로 남겨놓았습니다!

혼자 해결해보려 했지만, 답이 나오질 않아 질문이 너무 많네요. 죄송합니다 😅

긴 글 읽어주셔서 감사합니다 🙇‍♂️

2022-11-09 17:32 UTC, Yunsik-Choi commented on src/main/java/bowling/domain/ScoreValidator.java
> +        throw new IllegalArgumentException();
이렇게 여러 조건을 통과 후 에러를 던질 경우에는 validation을 일찍 하는 것이 힘들어보이는데 어떻게 생각하시나요??

2022-11-09 17:32 UTC, Yunsik-Choi commented on src/main/java/bowling/domain/Scores.java
> +    public static int sumScores(Score... scores) {
sumScores 메소드는 Score의 value를 꺼내 합을 구하는 메소드입니다.
이 메소드가 Scores랑 Score 중 어디에 위치하는 것이 맞을까요?
저는 Score 여러개를 다루기 때문에 Scores에 위치시켰습니다. 
그런데 사실 Scores 클래스에 의존하고 있지 않다고 생각이 들어 Score클래스로 옮겨야 하나 고민이됩니다 🤔

2022-11-09 17:32 UTC, Yunsik-Choi commented on src/main/java/bowling/domain/LastFrame.java
> +            return isRemainThirdTimeChance();
원래 LAST_FRAME_SIZE = 3 이라는 상수를 선언해 -1로 마지막 위치값을 가져와 사용하고 있었습니다.
하지만 메소드 이름에 Third라는 값을 포함하고 있어 만약 LAST_FRAME_SIZE 값을 4로 변경하면 2번째에서 검증해야 하지만 3번째에서 검증하게 되기 때문에 상수를 하드코딩하였습니다.
이러한 부분을 개선할 수 있을까요?

2022-11-09 17:32 UTC, Yunsik-Choi commented on src/main/java/bowling/domain/Scoreboard.java
> +    public static final int ROUND_END = 10;
원래는 ROUND 값을 전역 상수 클래스로 만들어 사용했습니다.

하지만 엘레강트 오브젝트에서 전역 상수를 선언하면 결합도가 높아지기 때문에 클래스별로 상수를 선언하는게 더 좋다고 하여 변경해보았습니다.

이렇게 하면 아래와 같은 문제점이 발생할 수 있다고 생각합니다.
1. 코드에 중복이 생긴다.
2. 10라운드에서 끝나야 하지만 9로 잘못 타이핑 하는 등 휴먼에러가 발생할 수 있다.
3. 라운드 정책 변경시 여러 클래스에서 변경해줘야한다.

더 좋은 방법이 있을까요?

2022-11-09 17:32 UTC, Yunsik-Choi commented on src/main/java/bowling/domain/Round.java
> +    private int round;
현재 Round는 불변클래스가 아닙니다.
Round를 불변클래스로 변환하게 되면 BowlingGame 객체에서 Round를 매번 재할당 해줘야 하는데
그렇게 되면 BowlingGame에 Round는 final로 선언이 불가능해 오히려 side effect가 발생할 확률이 더 클 것 같습니다.
불변클래스로 만들고싶은데 좋은 방법이 있을까요???

2022-11-10 16:18 UTC, JunHoPark93 commented on src/main/java/bowling/domain/Scores.java
> +    public static int sumScores(Score... scores) {
여러 score들의 합을 구하는것을 score에서 하는게 이상하지 않을까요?
다만 Score클래스에 add메서드를 만들면서 인자로 단일 score를 받게끔 하는건 괜찮아보여요~

2022-11-10 16:24 UTC, JunHoPark93 commented on src/main/java/bowling/domain/LastFrame.java
> +            return isRemainThirdTimeChance();
LAST_FRAME_SIZE가 4가 되면 isRemainThirdTimeChance() 가 아니라 isRemainFourthTimeChance()가 되지 않을까요?
 _2번째에서 검증해야 하지만 3번째에서 검증하게 되기 때문에 상수를 하드코딩하였습니다._ 이 말이 잘 와닿지가 않는데요, 부연 설명을 부탁드려요!

2022-11-10 16:29 UTC, JunHoPark93 commented on src/main/java/bowling/domain/Scoreboard.java
> +    public static final int ROUND_END = 10;
극단적으로 지켜보는것도 의미있다고는 생각해요. 이러한 미션들이 또 그런 극단적인 연습을 해보는것에 의의도 있구요. 그래서 저는 말씀주신 방법대로 해보는것도 적극 찬성입니다.

(이건 참고차 남겨요.
실용성이 떨어지는건 개인적으로 지양하고있습니다. 이미 이유를 잘 말씀해주셨는데요, 공통된 개념의 값을 여러 클래스에서 관리되고있을 때 정책이 변경된다면 문제가 발생할 수 있습니다. 사람이 수정을 하게 될텐데, 혹시나 분산되있는 값들 중에서 하나라도 수정을 안하게되면 치명적인 버그가 발생하게 됩니다)

답변이 되었을까요? 혹시 부족했으면 다시 말씀해주세요!

2022-11-10 16:39 UTC, JunHoPark93 commented on src/main/java/bowling/domain/Round.java
> +    private int round;
넵 현재 구조가 둘 다 만족할 수 가 없기 때문에 Round쪽의 메서드들에 대한 검증을 더 타이트하게 하는건 어떨까요?
초기화나 다음 라운드를 구하는 등의 메서드들에 검증을 추가로 넣어보아요!

2022-11-10 16:56 UTC, JunHoPark93 approved these changes
안녕하세요 리뷰 반영 잘해주셨어요!
많은 고민들을 해주셨네요 👍
질문에 대한 답들이 부족한게 있었다면 다시 말씀주세요~
이만 머지할게요. 다음 step에서 뵙겠습니다!

2022-11-10 16:56 UTC, JunHoPark93 commented on src/main/java/bowling/domain/ScoreValidator.java
> +        }
> ScoreValidator 로직 개선
> Scores 도메인을 만들었는데도 ScoreValidator 로직이 간결해지지가 않네요
> 준호님의 뜻을 완전 잘못 이해한 것 같기도 합니다 😂
> 만약 생각하신 방향과 다르다면 개선 방향을 알려주실 수 있을까요??

이런부분들도 validate하는것들을 추상메서드로 가져가게되면 instance of 들도 사라질 수 있지 않을까요?
Scores를 만들면 간결해진다는것들은 size == 2 이런 부분들처럼 일일이 밖에서 비교하는 행위들을 전부 명시적인 메서드들을 만들면 더 간결해진다는 의미였어요!

2022-11-10 16:56 UTC, JunHoPark93 commented on src/main/java/bowling/domain/ScoreValidator.java
> +package bowling.domain;
> 패키지 분리
> 지금 domain 패키지를 보게되면 너무 많은 클래스가 있어 파악이 쉽지 않은 것 같습니다.
> 패키지를 분리하려고 찾아보았습니다.
> 그런데 하위 패키지가 상위 패키지를 참조하면 안된다는 내용이 있어 분리하지 못했습니다 😂
> 패키지 분리에 관한 조언을 구할 수 있을까요??

관련 있는 group들끼리 묶어보면 정리가 될텐데요, 일단 다음 step에서 먼저 분리를 해보고 나서 이야기를 해보면 어떨까요?

2022-11-10 16:58 UTC, JunHoPark93 commented on src/main/java/bowling/domain/ScoreValidator.java
> +        throw new IllegalArgumentException();
조건을 통과를 못하면 throw하는 방식으로 하면 할 수 있지 않을까요?

2022-11-10 16:58 UTC, merged

2022-11-10 17:13 UTC, Yunsik-Choi commented on src/main/java/bowling/domain/ScoreValidator.java
> +        throw new IllegalArgumentException();
현재는 조건이 몇 개 없지만, 만약 조건이 많아지면 일찍 throw하는 방식이 힘들 것 같았습니다!

하지만 조건이 많아진다면 메소드를 분리하는 것이 맞는 것 같다는 생각이 들었습니다!

2022-11-10 17:18 UTC, Yunsik-Choi commented on src/main/java/bowling/domain/LastFrame.java
> +            return isRemainThirdTimeChance();
원래는 `LAST_FRAME_SZIE = 3` 이라는 상수가 존재하였고 `2`라는 값을 쓰기 위해 

`this.scores.size() == LAST_FRAME_SZIE - 1` 과 같은 방식으로 사용하였습니다!

여기서 만약 `LAST_FRAME_SZIE = 4`라는 값으로 변경하게되면 

size가 2일때 검증을 해야하지만 3일때 검증하게되는 부작용이 발생할 것 같았습니다!

그래서 이러한 문제를 해결하기 위해 
`this.scores.size() == LAST_FRAME_SZIE - 1` 

위 코드에서 상수를 포기하고 아래와 같은 코드로 변경했습니다!
`this.scores.size() == 2`

2022-11-12 02:03 UTC, JunHoPark93 commented on src/main/java/bowling/domain/LastFrame.java
> +            return isRemainThirdTimeChance();
넵 무슨 말씀이신지 이해했습니다~ 당연히 변경은 언제나 발생할수있지만 위에 말씀드린것처럼 변경으로 인해서 테스트가 깨질것이고 문제를 인지한 후에 코드를 수정하기 때문에 문제가 없다고 생각해요.