볼링 Step2
next-step/java-bowling pull request #936
Opened 2022-11-08 12:58 UTC by gumsu

안녕하세요 세윤님!
혼자 며칠간 구현해보다가 조금 지쳐서 PR 올려보았습니다.  😭

제일 어려웠던 부분이
1. 점수 결과판 출력 `- | 1`  `- | -` 불가
2. 10번 프레임 출력 😭
3. 10번 프레임
    - 스트라이크 3번일 경우 1, 2회차 각각 10개씩 20개의 핀이 필요 > 기존에 1 + 2회차 합쳐서 10개 핀인데 따로 구성해야 하는지 ? 궁금합니다.

2022-11-10 23:40 UTC, ksy90101 commented on src/main/java/bowling/BowlingApplication.java
> +        for (int i = 1; i < 11; i++) {
11을 상수로 빼서 차후에 유연하게 관리하는게 어떠신가요?

2022-11-10 23:44 UTC, ksy90101 requested changes
안녕하세요 :)
전체적으로 잘 구현해주셨네요 💯 
간단한 피드백을 남겼으니, 참고해주세요!

2022-11-10 23:44 UTC, ksy90101 commented on src/main/java/bowling/BowlingApplication.java
> +            if (i != 10) {
10도 상수로 뺴서 유연하게 관리하면 좋을듯 하네요!

2022-11-10 23:44 UTC, ksy90101 commented on src/main/java/bowling/BowlingApplication.java
> +        List<Frame> frames = new ArrayList<>();
Frame이라는 일급 컬렉션을 만들어서 처리하면 좀 더 main에 로직이 안들어 갈거 같네요!
Frames라는 일급컬렉션에서 최대한 처리하구요!

2022-11-10 23:44 UTC, ksy90101 commented on src/main/java/bowling/FinalFrame.java
> +        return false;
```suggestion
        return bonusPins != null || (secondPins() != 0 && getScore() != 10)
```

이런식으로 작성하면 좀 더 깔끔하게 의미 전달이 가능할수 있겟어요!

2022-11-10 23:44 UTC, ksy90101 commented on src/main/java/bowling/FinalThrown.java
> +        return true;
여기도 위와 같이 Boolean Expression으로 쓰면 더 좋을거 같아요!

2022-11-10 23:44 UTC, ksy90101 commented on src/main/java/bowling/FinalThrown.java
> +        }
맨 처음 값을 0으로 초기화 시켜두면 되지 않을까요?

2022-11-10 23:44 UTC, ksy90101 commented on src/main/java/bowling/Pins.java
> +    // TODO: 캐싱한 스태틱 메서드로 바꾸고 private 으로 변환하기
TODO를 진행했다면, 삭제해주세요!

2022-11-10 23:44 UTC, ksy90101 commented on src/main/java/bowling/Pins.java
> +            return "X";
매직스트링!

2022-11-10 23:46 UTC, ksy90101 commented
```
스트라이크 3번일 경우 1, 2회차 각각 10개씩 20개의 핀이 필요 > 기존에 1 + 2회차 합쳐서 10개 핀인데 따로 구성해야 하는지 ? 궁금합니다.
```
이부분에 대해서 이해를 잘 하지 못햇는데요 ㅠㅠ

10프레임에 스트라이크나 스페어가 나오면 공을 최대 3번 굴린다.

이러한 규칙으로 구현하는게 좋지 않을까 합니다 ㅎ

2022-11-11 11:56 UTC, gumsu commented
일반 프레임 -> 2번의 기회 안에 10개의 핀을 쓰러뜨린다.
10번 프레임 -> 2번의 기회 안에 스트라이크나 스페어면 추가 기회를 얻는다.
                            - 스페어인 경우 : 일반 프레임과 같이 2번의 기회 안에 10개의 핀을 쓰러뜨린다.
                            - 스트라이크인 경우 : 이미 10개 쓰러뜨림 + 2회차에 추가 10개의 핀이 새로 생김
10번 프레임이 스트라이크인 경우 2회차에 새로운 핀 10개가 생성되는데, 이럴 경우 기존 프레임과 같이 2회차 시도가 아닌 새로운 핀 생성으로 구현하는게 맞는지를 여쭤보았습니다.

2022-11-13 09:57 UTC, gumsu commented
안녕하세요 세윤님
제가 기존에 구현했던 로직들이 수정하기 너무 어려워서 처음부터 다시 구현해보았습니다~

2022-11-17 00:44 UTC, javajigi approved these changes
2단계 미션 진행하느라 수고했어요. 💯 
처음부터 다시 구현하다니 대단한 열정이네요. 👍 
이 미션의 핵심은 3단계인데요.
오늘 강의 마지막 날이지만 이후에도 리뷰 요청 가능하니 포기하지 말고 3단계  도전해 보세요.

2022-11-17 00:44 UTC, merged