Step2 : 볼링 점수판 (그리기)
next-step/java-bowling pull request #950
Opened 2022-11-10 14:35 UTC by Parkyunhwan

안녕하세요~

Out in 방식으로 작은 객체부터 프로그램을 만들려고 해보았는데 어렵네요.

한 프레임 당 여러 개의 볼링 기록을 가질 수 있는데 이걸 관리하고 출력하는 부분에서 많이 막혔던 것 같습니다.

출력과 실행하는 부분에 있어서도 하드코딩 되어 있는 부분과 객체로 분리시키지 못한 부분이 많은 것 같습니다. 
계속 고민하다가 볼링기록출력을 어떻게 관리해야할지감이 잘 오질 않아 PR을 드립니다.

저번에 피드백 주셨던 (https://github.com/next-step/java-bowling/pull/938) 부분이 잘 이해가 되지 않아 다시 질문을 남겼습니다.

감사합니다.☺️

2022-11-11 13:43 UTC, JunHoPark93 requested changes
안녕하세요~ 볼링 미션 구현하느라 고생많으셨습니다.
피드백 몇 가지 남겨두었는데요, 확인 후 의견 및 반영 부탁드려요!

2022-11-11 13:43 UTC, JunHoPark93 commented on src/main/java/bowling/App.java
> +            int count = InputView.hitCount(frameNumber + 1);
1부터 시작하게하는게 가독에 좋지 않을까요?

2022-11-11 13:43 UTC, JunHoPark93 commented on src/main/java/bowling/Frame.java
> +        return clearAllFrame() || hitTwice();
투구를 해서 핀을 쓰러트려도 false인 경우가 나오는 함수인데요, 개선을 해보면 어떨까요?

2022-11-11 13:43 UTC, JunHoPark93 commented on src/main/java/bowling/BowlingScoreRecord.java
> +        return frameNumber;
hitBowlingPin함수 구조때문에 상위까지 전개가 잘 읽히지 않는거같아요. hitBowlingPin를 개선하면 이 부분도 개선될것같아요~

2022-11-11 13:43 UTC, JunHoPark93 commented on src/main/java/bowling/Frame.java
> +    private static final int HIT_COUNT = 2;
상수명이 어색한데 바꿔보면 어떨까요?

2022-11-11 13:43 UTC, JunHoPark93 commented on src/main/java/bowling/view/OutputView.java
> +            if (index == 0 && hitRecord.hitAll()) {
> 출력과 실행하는 부분에 있어서도 하드코딩 되어 있는 부분과 객체로 분리시키지 못한 부분이 많은 것 같습니다.
> 계속 고민하다가 볼링기록출력을 어떻게 관리해야할지감이 잘 오질 않아 PR을 드립니다.

일단 Frame에 현재 상태를 질의하는 메서드를 만들면 로직이 조금 더 줄어들 것으로 보이는데요, 어떤 방식으로 먼저 접근하셨을까요? 작성해주신 로직에서는 HitRecord의 리스트만을 필요로 하는데요, 일단 이 메서드에서 frame을 받는 부분을 먼저 제거해보아요. 하나씩 뜯어내면 개선점을 찾아볼 수 있으실거에요!

2022-11-11 13:43 UTC, JunHoPark93 commented on src/main/java/bowling/BowlingScoreRecord.java
> +    public int hit(int frameNumber, int count) {
그리고 구조가 ScoreRecord가 hit를 받고 내부에서 frame을 꺼내오는데요, 점수기록은 frame으로 부터 나와야하지 않을까요?

2022-11-12 18:23 UTC, Parkyunhwan commented
안녕하세요! 리뷰어님

주신 피드백 보고 힌트를 얻어 코드 리팩터링을 진행해보았습니다. 마지막 프레임에 보너스로직도 빼먹어서 추가해두었습니다! 😀

마지막 프레임의 보너스 로직을 추가하다보니 '보너스에서 STRIKE, SPARE 등을 판단하는 로직'과 '일반 판단 로직'이 겹치게 되어 `Frame#hitBowlingPin` 메서드 로직이 복잡하게 된 것 같습니다.

이러한 부분은 
List<hitRecord>를 일급컬렉션을 빼서 로직을 나누고 일반Frame과 마지막Frame객체를 따로 둬서 로직을 나누는 게 좋을까요?

좋은 리뷰 항상 감사합니다!  😀

2022-11-13 13:58 UTC, JunHoPark93 approved these changes
안녕하세요!
2단계 피드백 반영하느라 고생많으셨습니다.
구조 관련해서 남겨주신것 코멘트 달아두었는데요,
다음 step에서 개선해보면 좋을거같아요 👍

2022-11-13 13:58 UTC, JunHoPark93 commented on src/main/java/bowling/Frame.java
> +    }
`return hitRecords.stream().anyMatch(records -> !records.hitAll());
`대략 이런식으로 줄여볼수도있을것같아요~

2022-11-13 13:58 UTC, JunHoPark93 commented on src/main/java/bowling/Frame.java
> +    }
> 마지막 프레임의 보너스 로직을 추가하다보니 '보너스에서 STRIKE, SPARE 등을 판단하는 로직'과 '일반 판단 로직'이 겹치게 되어 Frame#hitBowlingPin 메서드 로직이 복잡하게 된 것 같습니다.
> 이러한 부분은
> List를 일급컬렉션을 빼서 로직을 나누고 일반Frame과 마지막Frame객체를 따로 둬서 로직을 나누는 게 좋을까요?

넵 한번에 너무 많이 말씀드리면 부담이 되어 요번 step에서 말씀을 안드렸었는데요, 말씀주신것처럼 분리가 필요해보입니다. 문제점을 잘 찾아주셨네요 👍
말씀주신대로 나누게 되면 겹치는 기능들이 생길텐데요, 중복이 발생하지 않게끔 개선해보면 좋을거같아요~ 다음 step에서 진행해보면 어떨까요?

2022-11-13 13:58 UTC, JunHoPark93 commented on src/main/java/bowling/Frames.java
> +    public FrameNumber pitchingLast(FrameNumber frameNumber, int hitCount) {
Frame구조를 개선하면 마지막 투구를 위한 메서드도 중복이 제거될거에요!

2022-11-13 13:59 UTC, merged