🚀 Step3 - 볼링 점수판(점수 계산)
next-step/java-bowling pull request #951
Opened 2022-11-10 14:45 UTC by o3ozzvb

안녕하세요. 
2단계 피드백 반영과 3단계 볼링 점수판 구현해보았습니다.
아직 많이 부족하지만... 피드백 잘 부탁드립니다!

2022-11-11 12:47 UTC, seokhongkim requested changes
은경님, 3단계 미션 잘 구현해주셨습니다. 👍 
`Spare`, `Strike` 상황일 때 복잡한 스코어 계산을 위해 `Score` 객체를 추가하신 후, 구현해보신 것 좋습니다.

조금 더 확인해주시면 좋을 것 같은 부분에 코멘트 남겼으니 확인 부탁드립니다. 🙏

2022-11-11 12:47 UTC, seokhongkim commented on README.md
> +* 10 프레임은 스트라이크이거나 스페어이면 한 번을 더 투구할 수 있다.
스트라이크인 경우 2회, 스페이어인 경우 1회 투구가 가능한 것으로 알고 있습니다. :)
혹시 제가 잘못 알고 있는 부분이라면 말씀해주세요!

2022-11-11 12:47 UTC, seokhongkim commented on src/main/java/bowling/domain/Name.java
> +    public static final int NAME_LENGTH = 3;
상수 사용 좋습니다. 👍 
내부에서만 사용하는 값이라면 private 접근 제어자를 사용해보면 어떨까요? 에러 메시지도 private 으로 변경해도 될 것 같네요!

2022-11-11 12:47 UTC, seokhongkim commented on src/main/java/bowling/domain/frame/FinalFrame.java
> +        if (statuses.get(0) instanceof Strike && statuses.get(1) instanceof Strike && statuses.get(2) instanceof Strike) return true;
마지막 프레임에서 스트라이크, 스트라이크인 경우 마지막 투구가 스트라이크가 아니면 계속 던질 수 있을 것 같네요!

2022-11-11 12:47 UTC, seokhongkim commented on src/main/java/bowling/domain/frame/Frame.java
>      public abstract Boolean isFinalFrame();
null 값을 허용해야 하는 상황이 없을 것 같으니 primitive type 을 사용해보면 어떨까요?

2022-11-11 12:47 UTC, seokhongkim commented on src/main/java/bowling/domain/Score.java
> +    public Score addScore(Score nextScore) {
`Score` 계산 과정에 오류가 있는 것으로 보이네요.
`Spare` 인 경우 다음 1프레임이 아닌, 1투구의 점수를 더해야 합니다.

게임을 실행했을 때 1프레임에서 `Spare`, 2프레임을 5/5 개로 마치는 경우, 1프레임의 점수는 15점이 되어야 하는데 20점이 됩니다.
`Strike` 의 계산에서도 2투구의 점수를 더해야 하는데, 2프레임의 점수를 더하는 것으로 보입니다. 1프레임에서 `Strike` 이후 2 프레임에서 2/5, 3프레임에서 `Strike` 를 만들면 1프레임은 27점, 2프레임은 7점으로 계산됩니다.

아래 내용을 참고하셔서 점수 계산을 다시 확인해보시면 좋겠습니다. :)
> http://sports.koreanpc.kr:9000/sports_follow/sub/bowling/bowling_1_04_02.asp?naviNum=2

2022-11-11 12:47 UTC, seokhongkim commented on src/main/java/bowling/domain/status/Finished.java
> +public class Finished extends Status {
`Finished` 상태는 `Miss`, `Spare`, `Strike` 의 공통 부분을 가지며 실제 상태로는 사용할 수 없어야 할 것 같아요.
abstract 클래스로 만들고, `getScore` 는 실제 구현 클래스에서 구현하도록 남겨놓는 것이 어떨까요?

2022-11-11 12:47 UTC, seokhongkim commented on src/main/java/bowling/view/FrameView.java
>  package bowling.view;
각 상수에 대한 접근 제어자 및 사용 여부를 확인해보시면 좋을 것 같네요! :)

2022-11-11 12:47 UTC, seokhongkim commented on src/test/java/bowling/domain/frame/FinalFrameTest.java
> +
아래 테스트 케이스를 추가하신 후 `FinalFrame` 의 `isFinished` 로직을 수정해보시면 좋겠습니다. :)

```java
    @Test
    void isFinished_true5() {
        FinalFrame frame = FinalFrame.init();
        frame.bowl(new Pin(10));
        frame.bowl(new Pin(10));
        frame.bowl(new Pin(5));
        assertThat(frame.isFinished()).isTrue();
    }
```

2022-11-11 12:47 UTC, seokhongkim commented on src/test/java/bowling/domain/frame/FramesTest.java
> +    void bowl2() {
이 테스트에서 프레임별 스코어에 대한 검증도 함께 해보시면 좋겠습니다. :)

2022-11-11 13:52 UTC, o3ozzvb commented on README.md
> +* 10 프레임은 스트라이크이거나 스페어이면 한 번을 더 투구할 수 있다.
음 해당 내용은 nextstep 미션 기능 요구사항에 기재된 내용이에요!

2022-11-11 15:04 UTC, o3ozzvb commented on README.md
> +* 10 프레임은 스트라이크이거나 스페어이면 한 번을 더 투구할 수 있다.
네 제가 볼링규칙을 헷갈렸네요 ㅠㅠ

2022-11-12 09:46 UTC, seokhongkim approved these changes
은경님, 3단계 미션 코멘트 잘 반영해주셨습니다. 💯 
3단계 PR도 이만 머지하도록 하겠습니다.

코멘트 조금 남긴 내용은 4단계 미션을 진행하시며 고민해보셔도 좋겠습니다.
4단계 미션에서 뵙겠습니다. 😀

2022-11-12 09:46 UTC, seokhongkim commented on src/main/java/bowling/domain/frame/FinalFrame.java
>      @Override
`RuntimeException` 보다는 예외 상황을 더 잘 표현해줄 수 있는 구현체를 사용해보시면 좋을 것 같아요.
상태에 관한 예외이니 `IllegalStateException` 을 사용ㅇ해도 괜찮을 것 같습니다. :)

2022-11-12 09:46 UTC, seokhongkim commented on src/main/java/bowling/domain/status/Finished.java
> +public abstract class Finished extends Status {
`FirstBowl` 과 `Ready` 상태는 진행중이니, 진행중 상태를 나타내는 `Ongoing` 과 같은 추상 클래스도 추가해보셔도 좋겠습니다. :)

2022-11-12 09:46 UTC, seokhongkim commented on src/main/java/bowling/domain/frame/FinalFrame.java
>          return false;
`FinalFrame` 의 `isFinished` 로직이 점점 복잡해지는 것 같네요.
다음 단계를 진행하시며 이 부분을 리팩토링할 수 있는 방법이 있을지 고민해보셔도 좋겠습니다. :)

지금 드는 생각은 `FinalFrame` 에서 `Strike`, `Spare` 인 경우 스코어 계산을 위해 추가 투구를 진행하겠네요. 그렇다면 `Strike`, `Spare` 의 공통 속성인 점수 계산을 위해 다음 투구가 필요하다는 내용을 이용해서, `FinalFrame` 에서 투구수가 남았는지 알 수 있을 것 같습니다.

2022-11-12 09:46 UTC, merged