Step4
next-step/java-bowling pull request #952
Opened 2022-11-11 05:50 UTC by nooose

2022-11-11 07:00 UTC, nooose reviewed
-

2022-11-13 12:16 UTC, lxxjn0 requested changes
준혁님, 미션 진행하시느라 수고하셨습니다!!

크게 로직적인 부분에서 변경 사항은 없어서 크게 피드백을 드릴만한 부분이 없네요!! 간단한 부분에 대해서만 피드백 남겨두었으니 한 번 확인해보시고 반영 부탁드릴게요 :)

2022-11-13 12:16 UTC, lxxjn0 commented on src/main/java/bowling/controller/BowlingController.java
> +        List<Player> players = IntStream.rangeClosed(1, numberOfPlayers)
만약 numberOfPlayers의 크기만큼 반복을 하고 싶은거라면 `range(0, nubmerOfPlayers)` 같은 로직도 괜찮을 것 같아요!! for문이 index 0으로 시작하는 걸 기본 로직으로 가지고 있다보니 `range(0, nubmerOfPlayers)` 와 같은 코드가 좀 더 이해가 잘 가지 않을까?? 싶은 생각이 들어 남겨봤습니다!! ㅎㅎㅎ

이건 중요한 피드백은 아니고 저의 개인적인 생각이라 참고만 해주세요 :)

2022-11-13 12:16 UTC, lxxjn0 commented on src/main/java/bowling/controller/BowlingController.java
> +    private Players getPlayers() {
이 부분도 개인적인 의견이지만 get을 prefix로 쓰는 경우 보통 getter로 인식이 되다보니 저는 getter가 아닌 메서드에서는 get을 사용하는 걸 지양하는 편이에요. `generatePlayers()`나 `createPlayers()` 등 다른 이름을 사용해보는 것도 좋을 것 같아요!! 👍🏼

2022-11-13 12:16 UTC, lxxjn0 commented on src/main/java/bowling/domain/Score.java
> +    private final int value;
이 부분은 전 개인적으로 이전에 score가 더 좋은 것 같아요!! value라는 명은 특정 도메인의 필드를 나타내기에는 너무 범용적이고 모호한 단어가 아닐까 싶어요!! 중요한 부분은 아니기에 한 번 고민해보면 좋을 것 같아요!! 

`score.getScore()`는 Score 객체가 관리하는 score라는 값을 반환하는구나!! 라는 것을 알겠는데 `score.getValue()`는 어떠한 value인지 코드를 보지 않으면 명확히 식별이 안되는 것 같아서 아쉬웠어요

2022-11-13 12:16 UTC, lxxjn0 commented on src/main/java/bowling/domain/player/Name.java
> +        if (value == null || value.isBlank()) {
굿!! 👍🏼

2022-11-13 12:16 UTC, lxxjn0 commented on src/main/java/bowling/controller/BowlingController.java
>      }
여기에 있는 출력 로직을 상단 메서드로 옮기는 건 어떨까요?? 그렇다면 Players 파라미터를 받지 않아도 될 것 같아요!! bowl이라는 private 메서드에서 출력까지 담당한다라는 느낌으로 봐도 괜찮을 것 같아요!!

2022-11-13 12:16 UTC, lxxjn0 commented on src/main/java/bowling/controller/BowlingController.java
> +        for (Player player : players.getPlayers()) {
일급 컬렉션으로 감싼 객체를 다시 getter로 가져와서 로직을 진행하는 것이 '일급 컬렉션으로 사용하는 의미가 있는걸까?'에 대한 고민이 들긴 하네요.. 그런데 입출력 로직이 관여되어 있다보니 어쩔 수 없을 것 같아요 ㅠㅠ 콘솔 프로그램이라서 가지는 한계라는 생각은 들어서 아쉽지만 해당 부분을 개선하기는 어려움이 있을 것 같네요 ㅠㅠ

2022-11-13 13:04 UTC, nooose commented on src/main/java/bowling/controller/BowlingController.java
>      }
그렇네요! 감사합니다.

2022-11-13 13:09 UTC, nooose commented on src/main/java/bowling/domain/Score.java
> +    private final int value;
앗 그렇군요.
score 에서 또 getScore() 를 하다보니 스코어에서 또 스코어를 꺼낸다? 라는 느낌이 좀 이상해서 변경했었습니다.
이런 경우에는 변수명을 score로 두고 클래스명을 바꾸도록 해볼게요

2022-11-13 13:20 UTC, nooose commented on src/main/java/bowling/controller/BowlingController.java
> +        List<Player> players = IntStream.rangeClosed(1, numberOfPlayers)
<img width="366" alt="image" src="https://user-images.githubusercontent.com/36617783/201523535-b7287ddb-f7d9-452d-ba3f-624886c41a42.png">
위 사진 처럼 index가 1 부터 출력시키기 위해서 `IntStream.rangeClosed(1, numberOfPlayers)` 이렇게 사용하고 있는데요

답변 주신대로 `IntStream.range(0, numberOfPlayers)` 로 반복을 돌리고 index 를 따로 +1 증가시켜야 하는 걸까요?
제가 이 부분은 잘 이해를 못한 것 같습니다.😭

2022-11-13 13:27 UTC, nooose commented on src/main/java/bowling/controller/BowlingController.java
> +        for (Player player : players.getPlayers()) {
넵, 말씀주신대로 저도 공감하는 부분입니다..
드라마틱하게 느끼는 장점은 없지만
모든 플레이어들의 게임 종료여부 상태 체크, 중복 회원 체크만으로도 컨트롤러 내 코드가 많이 줄어들어 좋은 것 같습니다.

2022-11-13 13:34 UTC, nooose commented on src/main/java/bowling/controller/BowlingController.java
> +        List<Player> players = IntStream.rangeClosed(1, numberOfPlayers)
준영님의 의견은 사이즈만큼 반복시킬 때
range 메서드로 0 부터 Size 크기만큼 반복을 돌리는 것이 좀 더 이해하기 쉽다 라는 의미일까요?

저는 불필요하게 +1 을 할까봐 rangeClosed를 사용했었는데 
무조건 반복된 사이즈만큼 반복시키는 경우라면 range(0, size)로 범위를 확실히 보여주는 것도 괜찮은 방법이겠네요

2022-11-13 14:14 UTC, nooose commented on src/main/java/bowling/domain/Score.java
> +    private final int value;
Name 클래스와 Score 클래스에서도 value 라는 필드명을 사용했었는데요

리뷰어님 말씀대로 생각도해보니까 특정 객체가 관리하는 값을 반환한다는 의미가 있네요.
중복적인 표현같았었는데 이렇게도 생각할 수 있네요...

위 코멘트에서 클래스 명도 변경해보려고 했는데 FrameScore 는 Frame 이 중복적으로 들어가서 별로인 것 같구..
Point 도 생각해봤지만 Score 만 계속봐서 그런지 Score 가 더 자연스러운 것 같네요. 😅

변경하도록 하겠습니다.

2022-11-13 14:21 UTC, nooose commented on src/main/java/bowling/domain/player/Players.java
> +
일급 컬렉션의 경우에도 동일할까요?

저는 `getXXXs` 와 같이 값을 꺼낼 때 컬렉션이기 때문에 values 라는 값을 꺼내면 
해당 일급 컬렉션이 담고있는 객체들을 반환한다는 게 명확해 보일 수 있다고 생각합니다.
Enum 의 values() 처럼요!

리뷰어님의 의견이 궁금합니다.

2022-11-15 07:13 UTC, lxxjn0 commented on src/main/java/bowling/controller/BowlingController.java
> +        List<Player> players = IntStream.rangeClosed(1, numberOfPlayers)
제가 출력문에서 해당 인덱스를 사용하는 상황을 따로 인지하진 않았었네요 ㅠㅠ 그렇다면 작성해주신 로직도 충분히 좋다고 생각해요! 또는 제가 작성한 로직에서 +1을 하는 방법도 있겠지만 지금처럼 출력에서 활용을 한다면 준혁님 로직도 좋다고 생각합니다 :)

2022-11-15 07:19 UTC, lxxjn0 commented on src/main/java/bowling/domain/player/Players.java
> +
이 부분은 개인적인 의견의 차이일 것 같아요!! :)

enum의 경우 자바 자체에서 제공해주는 특별한 클래스 타입이고 values는 그러한 특정한 클래스에서 제공해주는 default 메서드이다보니 모든 사람들이 합의가 된 코드라고 생각해요. 

그러나 우리가 구현하는 Players와 같은 일급 컬렉션은 실제 내부 구현을 확인하지 않는 이상은 일급 컬렉션이라는 사실을 모를 것 같아요. 실제 코드의 내부를 봐야지 '아, 일급 컬렉션이라 필드가 컬렉션 타입으로 하나만 가지고 있으니깐 values라는 변수명을 준거구나'라고 이해할 수 있을 것 같아요!! 

물론 사실 내부 코드를 아예 안본다는 가정도 말은 안되고 일급 컬렉션에 한해서는 values라는 필드를 쓰는 것도 괜찮다고는 생각해요. 그러나 players로 표현하는 방법이 보기에 어색하다? 말고는 values에 비해 뚜렷하게 가지는 단점이 없다고 생각해서 저라면 players로 필드 명을 사용하고 getter도 동일한 형식으로 가지 않을까 싶어요. 

실제 변수명도 변수가 가지는 의미를 담아서 만들어야 하는데 Player 다수를 담는 컬렉션을 표현하기 위한 변수이므로 players도 적절한 변수명이라 생각하기도 하구요!!

그러나 이런 변수 네이밍은 어느정도 합의가 된다면 괜찮다고 생각해서 개인의 생각에 따라서 팀에서 이해가는 범위 안에 용어를 사용하면 충분할 것 같아요!!

2022-11-15 07:20 UTC, lxxjn0 approved these changes
준혁님, 미션 진행하시느라 정말 수고 많으셨습니다 👍🏼 

추가적인 피드백을 드릴만한 부분이 없는 것 같아서 이번 미션은 여기서 마무리하도록 할게요!! 고생 많으셨어요 :)

2022-11-15 07:21 UTC, merged

2022-11-15 12:05 UTC, nooose commented on src/main/java/bowling/domain/player/Players.java
> +
상세한 답변 정말 감사합니다!