Step2 - 2단계 - 볼링 점수판(그리기)
next-step/java-bowling pull request #953
Opened 2022-11-11 08:23 UTC by shineyuno

이번 미션 리뷰도 잘부탁드립니다. 
* step1  피드백 반영
* 2단계 - 볼링 점수판(그리기) 구현

2022-11-11 22:38 UTC, younlll requested changes
안녕하세요. 윤호님!

볼링 점수판 2단계 미션 하느라 수고하셨습니다~
몇 가지 코멘트 남겨드렸으니
확인 해주시고 다시 리뷰요청 부탁드립니다. 🙏

2022-11-11 22:38 UTC, younlll commented on README.md
> +  * [x] 미스(miss) : 프레임의 두번재 투구에서도 모든 핀이 쓰러지지 않은 상태
👍

2022-11-11 22:38 UTC, younlll commented on src/main/java/bowling/ui/InputView.java
> +            throw new RuntimeException("플렐이어 이름 세글자로 해주세요.");
```suggestion
            throw new RuntimeException("플레이어 이름 세글자로 해주세요.");
```

2022-11-11 22:38 UTC, younlll commented on src/main/java/bowling/BowlingMain.java
> +        String userName = InputView.inputPlayerName();
플레이어 이름 원시값을 포장해보는건 어떨까요?

2022-11-11 22:38 UTC, younlll commented on src/main/java/bowling/domain/Ball.java
> +    }
pitch를 호출 하는 곳에서 return 받은 값을 사용하지 않고 있네요~
void로 변경해주는건 어떨까요?

2022-11-11 22:38 UTC, younlll commented on src/main/java/bowling/domain/BowlingGame.java
> +    }
여기도 return 값을 활용하고 있지 않네요

2022-11-11 22:38 UTC, younlll commented on src/main/java/bowling/domain/Pins.java
> +        pinList.forEach(pin -> pin.knockDown());
```suggestion
        pinList.forEach(Pin::knockDown);
```
조금 더 간단하게 표현도 가능 할 것 같습니다.

2022-11-11 22:38 UTC, younlll commented on src/main/java/bowling/domain/Pin.java
> +    }
toString을 잘 활용해주셨네요. 💯👍
단, 사용하실 때 문자화에 대한 목적으로만 사용하는 것보다 디버깅과 같은 표준적인 사용을 고려하면 더 좋을 것 같습니다.
각 toString이 어떻게 작동하는지가 다 다르다고 하면 호출하는 입장에서 매우 곤란할 수도 있습니다.
보통은 컨벤션으로 출력형태를 고정시키기도 합니다.
다른, 클래스에 정의된 toString도 해당되는 이야기입니다.
참고 링크 공유드릴게요.
[이펙티브 자바 Item 12. toString을 항상 재정의하라](https://jake-seo-dev.tistory.com/m/29)

2022-11-11 22:38 UTC, younlll commented on src/main/java/bowling/ui/ResultView.java
> +        System.out.println(printText);
StringBuilder를 활용해보는건 어떨까요?

2022-11-11 22:38 UTC, younlll commented on src/main/java/bowling/domain/Frame.java
> +    public Frame(int round, int firstBallKnockedDownPinCount, int secondBallKnockedDownPinCount) {
매개변수의 갯수를 2개로 제한하고 미션을 진행해보죠!!

2022-11-11 22:38 UTC, younlll commented on src/main/java/bowling/domain/Frame.java
> +            List<Pin> addPins = PinGenerator.generate();
각 프레임별 투구를 자동생성 하는 것이 아닌 직접 입력받는 형식의 요구사항입니다! 😥

2022-11-11 22:38 UTC, younlll commented on src/main/java/bowling/domain/Frame.java
> +        this.pins = new Pins();
테스트에서만 호출하고 있는데 테스트를 위해서만 만들어진 생성자일까요?

2022-11-13 07:52 UTC, shineyuno commented on src/main/java/bowling/ui/InputView.java
> +            throw new RuntimeException("플렐이어 이름 세글자로 해주세요.");
앗 오타 아래 커밋에 수정하였습니다. 
13c7a13

2022-11-13 07:52 UTC, shineyuno commented on src/main/java/bowling/BowlingMain.java
> +        String userName = InputView.inputPlayerName();
아래 커밋에 수정하였습니다. 
13c7a13

2022-11-13 07:55 UTC, shineyuno commented on src/main/java/bowling/domain/Ball.java
> +    }
아래커밋에 반영했습니다.
d1f678a

2022-11-13 07:55 UTC, shineyuno commented on src/main/java/bowling/domain/BowlingGame.java
> +    }
아래커밋에 반영했습니다.
d1f678a

2022-11-13 07:55 UTC, shineyuno commented on src/main/java/bowling/domain/Pins.java
> +        pinList.forEach(pin -> pin.knockDown());
아래커밋에 반영했습니다.
d1f678a

2022-11-13 07:56 UTC, shineyuno commented on src/main/java/bowling/ui/ResultView.java
> +        System.out.println(printText);
StringBuilder 를 쓰라고 해주신 이유가 무엇인가요??

2022-11-13 07:57 UTC, shineyuno commented on src/main/java/bowling/domain/Frame.java
> +    public Frame(int round, int firstBallKnockedDownPinCount, int secondBallKnockedDownPinCount) {
int firstBallKnockedDownPinCount, int secondBallKnockedDownPinCount 를 묶어서 Balls객체로 받도록 수정했습니다.

2022-11-13 07:59 UTC, shineyuno commented on src/main/java/bowling/domain/Frame.java
> +            List<Pin> addPins = PinGenerator.generate();
직접... 입력받도록 하라는 요구사항 문구가 없어서... 그렇게 해야 하는 줄몰랐네요.  
입력받도록 수정했습니다.

2022-11-13 07:59 UTC, shineyuno commented on src/main/java/bowling/domain/Frame.java
> +        this.pins = new Pins();
네 테스트용 생성자 입니다.

2022-11-13 08:02 UTC, shineyuno commented
@younlll 
투구 입력값을 자동에서 직접 입력받는식으로 바꾸면서 힌트에 있는 아래 내용을 적용해서 구조를 변경하였습니다. 
* 1 ~ 9 프레임을 NormalFrame, 10 프레임을 FinalFrame과 같은 구조로 구현
* 현재 Frame에서 다음 Frame을 생성하는 방식으로 구현

2022-11-14 05:31 UTC, younlll commented on src/main/java/bowling/ui/ResultView.java
> +        System.out.println(printText);
비록 10회 연산이긴 하지만 문자열 + 연산 대신해 StringBuilder를 사용하면 어떨까라는 개인적인 의견이였습니다.

2022-11-14 05:45 UTC, younlll approved these changes
안녕하세요. 윤호님! 
피드백 반영 잘 해주시고 구현도 깔끔하게 잘 해주셨네요!!
몇 가지 의견 남겨드렸으니 확인 부탁드립니다~
이번 단계는 이만 머지하도록 하겠습니다.
다음 단계에서 뵙겠습니다!

2022-11-14 05:45 UTC, younlll commented on src/main/java/bowling/domain/FinalFrame.java
> +        if (balls.pitchedBallCount() < 3) {
매직넙버를 상수화 해주는건 어떨까요?

2022-11-14 05:45 UTC, younlll commented on src/test/java/bowling/domain/FrameTest.java
> +    }
메소드명에 카멜케이스와 스네이크케이스가 섞여있는데 카멜케이스로 맞춰주는건 어떨까요?

2022-11-14 05:45 UTC, merged