3단계 - 볼링 점수판(점수 계산)
next-step/java-bowling pull request #966
Opened 2022-11-14 04:10 UTC by jhwlim

안녕하세요. 3단계 리뷰 요청드립니다.

2022-11-14 23:47 UTC, seokhongkim requested changes
종환님, 3단계 미션 잘 구현해주셨습니다. 👍 
이번 단계는 코멘트 드릴 내용이 많지 않았네요.

`Frame` 과 `State` 사이의 순환참조를 어떻게 끊어낼 수 있을 것인지를 고민해보시면 도움이 될 것 같습니다. :)
코멘트 남긴 내용 확인 부탁드립니다. 🙏

2022-11-14 23:47 UTC, seokhongkim commented on src/main/java/bowling/domain/frame/AbstractBowlingGameFrame.java
>  public abstract class AbstractBowlingGameFrame implements BowlingGameFrame {
`BowlingGame` 은 이름에서 없어도 패키지와 프로젝트 내에서 이 클래스를 이해하는데 지장이 없을 것 같네요!

2022-11-14 23:47 UTC, seokhongkim commented on src/main/java/bowling/domain/state/BowlingGameHitState.java
> +    default boolean hasScore(BowlingGameFrame currentFrame) {
`BowlingGameFrame` 과 `BowlingGameHitState` 간의 순환참조를 없앨 수 있는 방법을 고민해보시면 좋겠습니다.

`State` 가 쓰러진 핀의 개수를 모르니, `Frame` 을 통해 핀의 개수에 접근하고 프레임의 상태를 물어보게 되는 것 같아요.
또한 `BowlingGameFrame` 은 `FinalBowlingGameFrame` 이 아니라면 하나의 상태를 가져도 되는데(=최종 상태를 통해 이전 상태를 알 수 있음) 리스트로 가지고 있어서 `State` 자체적으로 종료된 프레임인지 판단을 못 하는 것 같기도 합니다. :)

2022-11-14 23:47 UTC, seokhongkim commented on src/main/java/bowling/domain/state/BowlingGameHitState.java
> +        while (count < currentFrame.countHits() + getNumberOfBonus()) {
2단계 미션의 프로그래밍 요구사항을 지키기 위해 인덴트를 한 단계 줄여보시면 좋겠습니다.
> https://edu.nextstep.camp/s/DVVUSLFe/ls/l8jJozTD
규칙 1: 한 메서드에 오직 한 단계의 들여쓰기만 한다.

2022-11-14 23:47 UTC, seokhongkim commented on src/main/java/bowling/domain/state/BowlingGameHitState.java
> +            sum += frame.getHit(index++);
`frame` 에게 점수를 달라고 해보는 건 어떨까요? `frame` 이 점수 계산을 위해 필요하다면 다음 `frame` 에게 점수를 달라고 요청할 수 있을 것 같아요.
지금은 `BowlingGameHitState` 가 `Frame` 의 내부 구조를 자세히 알고 외부에서 `index` 를 통해 접근하는 것 같아요.

2022-11-14 23:47 UTC, seokhongkim commented on src/main/java/bowling/domain/state/Spare.java
> +        int remainedPins = BowlingGameFrame.MAX_NUMBER_OF_BOWLING_PINS - sum(hits) % BowlingGameFrame.MAX_NUMBER_OF_BOWLING_PINS;
마지막 프레임의 strike + spare 상황을 고려하다보니 로직이 복잡해지는 것 같네요. :)
이것도 프레임의 세부 구현에 의한 의존을 줄이는 방향을 고민해보시면 쉽게 풀어보는데 도움이 될 것 같습니다.

2022-11-15 12:25 UTC, jhwlim commented
피드백 주신 내용 참고하여 수정했습니다! 
- 클래스 네이밍 수정
- Frame과 State 간의 순환 참조 문제 해결 (점수 계산 로직 이동 포함)
- State의 Frame의 세부 구현을 의존하지 않도록 단순화

그런데 의견 주셨던 것처럼 일반 프레임은 최종 상태만 가지고 화면을 그릴 수 있지만, 마지막 프레임은 여러 개의 상태를 가질 수 있습니다. 문제는 프레임이 인터페이스 형태로 OutputView에서 메시지를 주고 받다보니, 만약 일반 프레임은 1개의 상태를 가질 수 있도록 세부 구현을 하고, 마지막 프레임은 여러 개의 상태를 가질 수 있도록 세부 구현을 하게 되면, OutputView에서 인터페이스가 아닌 각각의 NormalFrame, FinalFrame 클래스로 다운 캐스팅하여 출력 로직을 처리해야 할 것 같은데, 오히려 복잡해질 수 있다고 생각했습니다. 그래서 이 부분은 기존과 동일하게 각 투구에 대한 상태(결과)를 저장하도록 했습니다.

2022-11-15 13:15 UTC, seokhongkim approved these changes
종환님, 3단계 미션 코멘트 잘 반영해주셨습니다. 👍 

다음 단계 미션을 진행할 때 한 번 고민해보시면 좋을 것 같은 내용을 코멘트로 남겼습니다.
다음 단계 미션 진행하실 때 참고 부탁드립니다. 🙏 

4단계 미션에서 뵙겠습니다. 😀

2022-11-15 13:15 UTC, seokhongkim commented on src/main/java/bowling/domain/state/HitState.java
> +                .orElse(null);
`null` 이 발생하는 상황은 없을 것 같네요! 아무것도 해당하지 않는 경우에는 예외를 발생시켜 문제가 있음을 명시적으로 드러내도 좋겠습니다.

2022-11-15 13:15 UTC, seokhongkim commented on src/main/java/bowling/domain/frame/AbstractFrame.java
>      protected final List<Integer> hits;
`hits` 값은 `HitState` 에서 더 많이 사용하는 것으로 보여 추후 이 값을 `HitState` 에서 관리하는 것도 고려해보셔도 좋겠습니다.

현재 코드를 봤을 때 `Frame` 에서 많이 사용하는 것처럼 보이지만, 밸리데이션은 `HitState` 의 구현체에서 할 수 있는 부분이고, 종료 여부를 `hits` 사이즈를 이용해 계산하는데 이 역시 `HitState` 에게 물어서 처리할 수 있을 것 같기도 하네요. :)

2022-11-15 13:15 UTC, merged