4단계 - 볼링 점수판(n명)
next-step/java-bowling pull request #994
Opened 2022-11-17 14:10 UTC by yeonsuyang

안녕하세요 늦어서 죄송합니다.

나름.. 열심히 구조를 바꿔본다고 바꿔보았는데 더 나아진거였으면 좋겠네요ㅠㅠ
지난 리뷰에 주신 리뷰도 반영하여 점수값은 dto두도록 하였는데요.
게임의 계산법은 게임의 규칙 즉 비즈니스로직이라 생각하여 domain에 두고
resultDto를 생성할 때 이용할 수 있게 하였습니다.

그리고 Money를 예로 들어주셨던 부분

public void add(int count) {
        this.pitches.add(new Pitch(count));
}

도 add함수를 외부에서 호출하면 직접 add하는 건 내부에서, 내부의 인스턴스에 하도록 구현하였는데 해당 부분이 Money로 예들어주신 부분과 다른지 궁금합니다. 

감사합니다!!

2022-11-19 11:05 UTC, lowoon requested changes
안녕하세요 연수님!
4단계도 잘 구현해주셨네요 👍 
코멘트 남겼으니 확인해 주세요ㅎㅎ

궁금한 점은 언제든지 DM이나 코멘트 남겨주세요 :)

2022-11-19 11:05 UTC, lowoon commented on src/main/java/bowling/step4/domain/BowlingGame.java
> +        List<Player> players = new ArrayList<>();
players도 일급객체로 만들 수 있을 것 같구요.
```java
        names.stream()
            .map(Player::new)
            .collect(Collectors.toList())
```
를 활용할 수 있을것 같아요.

2022-11-19 11:05 UTC, lowoon commented on src/main/java/bowling/step4/domain/BowlingGame.java
> +    public List<ResultDto> createResult() {
```
public class ClassName {
	// private static final
	// 상수
	// 클래스 변수
	// 인스턴스 변수
	// 생성자
	// 팩토리 메서드
	// 일반 메서드
	// getter, setter
	// equals, hashCode, toString
}
```
순으로 작성하는 것이 좋습니다~

2022-11-19 11:05 UTC, lowoon commented on src/main/java/bowling/step4/domain/BowlingGame.java
> +        return this.players.stream().map(player -> {
ResultDto에 정적팩토리 메서드를 만들고 player를 넘겨서 자기 자신을 만들도록 할 수도 있을 것 같아요.

2022-11-19 11:05 UTC, lowoon commented on src/main/java/bowling/step4/domain/BowlingGame.java
> +                    player.frames().frameMap().values().stream().map(frame -> PitchDto.from(frame.pitches())).collect(Collectors.toList()),
player가 frame을 가지지 않고 BowlingGame에서 관리를 하게 되면 player에서 가져와서 로직을 진행하지 않아도 되지 않을까요?

2022-11-19 11:05 UTC, lowoon commented on src/main/java/bowling/step4/domain/Pitches.java
> +    public List<Pitch> value() {
list의 경우에는 values가 더 명확하지 않을까 생각합니다~

2022-11-19 11:05 UTC, lowoon commented on src/main/java/bowling/step4/domain/Pitches.java
> +        return this.pitches.stream().mapToInt(Pitch::count).sum();
.을 통한 메서드의 진행도 한줄에 하나씩 표현해주는 것이 더 명확하답니다~

2022-11-19 11:05 UTC, lowoon commented on src/main/java/bowling/step4/domain/Pitches.java
> +        this.pitches.add(new Pitch(count));
money하도 다르다고 생각을 하는데요.
불변객체를 엄격하게 지키는 방식으로 간다면 add의 return 값으로 Pitches를 반환하도록 하는 방식이 맞지 않을까해요.
다만 이 부분은 불필요하게 오버프로그래밍을 하는 것 같다는 의견이 있을 수 있기 때문에 상황과 컨벤션에 따라 다를 것 같아요.

2022-11-19 11:05 UTC, lowoon commented on src/main/java/bowling/step4/domain/ScoreCalculator.java
> +    private final Map<Integer, ScoreDto> scoreDtoList;
내부에는 score로 가지고 있고 veiw에 넘겨줄때 dto로 변환을 하면 되지 않을까요?
그리고 로직이 매번 점수를 처음부터 새로 계산하는게 아니라 이전에 계산한 값은 가지고 있고 다음 값만 계산하는 방식인거죠?
아마 장단점이 있을것 같은데 이전 데이터를 꼭 가지고 있어야하는지, 정말 필요한 데이터인지 한번 생각해보면 좋을것 같아요.

2022-11-19 11:05 UTC, lowoon commented on src/test/java/bowling/step4/domain/PitchesTest.java
> +            assertThat(pitches.hasSpare()).isFalse();
기본적으로 테스트는 하나의 기능을 테스트하는 것에 집중을 하는 것 같아요.
하나의 테스트에서 여러개를 테스트하기보다 하나만 검증을 하는것이 더 명확하지 않을까요?

2023-01-13 19:46 UTC, yeonsuyang commented
1.14
안녕하세요
이전의 볼링 코드가 부족한 점이 많은 것 같아
리팩토링 해보았습니다.
refactoring 패키지를 봐주시면 감사합니다.

2023-01-13 19:54 UTC, yeonsuyang commented on src/test/java/bowling/step4/domain/PitchesTest.java
> +            assertThat(pitches.hasSpare()).isFalse();
해당 테스트는 pitches클래스가 스크라이크를 정확하게 인식하였는지의 기능 테스트라고 생각합니다. getsize, getFirstfitch, getSum의 메서는 사실 테스트를 할 필요가 있는 메서드는 아니나 벌어지는 상황에 확인해볼 수 있는 값을 전부 확인해보자는 의미로 넣었습니다.

2023-01-16 10:02 UTC, javajigi approved these changes
마지막까지 미션 진행하느라 넘 수고했어요. 💯 
리팩토링한 코드는 전체적인 설계와 구조 잘 했네요. 
피드백 몇 개 남겼는데요.
추후에 참고해 보세요.
이 미션은 지금 단계에서 마무리하는 것으로 할께요.

2023-01-16 10:02 UTC, javajigi commented on src/main/java/bowling/refactoring/domain/frame/Frame.java
> +public abstract class Frame {
모든 메서드가 abstract 메서드라면 추상 클래스보다는 interface로 구현하는 것을 추천

2023-01-16 10:02 UTC, javajigi commented on src/main/java/bowling/refactoring/domain/frame/NormalFrame.java
> +        }
현재 State에 따라 다음 State를 생성하도록 구현한다면 if을 제거할 수 있지 않을까?

2023-01-16 10:02 UTC, merged